const {createEngine}=require('./engine');const assert=require('assert');
const N=15,idx=(x,y)=>y*N+x;let tests=0;
function board(stones){let b=Array(N*N).fill(0);for(let [x,y,p=1]of stones)b[idx(x,y)]=p;return b;}
function test(name,fn){fn();tests++;console.log('PASS',name);}
test('exact five wins',()=>{let e=createEngine(N,board([[4,7],[5,7],[6,7],[7,7]]));assert(e.winMove(idx(8,7),1));});
test('six is legal but not winning',()=>{let e=createEngine(N,board([[3,7],[4,7],[5,7],[6,7],[7,7]]));assert(e.legal(idx(8,7),1));assert(!e.winMove(idx(8,7),1));});
test('cross double three forbidden for both colors',()=>{for(let p of [1,2]){let e=createEngine(N,board([[6,7,p],[8,7,p],[7,6,p],[7,8,p]]));assert(!e.legal(idx(7,7),p));}});
test('broken double three forbidden',()=>{let e=createEngine(N,board([[5,7],[8,7],[7,5],[7,8]]));assert(!e.legal(idx(7,7),1));});
test('edge blocked three allowed',()=>{let e=createEngine(N,board([[0,1],[2,1],[1,0],[1,2]]));assert(e.legal(idx(1,1),1));});
test('double four allowed',()=>{let e=createEngine(N,board([[5,7],[6,7],[8,7],[7,5],[7,6],[7,8]]));assert(e.legal(idx(7,7),1));});
test('one direction is not double three',()=>{let e=createEngine(N,board([[6,7],[8,7]]));assert(e.legal(idx(7,7),1));});
test('immediate win priority',()=>{let e=createEngine(N,board([[4,7,2],[5,7],[6,7],[7,7],[8,7]]));let r=e.analyze(1,150);assert.equal(r.kind,'win');assert.equal(r.moves[0].i,idx(9,7));});
test('forced defense',()=>{let e=createEngine(N,board([[4,7,1],[5,7,2],[6,7,2],[7,7,2],[8,7,2]]));let r=e.analyze(1,200);assert.equal(r.kind,'block');assert.equal(r.moves[0].i,idx(9,7));});
test('two immediate threats retain warning and legal fallback moves',()=>{let e=createEngine(N,board([[5,7,2],[6,7,2],[7,7,2],[8,7,2]]));let r=e.analyze(1,200);assert.equal(r.kind,'lost');assert(r.fallback&&r.moves.length);assert(r.moves.every(m=>e.legal(m.i,1)));});
test('timeout keeps board intact',()=>{let b=board([[7,7],[8,7,2],[7,8],[8,8,2]]),e=createEngine(N,b);let r=e.analyze(1,150);assert.deepEqual(e.board,b);assert(r.moves.every(m=>e.legal(m.i,1)));assert.deepEqual(e.board,b);});
test('empty and 19 board return center',()=>{for(let n of [15,19]){let r=createEngine(n,Array(n*n).fill(0)).analyze(1,150);assert.equal(r.moves[0].i,Math.floor(n/2)*(n+1));}});
test('user screenshot before I5 has TWO threats and no black win',()=>{const {before,idx}=require('./position.cjs');let e=createEngine(15,before);assert.deepEqual(e.winningMoves(1),[]);assert.deepEqual(e.winningMoves(2).sort((a,b)=>a-b),[idx('I5'),idx('K6')].sort((a,b)=>a-b));let r=e.analyze(1,500);assert.equal(r.kind,'lost');assert(r.fallback&&r.moves.length>0);assert.deepEqual(e.board,before);});
test('blocking either screenshot threat leaves the other',()=>{const {before,idx}=require('./position.cjs');for(let [a,c]of [['I5','K6'],['K6','I5']]){let b=before.slice();b[idx(a)]=1;assert(createEngine(15,b).winMove(idx(c),2));}});
test('completed screenshot is terminal, no recommendation',()=>{const {final}=require('./position.cjs');let e=createEngine(15,final),r=e.analyze(1,100);assert.equal(r.kind,'terminal');assert.deepEqual(r.winners,[2]);assert.equal(r.moves.length,0);});
test('confirmed white I6 is a legal double four',()=>{const {before,idx}=require('./position.cjs');let b=before.slice();b[idx('I6')]=0;let e=createEngine(15,b);assert(e.legal(idx('I6'),2));assert.equal(e.winningMoves(2).length,0);b[idx('I6')]=2;assert.equal(createEngine(15,b).winningMoves(2).length,2);});
test('open three yields proven forcing four',()=>{let b=board([[6,7],[7,7],[8,7]]),e=createEngine(15,b),r=e.analyze(1,1000);assert.equal(r.kind,'forced');assert(r.moves.length);const i=r.moves[0].i;assert(e.legal(i,1));b[i]=1;assert(createEngine(15,b).winningMoves(1).length>=2);});
test('fork-producing opponent move is prevented',()=>{let b=board([[6,7,2],[7,7,2],[8,7,2],[7,6,1]]),e=createEngine(15,b),r=e.analyze(1,1200);assert(r.moves.length);assert([idx(5,7),idx(9,7)].includes(r.moves[0].i));assert.deepEqual(e.board,b);});
test('immediate win is preferred to defense',()=>{let b=board([[4,7],[5,7],[6,7],[7,7],[4,5,2],[5,5,2],[6,5,2],[7,5,2]]);let r=createEngine(15,b).analyze(1,200);assert.equal(r.kind,'win');});
test('multi-step forcing-four proof survives every legal defense',()=>{
 let initial=board([[5,7],[6,7],[7,7],[7,6],[6,5],[4,7,2]]),e=createEngine(15,initial),r=e.analyze(1,1500);assert.equal(r.kind,'forced');const pv=r.moves[0].pv;assert(pv.length>=3);
 function verify(b,k){const attack=pv[k],e=createEngine(15,b);assert(e.legal(attack,1));if(e.winMove(attack,1))return;let a=b.slice();a[attack]=1;let ea=createEngine(15,a),defenses=0;for(let j=0;j<a.length;j++){if(!ea.legal(j,2))continue;assert(!ea.winMove(j,2),'defender has an immediate win');let c=a.slice();c[j]=2;let ec=createEngine(15,c);if(c.some((v,i)=>!v&&ec.winMove(i,1)))continue;defenses++;assert.equal(j,pv[k+1]);assert(k+2<pv.length);verify(c,k+2);}if(k+2>=pv.length)assert.equal(defenses,0);}
 verify(initial,0);assert.deepEqual(e.board,initial);
});
const {coords,position,idx:recordIdx}=require('./game95.cjs');
const {parseOmokRecord,validateOmokAnalysis}=require('./records.js');
const recordText=coords.map((s,k)=>`${k+1}. ${k%2?'흑':'백'} ${s}`).join(' · ');
test('all 95 recorded moves are legal with no premature five',()=>{const r=parseOmokRecord(recordText);assert.equal(r.moves.length,95);assert.equal(r.next,1);assert.equal(r.first,2);assert.deepEqual(r.board,position());assert.equal(createEngine(15,r.board).state().winners.length,0);});
test('I4 double three is explained with two geometric witnesses',()=>{const e=createEngine(15,position()),info=e.moveInfo(recordIdx('I4'),1);assert(!info.legal);assert.equal(info.threes.length,2);const groups=info.threes.map(t=>t.stones.slice().sort((a,b)=>a-b).join(','));assert(groups.includes(['G6','H5','I4'].map(recordIdx).sort((a,b)=>a-b).join(',')));assert(groups.includes(['I4','J5','L7'].map(recordIdx).sort((a,b)=>a-b).join(',')));assert.deepEqual(e.board,position());});
test('95-ply defense I4 is forbidden, not a winning recommendation',()=>{let e=createEngine(15,position()),r=e.analyze(1,500);assert.equal(r.kind,'lost');assert.equal(r.lossReason,'forbidden-defense');assert.deepEqual(r.danger,[recordIdx('I4')]);assert(r.fallback&&r.moves.length>0);assert.equal(r.forbiddenDefenses[0].threes.length,2);});
test('94 H5 creates the forbidden defense, I4 is legal BEFORE H5',()=>{let before=position(93),after=position(94);assert(createEngine(15,before).legal(recordIdx('I4'),1));assert(!createEngine(15,after).legal(recordIdx('I4'),1));assert(createEngine(15,after).legal(recordIdx('G4'),2));});
test('94-ply recommendation excludes H5 and passes final line validation',()=>{const b=position(93),r=createEngine(15,b).analyze(1,1600);assert.notEqual(r.kind,'forced');assert(r.moves.length);assert(r.moves.every(m=>m.i!==recordIdx('H5')));assert.equal(r.moves[0].i,recordIdx('I4'));assert(validateOmokAnalysis(15,b,1,r));});
test('exact-five overline logic remains separate from open-three geometry',()=>{let b=Array(225).fill(0);for(let s of ['G6','H5','J5','L7','E8'])b[recordIdx(s)]=1;assert(!createEngine(15,b).legal(recordIdx('I4'),1));b[recordIdx('F7')]=1;assert(createEngine(15,b).legal(recordIdx('I4'),1));});
test('double three remains forbidden under all eight board symmetries',()=>{const source=position(),target=recordIdx('I4');for(let flip of [false,true])for(let rot=0;rot<4;rot++){const map=i=>{let x=i%15,y=Math.floor(i/15);if(flip)x=14-x;for(let k=0;k<rot;k++){let tmp=x;x=14-y;y=tmp;}return y*15+x;};let b=Array(225).fill(0);source.forEach((v,i)=>b[map(i)]=v);assert(!createEngine(15,b).legal(map(target),1));}});
test('rejected recommendation cannot pass final guard',()=>{assert(!validateOmokAnalysis(15,position(),1,{moves:[{i:recordIdx('I4'),pv:[recordIdx('I4')]}]}));assert(!validateOmokAnalysis(15,position(93),1,{moves:[{i:recordIdx('H5'),pv:['H5','G4','I4'].map(recordIdx)}]}));});
test('record import rejects missing, duplicate, invalid or forbidden moves atomically',()=>{for(let text of ['1. 백 H8 · 3. 흑 G9','1. 백 H8 · 2. 흑 H8','1. 백 P8','1. 백 H8 · 2. 백 G9','1. 백 H8 garbage',recordText+' · 96. 흑 I4'])assert.throws(()=>parseOmokRecord(text));assert.equal(parseOmokRecord(recordText).moves.length,95);});
const game47=require('./game47.cjs');
test('47-ply game is legal and first ends at white F4',()=>{const text=game47.coords.map((s,k)=>`${k+1}. ${k%2?'흑':'백'} ${s}`).join(' · '),r=parseOmokRecord(text);assert.equal(r.moves.length,47);for(let k=0;k<47;k++)assert.equal(createEngine(15,game47.position(k)).state().winners.length,0);assert.deepEqual(createEngine(15,r.board).state().lines[0],['F4','G4','H4','I4','J4'].map(game47.idx));});
test('white J4 creates F4 and K4 double winning endpoints',()=>{const e=createEngine(15,game47.position(45));assert.deepEqual(e.winningMoves(2).sort((a,b)=>a-b),['F4','K4'].map(game47.idx));assert.equal(e.analyze(1,300).kind,'lost');});
test('white forcing attack after black J3 survives every legal defense',()=>{const initial=game47.position(40),e=createEngine(15,initial),proof=e.forcingWin(2,13,1000);assert(proof&&proof.length>=5);
 function verify(b,k){const i=proof[k],ea=createEngine(15,b);assert(ea.legal(i,2));if(ea.winMove(i,2))return;const after=b.slice();after[i]=2;const ed=createEngine(15,after);let escapes=0;for(let j=0;j<225;j++){if(!ed.legal(j,1))continue;assert(!ed.winMove(j,1));const c=after.slice();c[j]=1;if(createEngine(15,c).winningMoves(2).length)continue;escapes++;assert.equal(j,proof[k+1]);assert(k+2<proof.length);verify(c,k+2);}if(k+2>=proof.length)assert.equal(escapes,0);}
 verify(initial,0);assert.deepEqual(e.board,initial);
});
test('39-ply position screens ALL legal points and rejects J3 forcing loss',()=>{const b=game47.position(39),e=createEngine(15,b),count=b.filter((v,i)=>!v&&e.legal(i,1)).length,r=e.analyze(1,3500);assert.equal(r.kind,'lost');assert.equal(r.lossReason,'forcing-line');assert.equal(r.screened,count);assert(r.fallback&&r.moves.length>0);const j=r.rejectedMoves.find(x=>x.i===game47.idx('J3'));assert(j);assert.deepEqual(j.line.slice(0,6),['J3','G4','F3','H4','H3','J4'].map(game47.idx));assert.deepEqual(e.board,b);});
test('37-ply position includes forced-block counterattack traps',()=>{const b=game47.position(37),e=createEngine(15,b),r=e.analyze(1,5000);assert.equal(r.kind,'lost');assert(r.fallback&&r.moves.length>0);assert.equal(r.screened,b.filter((v,i)=>!v&&e.legal(i,1)).length);for(let s of ['E4','E5'])assert.equal(r.rejectedMoves.find(x=>x.i===game47.idx(s)).reason,'forced-reply-trap');assert.deepEqual(e.board,b);});
test('41-ply forced defense is not sold as a safe recommendation',()=>{const r=createEngine(15,game47.position(41)).analyze(1,1500);assert.equal(r.kind,'lost');assert(r.fallback&&r.moves.length>0);});
test('opponent forcing checks preserve immediate winning priority',()=>{let b=game47.position(46),r=createEngine(15,b).analyze(2,100);assert.equal(r.kind,'win');assert.equal(r.moves[0].i,game47.idx('F4'));});
test('forcing-screen timeout never corrupts the position or returns illegal PV',()=>{const b=game47.position(35),e=createEngine(15,b),r=e.analyze(1,40);assert.deepEqual(e.board,b);assert(validateOmokAnalysis(15,b,1,r));});
const game33=require('./game33.cjs');
test('33-ply record is legal and has no completed five yet',()=>{const r=parseOmokRecord(game33.coords.map((s,k)=>`${k+1}. ${k%2?'흑':'백'} ${s}`).join(' · '));assert.deepEqual(r.board,game33.position());assert.deepEqual(createEngine(15,r.board).state().winners,[]);});
test('33 J6 leaves exact-five endpoints I5 and N10; neither single block saves black',()=>{const b=game33.position(),e=createEngine(15,b),ends=['I5','N10'].map(game33.idx);assert.deepEqual(new Set(e.winningMoves(2)),new Set(ends));assert.equal(e.analyze(1,100).kind,'lost');for(const i of ends){const c=b.slice();c[i]=1;assert.equal(createEngine(15,c).winningMoves(2).length,1);}});
test('31 K7 forces K6 but that defense still loses',()=>{const e=createEngine(15,game33.position(31)),r=e.analyze(1,500);assert.deepEqual(e.winningMoves(2),[game33.idx('K6')]);assert.equal(r.kind,'lost');assert(r.fallback&&r.moves.length>0);});
test('quiet L9 attack after ply28 refutes every legal defense',()=>{const b=game33.position(28),e=createEngine(15,b),line=e.threatWin(2,12000);assert(line);assert.equal(line[0],game33.idx('L9'));assert.deepEqual(e.board,b);assert(validateOmokAnalysis(15,b,2,{moves:[{i:line[0],pv:line}]}));const after=b.slice();after[line[0]]=2;const ed=createEngine(15,after);let count=0;for(let j=0;j<225;j++){if(!ed.legal(j,1))continue;assert(!ed.winMove(j,1));const c=after.slice();c[j]=1;assert(createEngine(15,c).forcingWin(2,13,3000),'unrefuted defense '+game33.coord(j));count++;}assert(count>150);});
test('ply27 rejects I11 after proving the quiet L9 attack',()=>{const b=game33.position(27),e=createEngine(15,b),r=e.analyze(1,30000);assert.equal(r.kind,'lost');assert.equal(r.screened,b.filter((v,i)=>!v&&e.legal(i,1)).length);const rejected=r.rejectedMoves.find(m=>m.i===game33.idx('I11'));assert(rejected);
 if(rejected.reason==='counter-threat'){
  assert(r.counterProof?.complete&&r.counterProof.checkedRoots===r.screened&&r.screeningComplete);
  const detail=createEngine(15,b,{strategy:false,counterProofDetails:true}),cert=detail.counterMove(game33.idx('I11'),1,12000,19,1);assert(cert.complete&&cert.proof,'new quiet proof must be complete');
  const after=b.slice();after[game33.idx('I11')]=1;
  const checked=require('../../tools/verify-counter.cjs')(after,require('../../tools/counter-dag.cjs')(cert.proof,{attacker:2}),{loss:false,limitMs:20000});assert(checked.verified,checked.error);assert(checked.boardRestored);assert.deepEqual(detail.board,b);
 }else assert.equal(rejected.reason,'three-threat');assert.deepEqual(e.board,b);});
test('quiet threat timeout preserves board and never invents proof',()=>{const b=game33.position(28),e=createEngine(15,b),line=e.threatWin(2,0);assert.equal(line,null);assert.deepEqual(e.board,b);});
const game31=require('./game31.cjs');
test('31-ply black-first record wins at F11 only on final move',()=>{const parsed=parseOmokRecord(game31.coords.map((s,k)=>`${k+1}. ${k%2?'백':'흑'} ${s}`).join(' · '));assert.equal(parsed.first,1);for(let n=0;n<31;n++)assert.equal(createEngine(15,game31.position(n)).state().winners.length,0);assert.deepEqual(createEngine(15,parsed.board).state().lines[0],['F11','G11','H11','I11','J11'].map(game31.idx));});
test('24 L14 no longer suppresses all moves; legal G6 remains playable',()=>{const b=game31.position(24),e=createEngine(15,b),r=e.analyze(1,10000);assert.equal(r.kind,'lost');assert(r.fallback);assert.equal(r.moves[0].i,game31.idx('G6'));assert(validateOmokAnalysis(15,b,1,r));assert.deepEqual(e.board,b);});
test('every nonterminal turn in winning record offers legal moves even at short budget',()=>{for(let n=0;n<31;n++){const b=game31.position(n),e=createEngine(15,b),p=n%2?2:1,r=e.analyze(p,30);assert(r.moves.length,'empty recommendation at '+n);assert(validateOmokAnalysis(15,b,p,r));assert.deepEqual(e.board,b);}assert.equal(createEngine(15,game31.position()).analyze(2,30).moves.length,0);});
test('early progress provides a usable candidate when analysis is cancelled',()=>{const b=game31.position(24),updates=[];createEngine(15,b).analyze(1,30,r=>updates.push(r));assert(updates.length);assert(updates[0].fallback);assert(validateOmokAnalysis(15,b,1,updates[0]));});
test('after actual G6 G10 continuation engine resumes defense and winning attack',()=>{const r=createEngine(15,game31.position(26)).analyze(1,1000);assert.equal(r.moves[0].i,game31.idx('G11'));const win=createEngine(15,game31.position(30)).analyze(1,100);assert.equal(win.kind,'win');assert(win.moves.some(m=>m.i===game31.idx('F11')));});
const game29=require('./game29.cjs');
test('29-ply record is legal and ends with white diagonal five',()=>{const parsed=parseOmokRecord(game29.coords.map((s,k)=>`${k+1}. ${k%2?'흑':'백'} ${s}`).join(' · '));assert.equal(parsed.first,2);assert.deepEqual(createEngine(15,parsed.board).state().lines[0],['I4','J5','K6','L7','M8'].map(game29.idx));});
test('mandatory defense never lists irrelevant fallback alternatives',()=>{for(const [n,s]of [[19,'E4'],[23,'I5'],[25,'K7']]){const b=game29.position(n),e=createEngine(15,b),updates=[],r=e.analyze(1,1000,x=>updates.push(x));for(const x of [...updates,r]){assert(x.mandatoryDefense);assert.deepEqual(x.moves.map(m=>m.i),[game29.idx(s)]);assert(validateOmokAnalysis(15,b,1,x));}assert.deepEqual(e.board,b);}});
test('27 J5 exposes both exact-five threats and keeps only legal endpoint fallbacks',()=>{const b=game29.position(27),e=createEngine(15,b),r=e.analyze(1,30);assert.equal(r.kind,'lost');assert(!r.mandatoryDefense);assert.deepEqual(new Set(r.danger),new Set(['M8','H3'].map(game29.idx)));assert.deepEqual(new Set(r.moves.map(m=>m.i)),new Set(r.danger));for(const t of r.immediateThreats){assert(t.lines.length);assert(t.lines.every(l=>l.length===5&&l.includes(t.i)));const c=b.slice();c[t.i]=1;assert.equal(createEngine(15,c).winningMoves(2).length,1);}assert.deepEqual(e.board,b);});
test('forbidden mandatory block never leaks into fallback candidates',()=>{const b=position(),e=createEngine(15,b),r=e.analyze(1,30);assert(!r.mandatoryDefense);assert(r.moves.length);assert(r.moves.every(m=>e.legal(m.i,1)&&m.i!==recordIdx('I4')));});
const game48=require('./game48.cjs');
test('48-ply game is legal, black first, ends at white G4',()=>{const r=parseOmokRecord(game48.coords.map((s,k)=>`${k+1}. ${k%2?'백':'흑'} ${s}`).join(' · '));assert.equal(r.first,1);assert.deepEqual(createEngine(15,r.board).state().lines[0],['G8','G7','G6','G5','G4'].map(game48.idx));});
test('46 G5 has two winning ends that cannot both be blocked',()=>{const b=game48.position(46),e=createEngine(15,b),r=e.analyze(1,50);assert.deepEqual(new Set(r.danger),new Set(['G4','G9'].map(game48.idx)));assert(r.fallback);for(const m of r.moves){const c=b.slice();c[m.i]=1;assert(createEngine(15,c).winningMoves(2).length);}});
test('expensive 28-ply safety screen reserves time for real comparison',()=>{const b=game48.position(28),e=createEngine(15,b),r=e.analyze(1,10000);assert(r.depth>=1,'comparison starved by screening');assert(r.moves.length);assert(validateOmokAnalysis(15,b,1,r));assert.deepEqual(e.board,b);if(!r.screeningComplete)assert.equal(r.forcingChecksComplete,false);});
test('34-ply interrupted screening retains unexplored moves without claiming proven loss',()=>{const b=game48.position(34),e=createEngine(15,b),r=e.analyze(1,1500);assert(r.moves.length);assert(r.depth>=1);assert(validateOmokAnalysis(15,b,1,r));if(!r.screeningComplete)assert.notEqual(r.kind,'lost');assert.deepEqual(e.board,b);});
const {autoStable}=require('./engine');
test('automatic stable stop requires completed depths, PV, rankings and sustained score gaps',()=>{
 const rounds=[200,240,220].map((score,k)=>({i:1,score,depth:k+2,pv:[1,2,3],ranking:[1,2],gap:100+k*10}));
 const checks={screeningComplete:true,forcingChecksComplete:true},moves=[{i:1,score:220,status:'screened'},{i:2,score:100}];
 assert(autoStable(rounds,4,1000,checks,moves));
 assert(!autoStable(rounds,3,1000,checks,moves));assert(!autoStable(rounds,4,500,checks,moves));
 assert(!autoStable(rounds,4,1000,{...checks,screeningComplete:false},moves));
 assert(!autoStable(rounds,4,1000,{...checks,forcingChecksComplete:false},moves));
 assert(!autoStable([{...rounds[0],i:2},...rounds.slice(1)],4,1000,checks,moves));
 assert(!autoStable(rounds,4,1000,checks,[moves[0],{i:2,score:210}]));
 assert(!autoStable(rounds,4,1000,checks,[{...moves[0],status:'unverified'}]));
 for(const unstable of [
  rounds.map((r,k)=>({...r,pv:[1,k+10,3]})),
  rounds.map((r,k)=>({...r,ranking:[1,k+10]})),
  rounds.map((r,k)=>({...r,gap:[500,250,120][k]})),
  rounds.map(r=>({...r,pv:undefined})),
  rounds.map((r,k)=>({...r,depth:k===0?1:r.depth})),
 ])assert(!autoStable(unstable,4,1500,checks,moves),'unstable or missing history must keep searching');
 const single=rounds.map(r=>({...r,ranking:[1],gap:null}));assert(autoStable(single,4,1500,checks,[moves[0]]));
});
test('automatic immediate win and forced defense finish without long search',()=>{const start=Date.now(),win=createEngine(15,game31.position(30)).analyze(1,'auto'),block=createEngine(15,game29.position(25)).analyze(1,'auto');assert(win.automatic);assert.equal(win.kind,'win');assert.equal(block.kind,'block');assert.equal(block.moves[0].i,game29.idx('K7'));assert(block.autoReason.includes('미검사'));assert(Date.now()-start<1000);});
test('automatic opening and terminal positions return immediately',()=>{const r=createEngine(15,Array(225).fill(0)).analyze(1,'auto');assert.equal(r.moves[0].i,112);assert(r.automatic);assert.equal(createEngine(15,game48.position()).analyze(1,'auto').kind,'terminal');});
test('automatic complex position preserves legal moves and stops at bounded time',()=>{const b=game48.position(34),e=createEngine(15,b),start=Date.now(),r=e.analyze(1,'auto');assert(r.automatic&&r.autoReason);assert(Date.now()-start<9500);assert(r.depth>0);assert(validateOmokAnalysis(15,b,1,r));assert.deepEqual(e.board,b);console.log('AUTO timing:',Date.now()-start,'ms; depth',r.depth,';',r.autoReason);});
const fs=require('fs'),vm=require('vm'),html=fs.readFileSync(process.env.OMOK_TEST_HTML||'outputs/omok.html','utf8');for(const m of html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g))new vm.Script(m[1]);
console.log(`${tests} engine scenarios and HTML scripts passed`);
