'use strict';const assert=require('node:assert/strict'),create=require('../src/reader-engine.js').createEngine,idx=c=>(+c.slice(1)-1)*15+c.charCodeAt(0)-65,base='G10 F11 I12 G11 G12 I11 I10 H9 A2 H10 N2 H12 A4 N14'.split(' '),board=m=>{const b=Array(225).fill(0);m.forEach((c,k)=>b[idx(c)]=k%2?1:2);return b;};
const b=board(base),e=create(15,b,{strategy:false,counterProofDetails:true}),legal=Array.from({length:225},(_,i)=>i).filter(i=>e.legal(i,2));assert(!e.legal(idx('H11'),2));const zero=e.counterLoss(2,0,19,1);assert(!zero.lossProven&&!zero.complete);assert.deepEqual(e.board,b);const loss=e.counterLoss(2,1500,19,1);assert(loss.lossProven&&loss.complete);assert.equal(loss.branches.length,legal.length);assert.equal(new Set(loss.branches.map(x=>x.i)).size,legal.length);assert.deepEqual(e.board,b);const independent=require('../tools/verify-counter.cjs')(b,require('../tools/counter-dag.cjs')(null,{attacker:1,roots:loss.branches}));assert(independent.verified,independent.error);assert(independent.boardRestored);e.analyze(2,30);assert(e.counterCertificate(1,100,7,0).proof,'analysis clock restored for later bounded proof');assert.deepEqual(e.board,b);
const winBoard=board(base.concat('A5 L1 B5 M3 C5 O7 D5 L15'.split(' '))),win=create(15,winBoard,{strategy:false}),own=win.counterLoss(2,200,19,1);assert(own.ownImmediateWin&&!own.lossProven);assert(win.counterMove(idx('E5'),2,100).ownWin);assert.equal(win.analyze(2,'auto').kind,'win');assert.deepEqual(win.board,winBoard);
console.log('PASS crossed broken-three all legal defenses, forbidden center, exact-five counterwin, bounded timeout, deadline restoration and board undo');


const original34='H8 G9 F8 G7 G8 I8 H9 F7 H7 H10 I6 J5 E8 D8 F9 E10 D7 G10 F10 I11 H5 H6 G4 F3 J7 K8 F5 E6 I10 J11 G5 E5 E4 G13'.split(' '),userBoard=board(original34),actual=create(15,userBoard,{strategy:false,optimized:true}),allLegal=Array.from({length:225},(_,i)=>i).filter(i=>actual.legal(i,2)),g13=actual.counterLoss(2,14100,19,1);assert(g13.lossProven&&g13.complete);assert.equal(g13.branches.length,allLegal.length);assert.equal(allLegal.length,191);assert.deepEqual(actual.board,userBoard);console.log('PASS user G13: all191 legal moves lose, including forcing counterattack delays');


const vm=require('vm'),context={performance:{now:(()=>{let t=0;return()=>++t;})()},Date};vm.createContext(context);vm.runInContext(require('fs').readFileSync('src/reader-engine.js','utf8'),context);const partialEngine=context.createEngine(15,b,{strategy:false}),partial=partialEngine.counterLoss(2,50,19,1);assert(!partial.lossProven&&!partial.complete);assert(partial.branches.length>0&&partial.branches.length<legal.length);const retained=partialEngine.counterRejections(2,partial);assert.equal(retained.length,partial.branches.length);assert(retained.every(x=>x.verifiedRefutation&&x.counterProof.complete&&x.line[0]===x.i));assert.deepEqual(Array.from(partialEngine.board),b);console.log('PASS complete individual refutations survive an interrupted all-root check; global unknown retained');
