'use strict';
// Independent persistence checks use legal played games, real family grouping,
// and injected crashes. Fixtures never train or adopt a production model.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),cp=require('node:child_process');
const S=require('../tools/learning/state.cjs'),R=require('../tools/learning/replay.cjs'),J=require('../tools/learning/journal.cjs'),C=require('../tools/learning/corpus.cjs'),N=require('../src/neural-evaluator.js');
fs.mkdirSync(path.join(S.ROOT,'work'),{recursive:true});
const temporary=fs.mkdtempSync(path.join(S.ROOT,'work','learning-corpus-test-')),outside=fs.mkdtempSync(path.join(os.tmpdir(),'omok-corpus-outside-')),contexts=[],passed=[];
const copy=value=>JSON.parse(JSON.stringify(value));
function context(name){const dir=path.join(temporary,name);fs.mkdirSync(dir);const state={schemaVersion:1,runId:name,rulesId:S.RULES_ID,featureVersion:S.FEATURE_VERSION,identity:S.sourceIdentity(),status:'stopped',phase:'generate',cycle:1,counters:{samples:0,generatedGames:0,completedGames:0,analyzedPositions:0},activeGames:{},generationIndex:0,history:[],adoptions:[],errors:[]},ctx={dir,state,settings:S.defaults()};S.atomic(path.join(dir,'settings.json'),ctx.settings);S.atomic(path.join(dir,'records.json'),[]);S.save(ctx);contexts.push(ctx);return ctx;}
function reload(ctx){return {dir:ctx.dir,state:S.read(path.join(ctx.dir,'state.json')),settings:S.read(path.join(ctx.dir,'settings.json'))};}
function rows(file){return fs.existsSync(file)?fs.readFileSync(file,'utf8').trim().split('\n').filter(Boolean).map(line=>JSON.parse(line)):[];}
function record(id,coords,split='train'){return R.normalizeRecords({id,first:1,events:coords,split,source:'persistence fixture'})[0];}
const coordinates=['H8','A1','I8','A2','J8','A3','K8','A4','L8'],otherCoordinates=['F6','B1','G6','B2','H6','B3','I6','B4','J6'];
function playedGame(id,rec,split='train',branch=null){const played=R.replay(rec);return {id,index:Number(id.replace(/\D/g,''))||0,seed:123,rng:345,firstPlayer:rec.first,opening:rec.events.slice(0,4),events:rec.events.slice(4),board:played.board,p:played.p,familyId:'fixture-'+id,split,branch:branch||{sourceGame:null,prefix:4},model:null,modelVersion:'untrained-current',lessons:[],lessonHash:S.hash([]),samples:played.positions.slice(4,6).map(pos=>({board:pos.board,p:pos.p,ply:pos.ply})),completed:played.completed,winner:played.draw?0:played.winner,elapsedMs:100,reason:played.completed?'played-exact-five':'ply-limit'};}
function sample(game,pos,id,split=game.split){return {schemaVersion:1,sampleId:id,rulesId:S.RULES_ID,featureVersion:S.FEATURE_VERSION,familyId:game.familyId,split,positionKey:R.positionKey(pos.board,pos.p,game.firstPlayer),features:Array.from(N.extractFeatures(pos.board,pos.p,game.firstPlayer)),target:game.winner===0?0:game.winner===pos.p?1:-1,weight:1,labelType:'terminal',position:{board:pos.board,p:pos.p,firstPlayer:game.firstPlayer},source:{gameId:game.id,ply:pos.ply,kind:'actual-played-terminal',modelVersion:game.modelVersion}};}
function sourceFixture(name){const ctx=context(name),rec=record('same-record-id',coordinates),other=record('other-record-id',otherCoordinates),game=playedGame('game-0',rec,'validation',{sourceGame:rec.id,prefix:4}),independent=playedGame('game-1',other,'validation'),cutoff=playedGame('game-2',{...other,events:other.events.slice(0,8)},'test');ctx.state.status='complete';ctx.state.counters={samples:3,generatedGames:3,completedGames:2};S.atomic(path.join(ctx.dir,'records.json'),[rec]);S.atomic(path.join(ctx.dir,'lessons.json'),{schemaVersion:1,rulesId:S.RULES_ID,lessons:[]});S.append(path.join(ctx.dir,'games.jsonl'),{...game,samples:undefined,model:undefined});S.append(path.join(ctx.dir,'games.jsonl'),{...independent,samples:undefined,model:undefined});S.append(path.join(ctx.dir,'games.jsonl'),{...cutoff,samples:undefined,model:undefined});S.append(path.join(ctx.dir,'dataset.jsonl'),sample(game,game.samples[0],'original-row-0','validation'));S.append(path.join(ctx.dir,'dataset.jsonl'),sample(game,game.samples[1],'original-row-1','train'));S.append(path.join(ctx.dir,'dataset.jsonl'),sample(independent,independent.samples[0],'original-row-2','train'));S.save(ctx);return {ctx,rec,game,independent,cutoff};}
function hashes(ctx){return Object.fromEntries(fs.readdirSync(ctx.dir).filter(name=>fs.statSync(path.join(ctx.dir,name)).isFile()).map(name=>[name,S.fileHash(path.join(ctx.dir,name))]));}
function rawContext(name){const c=context(name);c.state.cycle=0;c.state.freshModel=true;c.state.trial=0;S.save(c);return c;}
function missingAncestor(source,name){const ancestor=context(name),digests={'state.json':S.fileHash(path.join(ancestor.dir,'state.json')),'settings.json':S.fileHash(path.join(ancestor.dir,'settings.json'))};S.atomic(path.join(source.dir,'continuation.json'),{schemaVersion:1,source:ancestor.dir,sourceRun:ancestor.state.runId,sourceIdentity:ancestor.state.identity,sourceId:S.hash([ancestor.dir,digests]),hashes:digests,complete:true});fs.renameSync(ancestor.dir,ancestor.dir+'-missing');}
async function check(name,fn){await fn();passed.push(name);console.log('PASS '+name);}
(async()=>{
 await check('journal reserves large writes before append and retains disk budget codes through source wrappers',async()=>{const ctx=context('journal-budget'),data={sampleId:'reserved-row',familyId:'reserved-family',description:'x'.repeat(40000)};ctx.settings.maxDiskBytes=S.diskBytes(ctx.dir)+128;assert.throws(()=>J.appendRows(ctx.dir,'dataset.jsonl',[data],'sampleId',ctx),error=>error.code==='DISK_BUDGET');assert.equal(fs.existsSync(path.join(ctx.dir,'dataset.jsonl')),false);assert.equal(ctx.state.stopReason.kind,'disk-budget');ctx.settings.maxDiskBytes=S.defaults().maxDiskBytes;assert.equal(J.appendRows(ctx.dir,'dataset.jsonl',[data],'sampleId',ctx),1);await assert.rejects(C.eachLine(path.join(ctx.dir,'dataset.jsonl'),()=>{throw Object.assign(Error('budget fixture'),{code:'DISK_BUDGET'});}),error=>error.code==='DISK_BUDGET'&&/line 1/.test(error.message));});
 await check('continuation rejects same external record ID with different events before copying',async()=>{const source=sourceFixture('source-record-conflict'),destination=context('record-conflict-destination'),conflict=record(source.rec.id,otherCoordinates);S.atomic(path.join(destination.dir,'records.json'),[conflict]);const original=S.fileHash(path.join(destination.dir,'records.json'));await assert.rejects(C.continueFrom(destination,source.ctx.dir),/Conflicting record ID/);assert.equal(S.fileHash(path.join(destination.dir,'records.json')),original);assert.equal(fs.existsSync(path.join(destination.dir,'continuation.json')),false);assert.equal(rows(path.join(destination.dir,'dataset.jsonl')).length,0);});
 await check('missing warm ancestry is rejected by read-only preflight before any continuation marker or index',async()=>{
  const source=sourceFixture('raw-strict-source'),destination=context('raw-strict-destination');missingAncestor(source.ctx,'raw-strict-ancestor');const before=hashes(source.ctx),destinationBefore=hashes(destination);assert.throws(()=>C.continuationPreflight(source.ctx.dir),/Missing exposure continuation ancestor/);await assert.rejects(()=>C.continueFrom(destination,source.ctx.dir),/Missing exposure continuation ancestor/);assert.deepEqual(hashes(destination),destinationBefore);assert.deepEqual(hashes(source.ctx),before);
 });
 await check('raw recovery resets model history, reserves every played position and preserves source bytes',async()=>{
  const P=require('../tools/learning/snapshot.cjs'),source=sourceFixture('raw-cold-source'),destination=rawContext('raw-cold-destination');missingAncestor(source.ctx,'raw-cold-ancestor');source.ctx.state.trial=7;source.ctx.state.counters.trainingUpdates=99;source.ctx.state.lastTrainingSampleCount=3;S.save(source.ctx);for(const name of ['candidate.json','champion.json','warm-start.json'])S.atomic(path.join(source.ctx.dir,name),{modelId:'lost-warm-model',training:{updates:99}});const before=hashes(source.ctx),manifest=await C.continueFrom(destination,source.ctx.dir,{mode:'raw-reset'});assert.equal(manifest.mode,'raw-reset');assert.equal(manifest.modelReset,true);assert.equal(manifest.complete,true);assert.equal(destination.state.counters.samples,3);assert.equal(destination.state.counters.generatedGames,3);assert.equal(destination.state.counters.trainingUpdates,0);assert.equal(destination.state.trial,0);assert.equal(destination.state.lastTrainingSampleCount,0);assert.equal(destination.state.generationIndex,3);assert(rows(path.join(destination.dir,'dataset.jsonl')).every(r=>r.split==='train'));assert(rows(path.join(destination.dir,'games.jsonl')).every(r=>r.split==='train'));assert(S.read(path.join(destination.dir,'records.json')).every(r=>r.split==='train'));for(const name of ['candidate.json','champion.json','warm-start.json'])assert(!fs.existsSync(path.join(destination.dir,name)));
  const registry=rows(path.join(destination.dir,P.exposureName)),keys=new Set(registry.filter(r=>r.kind==='position').map(r=>r.key));assert(registry.every(r=>r.split==='train'));for(const rec of [source.rec,{first:source.independent.firstPlayer,events:[...source.independent.opening,...source.independent.events]}, {first:source.cutoff.firstPlayer,events:[...source.cutoff.opening,...source.cutoff.events]}])for(const p of R.replay(rec).positions)assert(keys.has(R.positionKey(p.board,p.p,rec.first)));assert.equal(P.verifyLineage(destination.dir).mode,'raw-reset');await P.ensureExposures(destination);assert.deepEqual(hashes(source.ctx),before);
  // A later ordinary continuation imports the portable cold-model exposure
  // proof; unavailable historical warm ancestors remain untrusted.
  const onward=context('raw-safe-onward');assert(C.continuationPreflight(destination.dir));await C.continueFrom(onward,destination.dir);await P.ensureExposures(onward);assert(keys.size<=new Set(rows(path.join(onward.dir,P.exposureName)).filter(r=>r.kind==='position'&&r.split==='train').map(r=>r.key)).size);assert.deepEqual(hashes(source.ctx),before);
  const overlapKey=R.positionKey(source.game.samples[0].board,source.game.samples[0].p,source.game.firstPlayer),common={schemaVersion:1,rulesId:S.RULES_ID,featureVersion:S.FEATURE_VERSION,features:Array(32).fill(0),target:0,weight:1,labelType:'terminal'};J.appendRows(destination.dir,'dataset.jsonl',[{...common,sampleId:'recovered-now-validation',familyId:'new-overlap-family',split:'validation',positionKey:overlapKey},{...common,sampleId:'independent-validation',familyId:'independent-validation',split:'validation',positionKey:'independent-validation'},{...common,sampleId:'independent-final',familyId:'independent-final',split:'test',positionKey:'independent-final'}],'sampleId');const data=path.join(destination.dir,'datasets/cycle-1.jsonl'),next=await P.snapshotData(destination,data);assert.equal(next.selection.temporalOverlapExcluded,1);assert(rows(data).some(r=>r.sampleId==='independent-validation'));assert(rows(data).some(r=>r.sampleId==='independent-final'));assert(!rows(data).some(r=>r.sampleId==='recovered-now-validation'));
 });
 await check('raw recovery rejects inherited models and immutable mode tampering',async()=>{
  const P=require('../tools/learning/snapshot.cjs'),source=sourceFixture('raw-refusal-source');missingAncestor(source.ctx,'raw-refusal-ancestor');for(const name of ['candidate.json','champion.json','warm-start.json','checkpoints/old.pt']){const destination=rawContext('raw-model-refusal-'+name.replace(/[^a-z0-9]/gi,'-'));S.atomic(path.join(destination.dir,name),'preserved-artifact');await assert.rejects(()=>C.continueFrom(destination,source.ctx.dir,{mode:'raw-reset'}),/model|checkpoint/);assert(!fs.existsSync(path.join(destination.dir,'continuation.json')));assert.equal(fs.readFileSync(path.join(destination.dir,name),'utf8'),'preserved-artifact');}
  const notFresh=context('raw-not-fresh');await assert.rejects(()=>C.continueFrom(notFresh,source.ctx.dir,{mode:'raw-reset'}),/fresh model/);const destination=rawContext('raw-mode-bound');await C.continueFrom(destination,source.ctx.dir,{mode:'raw-reset'});await assert.rejects(()=>C.continueFrom(destination,source.ctx.dir,{mode:'normal'}),/mode changed/);const marker=path.join(destination.dir,'continuation.json'),original=S.read(marker);S.atomic(marker,{...original,mode:'normal'});assert.throws(()=>P.verifyLineage(destination.dir),/provenance|lineage/);S.atomic(marker,original);const proofFile=path.join(destination.dir,P.lineageName),proof=S.read(proofFile);S.atomic(proofFile,{...proof,mode:undefined,modelReset:undefined,scope:undefined,proofHash:S.hash([proof.continuationSourceId,proof.registry,proof.sources])});assert.throws(()=>P.verifyLineage(destination.dir),/lineage/);S.atomic(proofFile,proof);await P.ensureExposures(destination);
 });
 await check('raw recovery preserves the shared evaluation highwater without inheriting source trial counters',async()=>{
  const L=require('../tools/learning/trial-ledger.cjs'),ledger=path.join(temporary,'raw-shared-ledger.sqlite'),owner=rawContext('raw-ledger-owner'),source=sourceFixture('raw-ledger-source'),destination=rawContext('raw-ledger-destination');owner.trialLedgerFile=ledger;owner.state.trial=4;L.reconcile(owner);destination.trialLedgerFile=ledger;L.reconcile(destination);assert.equal(destination.state.trial,4);source.ctx.state.trial=91;S.save(source.ctx);await C.continueFrom(destination,source.ctx.dir,{mode:'raw-reset'});assert.equal(destination.state.trial,4);assert.equal(destination.state.evaluationBudget.highwater,4);
 });
 await check('CLI main initializes a fresh model and recovers broken ancestry after ledger reconciliation',async()=>{
  const L=require('../tools/learning/trial-ledger.cjs'),run=require('../tools/learning/run.cjs'),ledger=path.join(temporary,'raw-main-ledger.sqlite'),owner=rawContext('raw-main-ledger-owner'),source=sourceFixture('raw-main-source'),dir=path.join(temporary,'raw-main-destination');owner.trialLedgerFile=ledger;owner.state.trial=4;L.reconcile(owner);missingAncestor(source.ctx,'raw-main-ancestor');source.ctx.state.trial=91;S.save(source.ctx);const before=hashes(source.ctx),reconcile=L.reconcile;try{L.reconcile=(context,arena)=>{context.trialLedgerFile=ledger;return reconcile(context,arena);};await run.main(['init','--run='+dir,'--from-run='+source.ctx.dir,'--continuation-mode=raw-reset','--fresh-model','--device=cpu','--no-adopt']);}finally{L.reconcile=reconcile;J.close(dir);C.close(dir);}const state=S.read(path.join(dir,'state.json'));assert.equal(state.freshModel,true);assert.equal(state.initialIncumbentHash,null);assert.equal(state.pendingModelExposure,null);assert.equal(state.trial,4);assert.equal(state.evaluationBudget.highwater,4);assert.equal(state.counters.trainingUpdates,0);assert.equal(state.status,'complete');assert.equal(S.read(path.join(dir,'continuation.json')).mode,'raw-reset');assert(!fs.existsSync(path.join(dir,'champion.json')));assert.deepEqual(hashes(source.ctx),before);
 });
 await check('cold imported samples and waiting-data retries generate fresh holdouts before concurrent training',async()=>{
  const run=require('../tools/learning/run.cjs');for(const mode of ['cold-import','waiting-data']){const destination=context('raw-holdout-gate-'+mode),order=[];destination.settings.continuous=true;destination.settings.concurrentTraining=true;destination.settings.minNewSamples=1;destination.state.counters.samples=3;destination.state.counters.generatedGames=3;destination.state.lastTrainingSampleCount=0;destination.state.pipeline={stage:'generate',target:4};if(mode==='cold-import')destination.state.continuation={mode:'raw-reset',importedGames:3};else destination.state.training={status:'waiting-data'};assert.equal(await run.cycle(destination,{},Date.now()+30000,{generate:async c=>{order.push('generate');c.state.counters.generatedGames++;c.state.counters.samples++;return true;},train:async()=>{order.push('train');return false;}}),false);assert.deepEqual(order,['generate','train']);}
 });
 await check('actual raw-recovery crashes resume the sealed training-only registry and copy exactly once',async()=>{
  const P=require('../tools/learning/snapshot.cjs'),source=sourceFixture('raw-crash-source');missingAncestor(source.ctx,'raw-crash-ancestor');const before=hashes(source.ctx),child="const S=require('./tools/learning/state.cjs'),J=require('./tools/learning/journal.cjs'),C=require('./tools/learning/corpus.cjs'),path=require('node:path');const dir=process.argv[1],boundary=process.argv[3],context={dir,state:S.read(path.join(dir,'state.json')),settings:S.read(path.join(dir,'settings.json'))},append=J.appendRows,atomic=S.atomic;J.appendRows=(...args)=>{const n=append(...args);if((boundary==='exposure'&&args[1]==='temporal-exposures.jsonl')||(boundary==='copy'&&args[1]==='games.jsonl'))process.exit(73);return n;};S.atomic=(target,value)=>{const n=atomic(target,value);if((boundary==='lineage'&&path.basename(target)==='temporal-exposures-lineage.json')||(boundary==='seal'&&path.basename(target)==='temporal-exposures-ready.json'))process.exit(73);return n;};C.continueFrom(context,process.argv[2],{mode:'raw-reset'}).then(()=>process.exit(0)).catch(error=>{console.error(error);process.exit(1);});";
  for(const boundary of ['exposure','lineage','seal','copy']){const destination=rawContext('raw-crash-'+boundary),result=cp.spawnSync(process.execPath,['-e',child,destination.dir,source.ctx.dir,boundary],{cwd:S.ROOT,encoding:'utf8',timeout:20000,windowsHide:true});assert.equal(result.status,73,result.stderr);assert.equal(S.read(path.join(destination.dir,'continuation.json')).complete,false);const resumed=reload(destination);assert.equal((await C.continueFrom(resumed,source.ctx.dir)).complete,true);await P.ensureExposures(resumed);assert.equal(rows(path.join(destination.dir,'games.jsonl')).length,3);assert.equal(rows(path.join(destination.dir,'dataset.jsonl')).length,3);const exposures=rows(path.join(destination.dir,P.exposureName));assert(exposures.every(r=>r.split==='train'));assert.equal(new Set(exposures.map(r=>r.id)).size,exposures.length);assert(!fs.existsSync(path.join(destination.dir,'raw-recovery-exposure-intent.json')));const completed=hashes(destination);await C.continueFrom(resumed,source.ctx.dir);assert.deepEqual(hashes(destination),completed);assert.deepEqual(hashes(source.ctx),before);}
 });
 await check('continuation inherits prior published training exposure without changing the source',async()=>{
  const source=sourceFixture('source-temporal'),destination=context('temporal-destination'),snapshot=require('../tools/learning/snapshot.cjs'),historical=rows(path.join(source.ctx.dir,'dataset.jsonl'))[0],priorFile=path.join(source.ctx.dir,'datasets','cycle-1.jsonl');historical.split='train';S.atomic(priorFile,JSON.stringify(historical)+'\n');S.atomic(priorFile+'.manifest.json',{schemaVersion:1,file:path.basename(priorFile),rulesId:S.RULES_ID,featureVersion:S.FEATURE_VERSION,sha256:S.fileHash(priorFile)});const before=hashes(source.ctx),priorHash=S.fileHash(priorFile);await C.continueFrom(destination,source.ctx.dir);assert.deepEqual(hashes(source.ctx),before);assert.equal(S.fileHash(priorFile),priorHash);assert.ok(rows(path.join(destination.dir,snapshot.exposureName)).some(r=>r.kind==='position'&&r.key===historical.positionKey&&r.split==='train'));
  const common={schemaVersion:1,rulesId:S.RULES_ID,featureVersion:S.FEATURE_VERSION,features:Array(32).fill(0),target:0,weight:1,labelType:'terminal'};J.appendRows(destination.dir,'dataset.jsonl',[{...common,sampleId:'future-validation',familyId:'new-validation',split:'validation',positionKey:historical.positionKey},{...common,sampleId:'fresh-validation',familyId:'fresh-validation',split:'validation',positionKey:'fresh-validation'},{...common,sampleId:'fresh-final',familyId:'fresh-final',split:'test',positionKey:'fresh-final'}],'sampleId');const target=path.join(destination.dir,'datasets','cycle-1.jsonl'),manifest=await snapshot.snapshotData(destination,target);assert.ok(manifest.selection.temporalOverlapExcluded>=1);assert.ok(!rows(target).some(r=>r.sampleId==='future-validation'));assert.ok(rows(target).some(r=>r.sampleId==='fresh-validation'));assert.deepEqual(hashes(source.ctx),before);
 });
 await check('legacy two-ancestor warm lineage is sealed before future holdouts and independent arena openings',async()=>{
  const snapshot=require('../tools/learning/snapshot.cjs'),arena=require('../tools/learning/arena.cjs'),old=context('legacy-grandparent'),parent=context('legacy-parent'),source=context('legacy-source'),destination=context('legacy-future'),probe=context('legacy-arena-probe');for(const c of [probe,destination]){c.settings.pairs=2;c.trialLedgerFile=path.join(c.dir,'isolated-trial-ledger.sqlite');}
  const openings=arena.plan(probe,{modelId:'legacy-warm-fixture'}).games.filter(g=>g.opponent==='baseline'&&g.candidateFirst),key=g=>R.positionKey(g.board,g.p,g.firstPlayer),writeSnapshot=(c,name,g,split)=>{const file=path.join(c.dir,'datasets',name+'.jsonl');S.atomic(file,JSON.stringify({familyId:g.familyId,positionKey:key(g),split,features:{reserved:true},target:{reserved:true}})+'\n');S.atomic(file+'.manifest.json',{schemaVersion:1,rulesId:S.RULES_ID,featureVersion:S.FEATURE_VERSION,file:path.basename(file),sha256:S.fileHash(file)});return file;},link=(child,ancestor)=>{const names=['state.json','settings.json','records.json','continuation.json'].filter(name=>fs.existsSync(path.join(ancestor.dir,name))),digests=Object.fromEntries(names.map(name=>[name,S.fileHash(path.join(ancestor.dir,name))]));S.atomic(path.join(child.dir,'continuation.json'),{schemaVersion:1,source:ancestor.dir,sourceRun:ancestor.state.runId,sourceIdentity:ancestor.state.identity,sourceId:S.hash([ancestor.dir,digests]),hashes:digests,complete:true});};
  const oldFile=writeSnapshot(old,'old',openings[0],'train'),parentFile=writeSnapshot(parent,'parent',openings[1],'validation');link(parent,old);link(source,parent);S.atomic(path.join(source.dir,'warm-start.json'),{modelId:'legacy-warm-fixture',training:{updates:1,datasetHash:S.fileHash(oldFile)}});const before=[old,parent,source].map(hashes),prior=[oldFile,parentFile].map(S.fileHash);
  const proof=await snapshot.importExposures(destination.dir,source.dir,destination);assert.equal(proof.sources.length,3);assert.equal(snapshot.verifyLineage(destination.dir).proofHash,proof.proofHash);assert.ok(rows(path.join(destination.dir,snapshot.exposureName)).some(row=>row.key===key(openings[0])&&row.split==='train'));
  const common={schemaVersion:1,rulesId:S.RULES_ID,featureVersion:S.FEATURE_VERSION,features:Array(32).fill(0),target:0,weight:1,labelType:'terminal'},data=[{sampleId:'old-train-now-test',familyId:'new-final',split:'test',positionKey:key(openings[0])},{sampleId:'old-validation-now-test',familyId:'new-final-2',split:'test',positionKey:key(openings[1])},{sampleId:'fresh-train',familyId:'fresh-training',split:'train',positionKey:'fresh-training'},{sampleId:'fresh-validation',familyId:'fresh-validation',split:'validation',positionKey:'fresh-validation'},{sampleId:'fresh-final',familyId:'fresh-final',split:'test',positionKey:'fresh-final'}];S.atomic(path.join(destination.dir,'dataset.jsonl'),data.map(row=>JSON.stringify({...common,...row})+'\n').join(''));
  const file=path.join(destination.dir,'datasets/cycle-1.jsonl'),manifest=await snapshot.snapshotData(destination,file);assert.equal(manifest.selection.temporalOverlapExcluded,2);assert.ok(!rows(file).some(row=>row.sampleId.startsWith('old-')));const excluded=await arena.loadExclusions(destination);try{const planned=arena.plan(destination,{modelId:'legacy-warm-fixture'},excluded.positions,excluded);assert.ok(planned.games.every(game=>!openings.some(old=>old.familyId===game.familyId||key(old)===key(game))));}finally{excluded.close();}
  [old,parent,source].forEach((c,n)=>assert.deepEqual(hashes(c),before[n]));[oldFile,parentFile].forEach((file,n)=>assert.equal(S.fileHash(file),prior[n]));
  // Once copied and prefix-verified, the portable lineage no longer depends on
  // keeping every old run directory available for future local snapshots.
  fs.renameSync(old.dir,old.dir+'-temporarily-unavailable');try{await snapshot.ensureExposures(destination);assert.equal(snapshot.verifyLineage(destination.dir).proofHash,proof.proofHash);}finally{fs.renameSync(old.dir+'-temporarily-unavailable',old.dir);}
 });
 await check('missing, tampered, cyclic, outside and incomplete legacy ancestry rejects before copying any exposure',async()=>{
  const snapshot=require('../tools/learning/snapshot.cjs'),link=(child,ancestor,{complete=true,names=['state.json','settings.json']}={})=>{const digests=Object.fromEntries(names.map(name=>[name,S.fileHash(path.join(ancestor.dir,name))]));S.atomic(path.join(child.dir,'continuation.json'),{schemaVersion:1,source:ancestor.dir,sourceRun:ancestor.state.runId,sourceIdentity:ancestor.state.identity,sourceId:S.hash([ancestor.dir,digests]),hashes:digests,complete});};
  for(const mode of ['missing','tampered','cycle','outside','incomplete']){const ancestor=context('ancestor-'+mode),source=context('lineage-source-'+mode),destination=context('lineage-destination-'+mode);link(source,ancestor,{complete:mode!=='incomplete'});if(mode==='missing')fs.renameSync(ancestor.dir,ancestor.dir+'-missing');if(mode==='tampered')S.atomic(path.join(ancestor.dir,'settings.json'),{changed:true});if(mode==='cycle')link(ancestor,source);if(mode==='outside'){const original=S.read(path.join(source.dir,'continuation.json'));original.source=outside;original.sourceId=S.hash([outside,original.hashes]);S.atomic(path.join(source.dir,'continuation.json'),original);}await assert.rejects(()=>snapshot.importExposures(destination.dir,source.dir,destination),/ancestor|cycle|inside|incomplete|provenance/i);assert.equal(fs.existsSync(path.join(destination.dir,snapshot.exposureName)),false);assert.equal(fs.existsSync(path.join(destination.dir,'exposure-chain-intent.json')),false);if(mode==='missing')fs.renameSync(ancestor.dir+'-missing',ancestor.dir);}
 });
 await check('actual child exit during ancestor exposure import resumes the same sealed registry once',async()=>{
  const snapshot=require('../tools/learning/snapshot.cjs'),source=context('chain-crash-source'),file=path.join(source.dir,'datasets/old.jsonl');S.atomic(file,JSON.stringify({familyId:'historic-family',positionKey:'historic-position',split:'train'})+'\n');S.atomic(file+'.manifest.json',{schemaVersion:1,rulesId:S.RULES_ID,featureVersion:S.FEATURE_VERSION,file:path.basename(file),sha256:S.fileHash(file)});
  const child="const S=require('./tools/learning/state.cjs'),J=require('./tools/learning/journal.cjs'),P=require('./tools/learning/snapshot.cjs'),path=require('node:path');const dir=process.argv[1],boundary=process.argv[3],context={dir,state:S.read(path.join(dir,'state.json')),settings:S.read(path.join(dir,'settings.json'))},append=J.appendRows,atomic=S.atomic;J.appendRows=(...args)=>{const n=append(...args);if(boundary==='exposure'&&args[1]===P.exposureName)process.exit(73);return n;};S.atomic=(target,value)=>{const n=atomic(target,value);if((boundary==='lineage'&&path.basename(target)===P.lineageName)||(boundary==='seal'&&path.basename(target)==='temporal-exposures-ready.json'))process.exit(73);return n;};P.importExposures(dir,process.argv[2],context).then(()=>process.exit(0)).catch(error=>{console.error(error);process.exit(1);});";
  for(const boundary of ['exposure','lineage','seal']){const destination=context('chain-crash-destination-'+boundary);snapshot.sealExposures(destination.dir);const result=cp.spawnSync(process.execPath,['-e',child,destination.dir,source.dir,boundary],{cwd:S.ROOT,encoding:'utf8'});assert.equal(result.status,73,result.stderr);assert.ok(fs.existsSync(path.join(destination.dir,'exposure-chain-intent.json')));await snapshot.ensureExposures(destination);await snapshot.ensureExposures(destination);const imported=rows(path.join(destination.dir,snapshot.exposureName));assert.equal(imported.length,2);assert.equal(new Set(imported.map(row=>row.id)).size,2);assert.ok(snapshot.verifyLineage(destination.dir));assert.equal(fs.existsSync(path.join(destination.dir,'exposure-chain-intent.json')),false);}
 });
 await check('JSONL appends are durable, indexed after restart and idempotent',()=>{const ctx=context('journal-tail'),first={sampleId:'one',familyId:'f1'},second={sampleId:'two',familyId:'f2'};assert.equal(J.appendRows(ctx.dir,'dataset.jsonl',[first,first],'sampleId'),1);assert.equal(J.appendRows(ctx.dir,'dataset.jsonl',[first],'sampleId'),0);assert.throws(()=>J.appendRows(ctx.dir,'dataset.jsonl',[{...first,changed:true}],'sampleId'),/Conflicting/);J.close(ctx.dir);S.append(path.join(ctx.dir,'dataset.jsonl'),second);assert.equal(J.syncFile(ctx.dir,'dataset.jsonl','sampleId').n,2);assert.equal(J.appendRows(ctx.dir,'dataset.jsonl',[second],'sampleId'),0);const complete=fs.readFileSync(path.join(ctx.dir,'dataset.jsonl'));fs.appendFileSync(path.join(ctx.dir,'dataset.jsonl'),'{{truncated');assert.equal(J.syncFile(ctx.dir,'dataset.jsonl','sampleId').n,2);assert.deepEqual(fs.readFileSync(path.join(ctx.dir,'dataset.jsonl')),complete);assert.equal(rows(path.join(ctx.dir,'recovery.jsonl')).at(-1).discardedTailBytes,11);});
 await check('corpus rejects conflicting complete lines and shortened files',()=>{const ctx=context('journal-corrupt');J.appendRows(ctx.dir,'dataset.jsonl',[{sampleId:'one',familyId:'f'}],'sampleId');fs.appendFileSync(path.join(ctx.dir,'dataset.jsonl'),'not JSON\n');const bytes=fs.readFileSync(path.join(ctx.dir,'dataset.jsonl'));assert.throws(()=>J.syncFile(ctx.dir,'dataset.jsonl','sampleId'));assert.deepEqual(fs.readFileSync(path.join(ctx.dir,'dataset.jsonl')),bytes);const other=context('journal-short');J.appendRows(other.dir,'dataset.jsonl',[{sampleId:'one',familyId:'f'}],'sampleId');fs.truncateSync(path.join(other.dir,'dataset.jsonl'),0);assert.throws(()=>J.syncFile(other.dir,'dataset.jsonl','sampleId'),/shortened/);});
 await check('game commit recovers once after crash between append and state snapshot',()=>{const ctx=context('journal-commit'),rec=record('played',coordinates),game=playedGame('game-0',rec),data=game.samples.map((pos,i)=>sample(game,pos,'row-'+i));ctx.state.activeGames[game.id]=copy(game);S.save(ctx);const before=S.save;try{S.save=()=>{throw Error('injected snapshot crash');};assert.throws(()=>J.commitGame(ctx,game,data),/injected/);}finally{S.save=before;}assert(fs.existsSync(path.join(ctx.dir,'generation-intent.json')));J.close(ctx.dir);const restored=reload(ctx);J.recoverGames(restored);assert(!fs.existsSync(path.join(ctx.dir,'generation-intent.json')));assert.equal(restored.state.counters.completedGames,1);assert.equal(restored.state.counters.generatedGames,1);assert.equal(restored.state.counters.samples,2);assert.deepEqual(restored.state.activeGames,{});assert.equal(rows(path.join(ctx.dir,'games.jsonl')).length,1);assert.equal(rows(path.join(ctx.dir,'dataset.jsonl')).length,2);J.recoverGames(restored);assert.equal(restored.state.counters.samples,2);assert.equal(rows(path.join(ctx.dir,'games.jsonl')).length,1);});
 await check('unplayed winner and incomplete terminal labels cannot be committed',()=>{const ctx=context('journal-invalid'),rec=record('cutoff',coordinates.slice(0,8)),game=playedGame('game-0',rec);assert.equal(game.completed,false);assert.throws(()=>J.commitGame(ctx,{...game,completed:true,winner:1},[]),/Unplayed/);fs.unlinkSync(path.join(ctx.dir,'generation-intent.json'));assert.throws(()=>J.commitGame(ctx,game,[{sampleId:'false-label'}]),/Incomplete/);assert.equal(rows(path.join(ctx.dir,'dataset.jsonl')).length,0);assert.equal(rows(path.join(ctx.dir,'games.jsonl')).length,0);});
 await check('partial move tail recovery preserves exact events, board, RNG and samples',()=>{const ctx=context('journal-moves'),rec=record('moves',coordinates),start=R.replay({...rec,events:rec.events.slice(0,4)}),game={...playedGame('game-0',rec),board:start.board,p:start.p,events:[],samples:[],completed:false,winner:null,reason:null,rng:111,elapsedMs:0};ctx.state.activeGames[game.id]=copy(game);S.save(ctx);for(const event of rec.events.slice(4,6)){game.samples.push({board:game.board.slice(),p:game.p,ply:game.opening.length+game.events.length});game.board[event.i]=game.p;game.p=3-game.p;game.events.push(event);game.rng+=99;game.elapsedMs+=20;S.saveProgress(ctx,game);}const partial=path.join(ctx.dir,'partials',S.hash(game.id).slice(0,24)+'.jsonl'),durable=fs.readFileSync(partial);fs.appendFileSync(partial,'{partial');const restored=reload(ctx);J.recoverGames(restored);assert.deepEqual(restored.state.activeGames[game.id].events,game.events);assert.deepEqual(restored.state.activeGames[game.id].board,game.board);assert.equal(restored.state.activeGames[game.id].rng,game.rng);assert.equal(restored.state.activeGames[game.id].elapsedMs,40);assert.equal(restored.state.activeGames[game.id].samples.length,2);assert.equal(restored.state.activeGames[game.id].modelVersion,game.modelVersion);assert.deepEqual(fs.readFileSync(partial),durable);J.recoverGames(restored);assert.equal(restored.state.activeGames[game.id].samples.length,2);assert.equal(restored.state.counters.samples,0);S.append(partial,{id:game.id,ply:1,event:{type:'move',p:1,i:R.index('O15')}});assert.throws(()=>J.recoverGames(restored),/Conflicting saved move/);});
 await check('source bounds, symlinks, live locks and rule/provenance mismatch are rejected',()=>{const source=sourceFixture('source-security');assert.throws(()=>C.checkedSource(outside));fs.writeFileSync(path.join(source.ctx.dir,'runner.lock'),JSON.stringify({pid:process.pid}));assert.throws(()=>C.checkedSource(source.ctx.dir),/Stop|active|running/i);fs.unlinkSync(path.join(source.ctx.dir,'runner.lock'));const saved=S.read(path.join(source.ctx.dir,'state.json'));S.atomic(path.join(source.ctx.dir,'state.json'),{...saved,rulesId:'foreign-rules'});assert.throws(()=>C.checkedSource(source.ctx.dir),/rule|version/i);S.atomic(path.join(source.ctx.dir,'state.json'),{...saved,identity:{}});assert.throws(()=>C.checkedSource(source.ctx.dir),/identity|provenance/i);S.atomic(path.join(source.ctx.dir,'state.json'),saved);fs.symlinkSync(outside,path.join(source.ctx.dir,'runner.lock'),'junction');assert.throws(()=>C.checkedSource(source.ctx.dir),/leaves|outside|directory/i);fs.unlinkSync(path.join(source.ctx.dir,'runner.lock'));fs.unlinkSync(path.join(source.ctx.dir,'dataset.jsonl'));fs.symlinkSync(outside,path.join(source.ctx.dir,'dataset.jsonl'),'junction');assert.throws(()=>C.checkedSource(source.ctx.dir),/leaves|outside|directory/i);});
 await check('continuation preserves original, namespaces rows and fixes family split before append',async()=>{const source=sourceFixture('source-main'),destination=context('continued'),before=hashes(source.ctx),result=await C.continueFrom(destination,source.ctx.dir);assert.equal(result.complete,true);assert.deepEqual(hashes(source.ctx),before);const games=rows(path.join(destination.dir,'games.jsonl')),data=rows(path.join(destination.dir,'dataset.jsonl')),records=S.read(path.join(destination.dir,'records.json'));assert.equal(destination.state.counters.completedGames,2);assert.equal(destination.state.counters.samples,3);assert.equal(data.length,3);assert(games.every(game=>game.id!==source.game.id&&game.id!==source.independent.id));assert(data.every(row=>!row.sampleId.startsWith('original-row-')));assert(records.some(rec=>rec.contentId===source.rec.contentId));const split=new Map();for(const row of [...records,...games,...data]){const prior=split.get(row.familyId);if(prior)assert.equal(row.split,prior,'Every member of a family must keep one final split');split.set(row.familyId,row.split);}assert(data.every(row=>row.split==='train'),'Prior train use cannot become independent held-out evidence');const generated=games.find(game=>game.provenance?.originalGameId===source.game.id);assert(generated);assert(data.some(row=>row.source.gameId===generated.id));const firstCounts=copy(destination.state.counters),firstHashes=hashes(destination);await C.continueFrom(destination,source.ctx.dir);assert.deepEqual(destination.state.counters,firstCounts);assert.deepEqual(hashes(destination),firstHashes);assert.deepEqual(hashes(source.ctx),before);S.append(path.join(source.ctx.dir,'dataset.jsonl'),{...sample(source.game,source.game.samples[0],'later-row'),weight:.5});await assert.rejects(C.continueFrom(destination,source.ctx.dir),/changed/i);});
 await check('continuation IDs stay bounded without weakening trainer validation or losing source identity',()=>{
  const sourceId='a'.repeat(64),otherSource='b'.repeat(64),prefix='origin-'+sourceId.slice(0,16)+':';
  assert.equal(C.continuationSampleId(sourceId,'x'.repeat(232)),prefix+'x'.repeat(232));
  for(const id of ['x'.repeat(233),'x'.repeat(256),'origin-0123456789abcdef:'.repeat(10)+'record:builtin-reader-29:4','한'.repeat(300),'😀'.repeat(233)]){
   const encoded=C.continuationSampleId(sourceId,id);assert.match(encoded,/^origin-sha256-[a-f0-9]{64}$/);assert.equal(encoded.length,78);assert.equal(encoded,C.continuationSampleId(sourceId,id));assert.notEqual(encoded,C.continuationSampleId(otherSource,id));assert.notEqual(encoded,C.continuationSampleId(sourceId,id+'different-tail'));assert.throws(()=>C.continuationSampleId(sourceId,id,0),/Legacy continuation.*bound/);
  }
  const overflow=C.continuationSampleId(sourceId,'x'.repeat(233));assert.notEqual(C.continuationSampleId(sourceId,overflow),overflow,'Short literal IDs cannot alias the disjoint overflow namespace');
  for(const id of ['😀'.repeat(200),'😀'.repeat(232),'é'.repeat(116)])assert.equal(C.continuationSampleId(sourceId,id),prefix+id,'Short Unicode IDs keep the exact legacy identity under Python code-point length');
  let id='origin-0123456789abcdef:'.repeat(10)+'record:builtin-reader-29:4';for(let i=0;i<64;i++){id=C.continuationSampleId(S.hash(['source-hop',i]),id);assert.ok(Array.from(id).length<=256);}
  for(const invalid of [null,undefined,0,{},[],false,''])assert.throws(()=>C.continuationSampleId(sourceId,invalid),/Invalid continuation sample identity/);
  for(const invalid of ['', 'a'.repeat(63),'G'.repeat(64),['a'.repeat(64)],null,64])assert.throws(()=>C.continuationSampleId(invalid,'valid'),/Invalid continuation sample identity/);
  assert.throws(()=>C.continuationSampleId(sourceId,'valid',2),/Invalid continuation sample identity/);
 });
 await check('actual continuation and immutable snapshot can be prepared by the unchanged Python trainer after recursive legacy overflow',async()=>{
  const P=require('../tools/learning/snapshot.cjs'),source=sourceFixture('long-identity-source'),originalRows=rows(path.join(source.ctx.dir,'dataset.jsonl'));
  originalRows.push({...originalRows[0]});const identities=['x'.repeat(232),'origin-0123456789abcdef:'.repeat(9)+'record:builtin-reader-29:4','origin-0123456789abcdef:'.repeat(10)+'record:builtin-reader-29:4','😀'.repeat(232)];assert.equal(identities[1].length,242);assert.equal(('origin-'+'a'.repeat(16)+':'+identities[1]).length,266);
  originalRows.forEach((row,i)=>row.sampleId=identities[i]);S.atomic(path.join(source.ctx.dir,'dataset.jsonl'),originalRows.map(row=>JSON.stringify(row)+'\n').join(''));source.ctx.state.counters.samples=4;S.save(source.ctx);
  const sourceHashes=hashes(source.ctx),first=context('long-identity-first');const firstManifest=await C.continueFrom(first,source.ctx.dir);assert.equal(firstManifest.sampleIdEncodingVersion,1);assert.equal(firstManifest.complete,true);
  const firstRows=rows(path.join(first.dir,'dataset.jsonl'));assert.equal(firstRows.length,4);assert.equal(new Set(firstRows.map(row=>row.sampleId)).size,4);assert.equal(firstRows[0].sampleId.length,256);assert.match(firstRows[1].sampleId,/^origin-sha256-[a-f0-9]{64}$/);assert.equal(firstRows[3].sampleId,'origin-'+firstManifest.sourceId.slice(0,16)+':'+identities[3]);assert.equal(Array.from(firstRows[3].sampleId).length,256);assert.ok(firstRows.every(row=>Array.from(row.sampleId).length<=256));
  firstRows.forEach((row,i)=>{assert.equal(row.provenance.originalSampleId,identities[i]);assert.equal(row.provenance.sourceId,firstManifest.sourceId);assert.deepEqual(row.features,originalRows[i].features);assert.deepEqual(row.position,originalRows[i].position);assert.equal(row.positionKey,originalRows[i].positionKey);assert.equal(row.target,originalRows[i].target);assert.equal(row.weight,originalRows[i].weight);});
  const firstBefore=hashes(first);await C.continueFrom(first,source.ctx.dir);assert.deepEqual(hashes(first),firstBefore);assert.deepEqual(hashes(source.ctx),sourceHashes);
  const python=process.env.OMOK_TEST_PYTHON||(fs.existsSync(S.defaults().python)?S.defaults().python:'python'),program='import importlib.util,json,sys;from pathlib import Path;s=importlib.util.spec_from_file_location("omok_trainer",sys.argv[1]);t=importlib.util.module_from_spec(s);s.loader.exec_module(t);m=t.prepare_data(Path(sys.argv[2]),Path(sys.argv[3]),t.StopController(20,None));print(json.dumps({"counts":m["counts"],"duplicatesIgnored":m["duplicatesIgnored"]}))';
  const prepare=async(ctx,name)=>{const data=path.join(ctx.dir,'datasets',name+'.jsonl'),snapshot=await P.snapshotData(ctx,data),result=JSON.parse(cp.execFileSync(python,['-c',program,path.join(S.ROOT,'tools/learning/train.py'),data,path.join(outside,'python-cache-'+ctx.state.runId)],{encoding:'utf8',timeout:30000,windowsHide:true}));assert.deepEqual(result.counts,{train:snapshot.counts.train,validation:snapshot.counts.validation,test:snapshot.counts.test});assert.equal(result.duplicatesIgnored,0);assert.equal(fs.existsSync(path.join(ctx.dir,'candidate.json')),false);assert.equal(fs.existsSync(path.join(ctx.dir,'champion.json')),false);return S.fileHash(data);};
  const firstSnapshotHash=await prepare(first,'first'),firstSealed=hashes(first),second=context('long-identity-second');const secondManifest=await C.continueFrom(second,first.dir);assert.equal(secondManifest.sampleIdEncodingVersion,1);const secondRows=rows(path.join(second.dir,'dataset.jsonl'));assert.ok(secondRows.every(row=>Array.from(row.sampleId).length<=256));secondRows.forEach((row,i)=>{assert.equal(row.provenance.originalSampleId,firstRows[i].sampleId);assert.equal(row.provenance.sourceId,secondManifest.sourceId);assert.deepEqual(row.features,firstRows[i].features);assert.deepEqual(row.position,firstRows[i].position);assert.equal(row.target,firstRows[i].target);assert.equal(row.weight,firstRows[i].weight);});await prepare(second,'second');assert.equal(S.fileHash(path.join(first.dir,'datasets/first.jsonl')),firstSnapshotHash);assert.deepEqual(hashes(first),firstSealed);assert.deepEqual(hashes(source.ctx),sourceHashes);
  assert.throws(()=>J.appendRows(second.dir,'dataset.jsonl',[{...secondRows[0],weight:.5}],'sampleId'),/Conflicting/);const before=hashes(second);await C.continueFrom(second,first.dir);assert.deepEqual(hashes(second),before);
  let previous=second,previousRows=secondRows;for(let hop=3;hop<=20;hop++){const parentHashes=hashes(previous),next=context('long-identity-hop-'+hop),manifest=await C.continueFrom(next,previous.dir),nextRows=rows(path.join(next.dir,'dataset.jsonl'));assert.equal(manifest.complete,true);assert.equal(manifest.sampleIdEncodingVersion,1);assert.equal(nextRows.length,4);assert.equal(new Set(nextRows.map(row=>row.sampleId)).size,4);nextRows.forEach((row,i)=>{assert.ok(Array.from(row.sampleId).length<=256);assert.equal(row.provenance.originalSampleId,previousRows[i].sampleId);assert.deepEqual(row.features,previousRows[i].features);assert.deepEqual(row.position,previousRows[i].position);assert.equal(row.target,previousRows[i].target);assert.equal(row.weight,previousRows[i].weight);});assert.deepEqual(hashes(previous),parentHashes);previous=next;previousRows=nextRows;}await prepare(previous,'twentieth');assert.deepEqual(hashes(source.ctx),sourceHashes);
 });
 await check('versionless interrupted continuation never silently changes already durable sample IDs',async()=>{
  const source=sourceFixture('legacy-partial-source'),destination=context('legacy-partial-destination'),append=J.appendRows;try{J.appendRows=(...args)=>{const count=append(...args);if(args[1]==='games.jsonl')throw Error('legacy-encoding-fixture-stop');return count;};await assert.rejects(C.continueFrom(destination,source.ctx.dir),/legacy-encoding-fixture-stop/);}finally{J.appendRows=append;}
  const marker=S.read(path.join(destination.dir,'continuation.json'));delete marker.sampleIdEncodingVersion;S.atomic(path.join(destination.dir,'continuation.json'),marker);const result=await C.continueFrom(reload(destination),source.ctx.dir);assert.equal(result.complete,true);assert.equal(result.sampleIdEncodingVersion,undefined);const prefix='origin-'+result.sourceId.slice(0,16)+':';assert.ok(rows(path.join(destination.dir,'dataset.jsonl')).every(row=>row.sampleId===prefix+row.provenance.originalSampleId));
  const longSource=sourceFixture('legacy-partial-overflow-source'),longDestination=context('legacy-partial-overflow-destination'),longRows=rows(path.join(longSource.ctx.dir,'dataset.jsonl'));longRows[0].sampleId='x'.repeat(233);S.atomic(path.join(longSource.ctx.dir,'dataset.jsonl'),longRows.map(row=>JSON.stringify(row)+'\n').join(''));const sourceHashes=hashes(longSource.ctx);
  try{J.appendRows=(...args)=>{const count=append(...args);if(args[1]==='games.jsonl')throw Error('legacy-overflow-fixture-stop');return count;};await assert.rejects(C.continueFrom(longDestination,longSource.ctx.dir),/legacy-overflow-fixture-stop/);}finally{J.appendRows=append;}
  const oldMarker=S.read(path.join(longDestination.dir,'continuation.json'));delete oldMarker.sampleIdEncodingVersion;S.atomic(path.join(longDestination.dir,'continuation.json'),oldMarker);const gameHash=S.fileHash(path.join(longDestination.dir,'games.jsonl'));await assert.rejects(C.continueFrom(reload(longDestination),longSource.ctx.dir),/Legacy continuation.*trainer bound/);assert.equal(rows(path.join(longDestination.dir,'dataset.jsonl')).length,0);assert.equal(S.fileHash(path.join(longDestination.dir,'games.jsonl')),gameHash);assert.deepEqual(hashes(longSource.ctx),sourceHashes);
 });
 await check('unplayed source terminal claims are rejected during continuation',async()=>{const source=sourceFixture('source-bad-label'),destination=context('bad-label-destination'),pos=source.cutoff.samples[0],row=sample({...source.cutoff,winner:1},pos,'unplayed-winner');S.append(path.join(source.ctx.dir,'dataset.jsonl'),row);await assert.rejects(C.continueFrom(destination,source.ctx.dir),/terminal|incomplete|outcome|played|source game/i);});
 await check('interrupted continuation retries the same durable rows without duplication',async()=>{const source=sourceFixture('source-retry'),destination=context('retry-destination'),before=hashes(source.ctx),append=J.appendRows;try{J.appendRows=(...args)=>{const n=append(...args);if(args[1]==='games.jsonl')throw Error('injected copy interruption');return n;};await assert.rejects(C.continueFrom(destination,source.ctx.dir),/injected copy interruption/);}finally{J.appendRows=append;}assert.equal(S.read(path.join(destination.dir,'continuation.json')).complete,false);assert.equal(rows(path.join(destination.dir,'games.jsonl')).length,3);J.close(destination.dir);const resumed=reload(destination);const result=await C.continueFrom(resumed,source.ctx.dir);assert.equal(result.complete,true);assert.equal(rows(path.join(destination.dir,'games.jsonl')).length,3);assert.equal(rows(path.join(destination.dir,'dataset.jsonl')).length,3);assert.equal(resumed.state.counters.completedGames,2);assert.equal(resumed.state.counters.samples,3);assert.deepEqual(hashes(source.ctx),before);});
 await check('batched index failure rolls back only the open transaction and resumes with unchanged labels and splits',async()=>{
  const source=sourceFixture('source-index-batch'),destination=context('index-batch-destination');
  for(let i=0;i<128;i++){const game={...source.game,id:'extra-game-'+i,index:i+3};S.append(path.join(source.ctx.dir,'games.jsonl'),{...game,samples:undefined,model:undefined});S.append(path.join(source.ctx.dir,'dataset.jsonl'),sample(game,game.samples[0],'extra-row-'+i,'train'));}
  const before=hashes(source.ctx),verify=J.verify;let visited=0;
  try{J.verify=game=>{if(++visited===130)throw Error('injected index-batch crash');return verify(game);};await assert.rejects(C.continueFrom(destination,source.ctx.dir),/injected index-batch crash/);}finally{J.verify=verify;}
  const {DatabaseSync}=require('node:sqlite'),index=new DatabaseSync(path.join(destination.dir,'continuation.sqlite'),{readOnly:true});
  try{assert.equal(index.prepare('SELECT COUNT(*) n FROM games').get().n,128);assert.equal(index.prepare('SELECT COUNT(*) n FROM games WHERE id=?').get('extra-game-125').n,0);}finally{index.close();}
  assert.equal(rows(path.join(destination.dir,'games.jsonl')).length,0,'Raw games wait until every source label/family is validated');assert.equal(rows(path.join(destination.dir,'dataset.jsonl')).length,0);assert.equal(S.read(path.join(destination.dir,'continuation.json')).complete,false);
  const resumed=reload(destination);assert.equal((await C.continueFrom(resumed,source.ctx.dir)).complete,true);assert.equal(resumed.state.counters.generatedGames,131);assert.equal(resumed.state.counters.samples,131);assert.deepEqual(hashes(source.ctx),before);
  const original=new Map(rows(path.join(source.ctx.dir,'dataset.jsonl')).map(row=>[row.sampleId,row]));for(const row of rows(path.join(destination.dir,'dataset.jsonl'))){const prior=original.get(row.provenance.originalSampleId);assert.deepEqual(row.features,prior.features);assert.deepEqual(row.position,prior.position);assert.equal(row.target,prior.target);assert.equal(row.weight,prior.weight);assert.equal(row.split,'train');}
  const stopped=context('index-batch-stop');visited=0;
  try{J.verify=game=>{const checked=verify(game);if(++visited===130)fs.writeFileSync(path.join(stopped.dir,'stop.flag'),'injected user stop between index batches');return checked;};assert.equal((await C.continueFrom(stopped,source.ctx.dir)).complete,false);}finally{J.verify=verify;}
  const stoppedIndex=new DatabaseSync(path.join(stopped.dir,'continuation.sqlite'),{readOnly:true});try{assert.equal(stoppedIndex.prepare('SELECT COUNT(*) n FROM games').get().n,130);}finally{stoppedIndex.close();}
  assert.equal(rows(path.join(stopped.dir,'games.jsonl')).length,0);assert.equal(rows(path.join(stopped.dir,'dataset.jsonl')).length,0);fs.unlinkSync(path.join(stopped.dir,'stop.flag'));assert.equal((await C.continueFrom(reload(stopped),source.ctx.dir)).complete,true);assert.equal(rows(path.join(stopped.dir,'games.jsonl')).length,131);assert.deepEqual(hashes(source.ctx),before);
 });
 await check('stop flag during source copy preserves an incomplete manifest for explicit resume',async()=>{const source=sourceFixture('source-stop'),destination=context('stopped-destination');fs.writeFileSync(path.join(destination.dir,'stop.flag'),'user stop');const stopped=await C.continueFrom(destination,source.ctx.dir);assert.equal(stopped.complete,false);assert.equal(rows(path.join(destination.dir,'games.jsonl')).length,0);fs.unlinkSync(path.join(destination.dir,'stop.flag'));const result=await C.continueFrom(reload(destination),source.ctx.dir);assert.equal(result.complete,true);assert.equal(rows(path.join(destination.dir,'dataset.jsonl')).length,3);});
 await check('an unaccepted prior candidate can warm-start training but cannot become champion',async()=>{const source=sourceFixture('source-warm'),destination=context('warm-destination'),candidate={schemaVersion:1,kind:'forest-value-mlp',rulesId:S.RULES_ID,featureVersion:S.FEATURE_VERSION,inputSize:32,hiddenSize:1,activation:'relu',outputActivation:'tanh',normalization:{mean:Array(32).fill(0),scale:Array(32).fill(1)},layers:[{weights:[Array(32).fill(0)],bias:[0]},{weights:[[0]],bias:[0]}],modelId:'unaccepted-fixture',scale:600,training:{updates:10},adoption:{accepted:false}};N.validate(candidate);S.atomic(path.join(source.ctx.dir,'candidate.json'),candidate);const before=hashes(source.ctx);await C.continueFrom(destination,source.ctx.dir);assert.equal(S.read(path.join(destination.dir,'warm-start.json')).modelId,candidate.modelId);assert(!fs.existsSync(path.join(destination.dir,'champion.json')));assert(!fs.existsSync(path.join(destination.dir,'candidate.json')));assert.deepEqual(hashes(source.ctx),before);});
 await check('claimed source ply must match the actual played position',async()=>{const source=sourceFixture('source-wrong-position'),destination=context('position-destination'),data=rows(path.join(source.ctx.dir,'dataset.jsonl'));data[0].position.board[R.index('O15')]=1;data[0].positionKey=R.positionKey(data[0].position.board,data[0].position.p,data[0].position.firstPlayer);data[0].features=Array.from(N.extractFeatures(data[0].position.board,data[0].position.p,data[0].position.firstPlayer));S.atomic(path.join(source.ctx.dir,'dataset.jsonl'),data.map(row=>JSON.stringify(row)+'\n').join(''));await assert.rejects(C.continueFrom(destination,source.ctx.dir),/position|played|ply|source/i);});
 await check('stored features must match the versioned feature extractor',async()=>{const source=sourceFixture('source-wrong-features'),destination=context('features-destination'),data=rows(path.join(source.ctx.dir,'dataset.jsonl'));data[0].features[0]+=.5;S.atomic(path.join(source.ctx.dir,'dataset.jsonl'),data.map(row=>JSON.stringify(row)+'\n').join(''));await assert.rejects(C.continueFrom(destination,source.ctx.dir),/feature|position|extract/i);});
 await check('continuation preserves fresh-data baseline, seed cursor, trial budget and update history',async()=>{const source=sourceFixture('source-history'),destination=context('history-destination');source.ctx.state.generationIndex=20;source.ctx.state.trial=4;source.ctx.state.counters.trainingUpdates=10;source.ctx.state.importedSampleGames=['same-record-id'];source.ctx.state.analysisDone=['same-record-id:4'];S.save(source.ctx);const before=hashes(source.ctx);await C.continueFrom(destination,source.ctx.dir);assert.equal(destination.state.generationIndex,20);assert.equal(destination.state.trial,4);assert.equal(destination.state.counters.trainingUpdates,10);assert.equal(destination.state.lastTrainingSampleCount,3);assert.equal(destination.state.counters.samples-destination.state.lastTrainingSampleCount,0);assert.deepEqual(destination.state.importedSampleGames,['same-record-id']);assert.deepEqual(destination.state.analysisDone,['same-record-id:4']);assert.deepEqual(hashes(source.ctx),before);const legacy=sourceFixture('source-cursor-fallback'),fresh=context('cursor-fallback-destination');await C.continueFrom(fresh,legacy.ctx.dir);assert.equal(fresh.state.generationIndex,3,'Fresh seeds must start beyond every imported game index even if the old cursor was stale');});
 console.log(JSON.stringify({passed:true,checks:passed.length,scope:'Independent legal-game persistence, source boundaries, family isolation and crash recovery; no training/adoption',tests:passed}));
})().catch(error=>{console.error(error);process.exitCode=1;}).finally(()=>{for(const ctx of contexts)J.close(ctx.dir);const absolute=path.resolve(temporary);if(path.dirname(absolute)!==path.join(S.ROOT,'work')||!path.basename(absolute).startsWith('learning-corpus-test-'))throw Error('Unsafe project fixture cleanup');fs.rmSync(absolute,{recursive:true,force:true});const external=path.resolve(outside);if(path.dirname(external)!==path.resolve(os.tmpdir())||!path.basename(external).startsWith('omok-corpus-outside-'))throw Error('Unsafe external fixture cleanup');fs.rmSync(external,{recursive:true,force:true});});
