'use strict';
const assert=require('node:assert/strict'),S=require('../tools/learning/state.cjs'),archive=require('../tools/learning/archive.cjs');
archive.assertDeliverySource({identity:S.sourceIdentity()});
assert.throws(()=>archive.assertDeliverySource({identity:{sourceHash:'0'.repeat(64)}}),/production engine changed/);
const path=require('node:path'),fs=require('node:fs'),baseline=path.join(S.ROOT,'work/continuous-runtime-baseline.json');
if(fs.existsSync(baseline)){const original=S.read(baseline);if(original.files['src/node-engine.cjs']&&original.files['build.cjs']&&original.files['src/neural-app.js'])assert.deepEqual(archive.frozenRuntime().load('tools/learning/state.cjs').sourceIdentity(),original.identity);else assert.throws(()=>archive.frozenRuntime(),/Archived repository dependency missing/);}
fs.mkdirSync(path.join(S.ROOT,'work'),{recursive:true});
const dir=fs.mkdtempSync(path.join(S.ROOT,'work/archive-contract-')),identity=S.sourceIdentity(),files=Object.fromEntries([...identity.sourceManifest,...identity.harnessManifest].map(row=>[row.path,fs.readFileSync(path.join(S.ROOT,row.path),'utf8')])),snapshot={schemaVersion:2,identity,files,externalDependencies:[]};
const write=(name,value)=>{const file=path.join(dir,name+'.json');S.atomic(file,value);return file;};
for(const dependency of ['src/node-engine.cjs','build.cjs','src/neural-app.js'])assert(identity.sourceManifest.some(row=>row.path===dependency));
const frozen=archive.frozenRuntime(write('complete',snapshot));assert.deepEqual(frozen.load('tools/learning/state.cjs').sourceIdentity(),identity);assert.equal(typeof frozen.load('src/node-engine.cjs'),'function');
const captured=archive.captureRuntime(identity);assert.deepEqual(archive.frozenRuntime(captured.file).snapshot.identity,identity);assert.equal(archive.captureRuntime(identity).file,captured.file);
for(const dependency of ['src/node-engine.cjs','build.cjs','src/neural-app.js']){const broken=structuredClone(snapshot);delete broken.files[dependency];assert.throws(()=>archive.frozenRuntime(write('missing-'+path.basename(dependency),broken)),/Archived repository dependency missing|manifest mismatch/);}
const changed=structuredClone(snapshot);changed.files['build.cjs']+='\n// unverified change';assert.throws(()=>archive.frozenRuntime(write('changed-build',changed)),/manifest mismatch/);
const wrongNative=structuredClone(snapshot);wrongNative.identity.runtimeHash='0'.repeat(64);assert.throws(()=>archive.frozenRuntime(write('native-runtime',wrongNative)),/native runtime mismatch/);assert.throws(()=>archive.assertDeliverySource(wrongNative),/production engine changed/);assert.notEqual(archive.archiveId(wrongNative.identity),archive.archiveId(identity));
const older=structuredClone(snapshot);older.files['build.cjs']+='\n// older captured build';older.identity.sourceManifest.find(row=>row.path==='build.cjs').sha256=S.hash(older.files['build.cjs']);older.identity.sourceHash=S.hash(older.identity.sourceManifest);const olderId=archive.archiveId(older.identity);S.atomic(path.join(S.ROOT,'work/runtime-archives',olderId+'.json'),older);S.atomic(path.join(dir,'state.json'),{identity:older.identity});assert.deepEqual(archive.selectResumeRunner(dir).argsPrefix,['--archived-run','--runtime='+olderId]);assert.deepEqual(archive.frozenRuntime(path.join(S.ROOT,'work/runtime-archives',olderId+'.json')).load('tools/learning/state.cjs').sourceIdentity(),older.identity);assert.throws(()=>archive.assertDeliverySource(older),/production engine changed/);
for(const [name,source,pattern] of [
 ['relative',"module.exports=require('./unpreserved-module.cjs');",/Archived repository dependency missing/],
 ['absolute',"module.exports=require(require('node:path').join(__dirname,'unpreserved-module.cjs'));",/Archived repository dependency missing/],
 ['worker',"module.exports=new (require('node:worker_threads').Worker)(require('node:path').join(__dirname,'unpreserved-worker.cjs'));",/Archived repository dependency missing/],
 ['external',"module.exports=require('unapproved-external-package');",/not allowlisted/]
]){const broken=structuredClone(snapshot),entry='test/reader/game29.cjs';broken.files[entry]=source;broken.identity.sourceManifest.find(row=>row.path===entry).sha256=S.hash(source);broken.identity.sourceHash=S.hash(broken.identity.sourceManifest);const runtime=archive.frozenRuntime(write(name,broken));assert.throws(()=>runtime.load(entry),pattern);}
const extra=structuredClone(snapshot);extra.files['test/unmanifested.cjs']='module.exports=true;';assert.throws(()=>archive.frozenRuntime(write('unmanifested',extra)).load('test/unmanifested.cjs'),/canonical manifest/);
console.log(JSON.stringify({passed:20,artifacts:dir,scope:'Canonical captured/archive-selected identity and native runtime binding, dependency byte hashes, omitted loaders and workers, absolute and relative module refusal, explicit external dependency allowlist, and changed production engine blocks deployment'}));
