'use strict';
// Independent persistence checks use legal played games, real family grouping,
// and injected crashes. Fixtures never train or adopt a production model.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const S=require('../tools/learning/state.cjs'),R=require('../tools/learning/replay.cjs'),J=require('../tools/learning/journal.cjs'),C=require('../tools/learning/corpus.cjs'),N=require('../src/neural-evaluator.js');
const temporary=fs.mkdtempSync(path.join(S.ROOT,'work','learning-corpus-test-')),outside=fs.mkdtempSync(path.join(os.tmpdir(),'omok-corpus-outside-')),contexts=[],passed=[];
const copy=value=>JSON.parse(JSON.stringify(value));
function context(name){const dir=path.join(temporary,name);fs.mkdirSync(dir);const state={schemaVersion:1,runId:name,rulesId:S.RULES_ID,featureVersion:S.FEATURE_VERSION,identity:S.sourceIdentity(),status:'stopped',phase:'generate',cycle:1,counters:{samples:0,generatedGames:0,completedGames:0,analyzedPositions:0},activeGames:{},generationIndex:0,history:[],adoptions:[],errors:[]},ctx={dir,state,settings:S.defaults()};S.atomic(path.join(dir,'settings.json'),ctx.settings);S.atomic(path.join(dir,'records.json'),[]);S.save(ctx);contexts.push(ctx);return ctx;}
function reload(ctx){return {dir:ctx.dir,state:S.read(path.join(ctx.dir,'state.json')),settings:S.read(path.join(ctx.dir,'settings.json'))};}
function rows(file){return fs.existsSync(file)?fs.readFileSync(file,'utf8').trim().split('\n').filter(Boolean).map(line=>JSON.parse(line)):[];}
function record(id,coords,split='train'){return R.normalizeRecords({id,first:1,events:coords,split,source:'persistence fixture'})[0];}
const coordinates=['H8','A1','I8','A2','J8','A3','K8','A4','L8'],otherCoordinates=['F6','B1','G6','B2','H6','B3','I6','B4','J6'];
function playedGame(id,rec,split='train',branch=null){const played=R.replay(rec);return {id,index:Number(id.replace(/\D/g,''))||0,seed:123,rng:345,firstPlayer:rec.first,opening:rec.events.slice(0,4),events:rec.events.slice(4),board:played.board,p:played.p,familyId:'fixture-'+id,split,branch:branch||{sourceGame:null,prefix:4},model:null,modelVersion:'untrained-current',lessons:[],lessonHash:S.hash([]),samples:played.positions.slice(4,6).map(pos=>({board:pos.board,p:pos.p,ply:pos.ply})),completed:played.completed,winner:played.draw?0:played.winner,elapsedMs:100,reason:played.completed?'played-exact-five':'ply-limit'};}
function sample(game,pos,id,split=game.split){return {schemaVersion:1,sampleId:id,rulesId:S.RULES_ID,featureVersion:S.FEATURE_VERSION,familyId:game.familyId,split,positionKey:R.positionKey(pos.board,pos.p,game.firstPlayer),features:Array.from(N.extractFeatures(pos.board,pos.p,game.firstPlayer)),target:game.winner===0?0:game.winner===pos.p?1:-1,weight:1,labelType:'terminal',position:{board:pos.board,p:pos.p,firstPlayer:game.firstPlayer},source:{gameId:game.id,ply:pos.ply,kind:'actual-played-terminal',modelVersion:game.modelVersion}};}
function sourceFixture(name){const ctx=context(name),rec=record('same-record-id',coordinates),other=record('other-record-id',otherCoordinates),game=playedGame('game-0',rec,'validation',{sourceGame:rec.id,prefix:4}),independent=playedGame('game-1',other,'validation'),cutoff=playedGame('game-2',{...other,events:other.events.slice(0,8)},'test');ctx.state.status='complete';ctx.state.counters={samples:3,generatedGames:3,completedGames:2};S.atomic(path.join(ctx.dir,'records.json'),[rec]);S.atomic(path.join(ctx.dir,'lessons.json'),{schemaVersion:1,rulesId:S.RULES_ID,lessons:[]});S.append(path.join(ctx.dir,'games.jsonl'),{...game,samples:undefined,model:undefined});S.append(path.join(ctx.dir,'games.jsonl'),{...independent,samples:undefined,model:undefined});S.append(path.join(ctx.dir,'games.jsonl'),{...cutoff,samples:undefined,model:undefined});S.append(path.join(ctx.dir,'dataset.jsonl'),sample(game,game.samples[0],'original-row-0','validation'));S.append(path.join(ctx.dir,'dataset.jsonl'),sample(game,game.samples[1],'original-row-1','train'));S.append(path.join(ctx.dir,'dataset.jsonl'),sample(independent,independent.samples[0],'original-row-2','train'));S.save(ctx);return {ctx,rec,game,independent,cutoff};}
function hashes(ctx){return Object.fromEntries(fs.readdirSync(ctx.dir).filter(name=>fs.statSync(path.join(ctx.dir,name)).isFile()).map(name=>[name,S.fileHash(path.join(ctx.dir,name))]));}
async function check(name,fn){await fn();passed.push(name);console.log('PASS '+name);}
(async()=>{
 await check('JSONL appends are durable, indexed after restart and idempotent',()=>{const ctx=context('journal-tail'),first={sampleId:'one',familyId:'f1'},second={sampleId:'two',familyId:'f2'};assert.equal(J.appendRows(ctx.dir,'dataset.jsonl',[first,first],'sampleId'),1);assert.equal(J.appendRows(ctx.dir,'dataset.jsonl',[first],'sampleId'),0);assert.throws(()=>J.appendRows(ctx.dir,'dataset.jsonl',[{...first,changed:true}],'sampleId'),/Conflicting/);J.close(ctx.dir);S.append(path.join(ctx.dir,'dataset.jsonl'),second);assert.equal(J.syncFile(ctx.dir,'dataset.jsonl','sampleId').n,2);assert.equal(J.appendRows(ctx.dir,'dataset.jsonl',[second],'sampleId'),0);const complete=fs.readFileSync(path.join(ctx.dir,'dataset.jsonl'));fs.appendFileSync(path.join(ctx.dir,'dataset.jsonl'),'{{truncated');assert.equal(J.syncFile(ctx.dir,'dataset.jsonl','sampleId').n,2);assert.deepEqual(fs.readFileSync(path.join(ctx.dir,'dataset.jsonl')),complete);assert.equal(rows(path.join(ctx.dir,'recovery.jsonl')).at(-1).discardedTailBytes,11);});
 await check('corpus rejects conflicting complete lines and shortened files',()=>{const ctx=context('journal-corrupt');J.appendRows(ctx.dir,'dataset.jsonl',[{sampleId:'one',familyId:'f'}],'sampleId');fs.appendFileSync(path.join(ctx.dir,'dataset.jsonl'),'not JSON\n');const bytes=fs.readFileSync(path.join(ctx.dir,'dataset.jsonl'));assert.throws(()=>J.syncFile(ctx.dir,'dataset.jsonl','sampleId'));assert.deepEqual(fs.readFileSync(path.join(ctx.dir,'dataset.jsonl')),bytes);const other=context('journal-short');J.appendRows(other.dir,'dataset.jsonl',[{sampleId:'one',familyId:'f'}],'sampleId');fs.truncateSync(path.join(other.dir,'dataset.jsonl'),0);assert.throws(()=>J.syncFile(other.dir,'dataset.jsonl','sampleId'),/shortened/);});
 await check('game commit recovers once after crash between append and state snapshot',()=>{const ctx=context('journal-commit'),rec=record('played',coordinates),game=playedGame('game-0',rec),data=game.samples.map((pos,i)=>sample(game,pos,'row-'+i));ctx.state.activeGames[game.id]=copy(game);S.save(ctx);const before=S.save;try{S.save=()=>{throw Error('injected snapshot crash');};assert.throws(()=>J.commitGame(ctx,game,data),/injected/);}finally{S.save=before;}assert(fs.existsSync(path.join(ctx.dir,'generation-intent.json')));J.close(ctx.dir);const restored=reload(ctx);J.recoverGames(restored);assert(!fs.existsSync(path.join(ctx.dir,'generation-intent.json')));assert.equal(restored.state.counters.completedGames,1);assert.equal(restored.state.counters.generatedGames,1);assert.equal(restored.state.counters.samples,2);assert.deepEqual(restored.state.activeGames,{});assert.equal(rows(path.join(ctx.dir,'games.jsonl')).length,1);assert.equal(rows(path.join(ctx.dir,'dataset.jsonl')).length,2);J.recoverGames(restored);assert.equal(restored.state.counters.samples,2);assert.equal(rows(path.join(ctx.dir,'games.jsonl')).length,1);});
 await check('unplayed winner and incomplete terminal labels cannot be committed',()=>{const ctx=context('journal-invalid'),rec=record('cutoff',coordinates.slice(0,8)),game=playedGame('game-0',rec);assert.equal(game.completed,false);assert.throws(()=>J.commitGame(ctx,{...game,completed:true,winner:1},[]),/Unplayed/);fs.unlinkSync(path.join(ctx.dir,'generation-intent.json'));assert.throws(()=>J.commitGame(ctx,game,[{sampleId:'false-label'}]),/Incomplete/);assert.equal(rows(path.join(ctx.dir,'dataset.jsonl')).length,0);assert.equal(rows(path.join(ctx.dir,'games.jsonl')).length,0);});
 await check('partial move tail recovery preserves exact events, board, RNG and samples',()=>{const ctx=context('journal-moves'),rec=record('moves',coordinates),start=R.replay({...rec,events:rec.events.slice(0,4)}),game={...playedGame('game-0',rec),board:start.board,p:start.p,events:[],samples:[],completed:false,winner:null,reason:null,rng:111,elapsedMs:0};ctx.state.activeGames[game.id]=copy(game);S.save(ctx);for(const event of rec.events.slice(4,6)){game.samples.push({board:game.board.slice(),p:game.p,ply:game.opening.length+game.events.length});game.board[event.i]=game.p;game.p=3-game.p;game.events.push(event);game.rng+=99;game.elapsedMs+=20;S.saveProgress(ctx,game);}const partial=path.join(ctx.dir,'partials',S.hash(game.id).slice(0,24)+'.jsonl'),durable=fs.readFileSync(partial);fs.appendFileSync(partial,'{partial');const restored=reload(ctx);J.recoverGames(restored);assert.deepEqual(restored.state.activeGames[game.id].events,game.events);assert.deepEqual(restored.state.activeGames[game.id].board,game.board);assert.equal(restored.state.activeGames[game.id].rng,game.rng);assert.equal(restored.state.activeGames[game.id].elapsedMs,40);assert.equal(restored.state.activeGames[game.id].samples.length,2);assert.equal(restored.state.activeGames[game.id].modelVersion,game.modelVersion);assert.deepEqual(fs.readFileSync(partial),durable);J.recoverGames(restored);assert.equal(restored.state.activeGames[game.id].samples.length,2);assert.equal(restored.state.counters.samples,0);S.append(partial,{id:game.id,ply:1,event:{type:'move',p:1,i:R.index('O15')}});assert.throws(()=>J.recoverGames(restored),/Conflicting saved move/);});
 await check('source bounds, symlinks, live locks and rule/provenance mismatch are rejected',()=>{const source=sourceFixture('source-security');assert.throws(()=>C.checkedSource(outside));fs.writeFileSync(path.join(source.ctx.dir,'runner.lock'),JSON.stringify({pid:process.pid}));assert.throws(()=>C.checkedSource(source.ctx.dir),/Stop|active|running/i);fs.unlinkSync(path.join(source.ctx.dir,'runner.lock'));const saved=S.read(path.join(source.ctx.dir,'state.json'));S.atomic(path.join(source.ctx.dir,'state.json'),{...saved,rulesId:'foreign-rules'});assert.throws(()=>C.checkedSource(source.ctx.dir),/rule|version/i);S.atomic(path.join(source.ctx.dir,'state.json'),{...saved,identity:{}});assert.throws(()=>C.checkedSource(source.ctx.dir),/identity|provenance/i);S.atomic(path.join(source.ctx.dir,'state.json'),saved);fs.symlinkSync(outside,path.join(source.ctx.dir,'runner.lock'),'junction');assert.throws(()=>C.checkedSource(source.ctx.dir),/leaves|outside|directory/i);fs.unlinkSync(path.join(source.ctx.dir,'runner.lock'));fs.unlinkSync(path.join(source.ctx.dir,'dataset.jsonl'));fs.symlinkSync(outside,path.join(source.ctx.dir,'dataset.jsonl'),'junction');assert.throws(()=>C.checkedSource(source.ctx.dir),/leaves|outside|directory/i);});
 await check('continuation preserves original, namespaces rows and fixes family split before append',async()=>{const source=sourceFixture('source-main'),destination=context('continued'),before=hashes(source.ctx),result=await C.continueFrom(destination,source.ctx.dir);assert.equal(result.complete,true);assert.deepEqual(hashes(source.ctx),before);const games=rows(path.join(destination.dir,'games.jsonl')),data=rows(path.join(destination.dir,'dataset.jsonl')),records=S.read(path.join(destination.dir,'records.json'));assert.equal(destination.state.counters.completedGames,2);assert.equal(destination.state.counters.samples,3);assert.equal(data.length,3);assert(games.every(game=>game.id!==source.game.id&&game.id!==source.independent.id));assert(data.every(row=>!row.sampleId.startsWith('original-row-')));assert(records.some(rec=>rec.contentId===source.rec.contentId));const split=new Map();for(const row of [...records,...games,...data]){const prior=split.get(row.familyId);if(prior)assert.equal(row.split,prior,'Every member of a family must keep one final split');split.set(row.familyId,row.split);}assert(data.every(row=>row.split==='train'),'Prior train use cannot become independent held-out evidence');const generated=games.find(game=>game.provenance?.originalGameId===source.game.id);assert(generated);assert(data.some(row=>row.source.gameId===generated.id));const firstCounts=copy(destination.state.counters),firstHashes=hashes(destination);await C.continueFrom(destination,source.ctx.dir);assert.deepEqual(destination.state.counters,firstCounts);assert.deepEqual(hashes(destination),firstHashes);assert.deepEqual(hashes(source.ctx),before);S.append(path.join(source.ctx.dir,'dataset.jsonl'),{...sample(source.game,source.game.samples[0],'later-row'),weight:.5});await assert.rejects(C.continueFrom(destination,source.ctx.dir),/changed/i);});
 await check('unplayed source terminal claims are rejected during continuation',async()=>{const source=sourceFixture('source-bad-label'),destination=context('bad-label-destination'),pos=source.cutoff.samples[0],row=sample({...source.cutoff,winner:1},pos,'unplayed-winner');S.append(path.join(source.ctx.dir,'dataset.jsonl'),row);await assert.rejects(C.continueFrom(destination,source.ctx.dir),/terminal|incomplete|outcome|played|source game/i);});
 await check('interrupted continuation retries the same durable rows without duplication',async()=>{const source=sourceFixture('source-retry'),destination=context('retry-destination'),before=hashes(source.ctx),append=J.appendRows;try{J.appendRows=(...args)=>{const n=append(...args);if(args[1]==='games.jsonl')throw Error('injected copy interruption');return n;};await assert.rejects(C.continueFrom(destination,source.ctx.dir),/injected copy interruption/);}finally{J.appendRows=append;}assert.equal(S.read(path.join(destination.dir,'continuation.json')).complete,false);assert.equal(rows(path.join(destination.dir,'games.jsonl')).length,3);J.close(destination.dir);const resumed=reload(destination);const result=await C.continueFrom(resumed,source.ctx.dir);assert.equal(result.complete,true);assert.equal(rows(path.join(destination.dir,'games.jsonl')).length,3);assert.equal(rows(path.join(destination.dir,'dataset.jsonl')).length,3);assert.equal(resumed.state.counters.completedGames,2);assert.equal(resumed.state.counters.samples,3);assert.deepEqual(hashes(source.ctx),before);});
 await check('batched index failure rolls back only the open transaction and resumes with unchanged labels and splits',async()=>{
  const source=sourceFixture('source-index-batch'),destination=context('index-batch-destination');
  for(let i=0;i<128;i++){const game={...source.game,id:'extra-game-'+i,index:i+3};S.append(path.join(source.ctx.dir,'games.jsonl'),{...game,samples:undefined,model:undefined});S.append(path.join(source.ctx.dir,'dataset.jsonl'),sample(game,game.samples[0],'extra-row-'+i,'train'));}
  const before=hashes(source.ctx),verify=J.verify;let visited=0;
  try{J.verify=game=>{if(++visited===130)throw Error('injected index-batch crash');return verify(game);};await assert.rejects(C.continueFrom(destination,source.ctx.dir),/injected index-batch crash/);}finally{J.verify=verify;}
  const {DatabaseSync}=require('node:sqlite'),index=new DatabaseSync(path.join(destination.dir,'continuation.sqlite'),{readOnly:true});
  try{assert.equal(index.prepare('SELECT COUNT(*) n FROM games').get().n,128);assert.equal(index.prepare('SELECT COUNT(*) n FROM games WHERE id=?').get('extra-game-125').n,0);}finally{index.close();}
  assert.equal(rows(path.join(destination.dir,'games.jsonl')).length,0,'Raw games wait until every source label/family is validated');assert.equal(rows(path.join(destination.dir,'dataset.jsonl')).length,0);assert.equal(S.read(path.join(destination.dir,'continuation.json')).complete,false);
  const resumed=reload(destination);assert.equal((await C.continueFrom(resumed,source.ctx.dir)).complete,true);assert.equal(resumed.state.counters.generatedGames,131);assert.equal(resumed.state.counters.samples,131);assert.deepEqual(hashes(source.ctx),before);
  const original=new Map(rows(path.join(source.ctx.dir,'dataset.jsonl')).map(row=>[row.sampleId,row]));for(const row of rows(path.join(destination.dir,'dataset.jsonl'))){const prior=original.get(row.provenance.originalSampleId);assert.deepEqual(row.features,prior.features);assert.deepEqual(row.position,prior.position);assert.equal(row.target,prior.target);assert.equal(row.weight,prior.weight);assert.equal(row.split,'train');}
  const stopped=context('index-batch-stop');visited=0;
  try{J.verify=game=>{const checked=verify(game);if(++visited===130)fs.writeFileSync(path.join(stopped.dir,'stop.flag'),'injected user stop between index batches');return checked;};assert.equal((await C.continueFrom(stopped,source.ctx.dir)).complete,false);}finally{J.verify=verify;}
  const stoppedIndex=new DatabaseSync(path.join(stopped.dir,'continuation.sqlite'),{readOnly:true});try{assert.equal(stoppedIndex.prepare('SELECT COUNT(*) n FROM games').get().n,130);}finally{stoppedIndex.close();}
  assert.equal(rows(path.join(stopped.dir,'games.jsonl')).length,0);assert.equal(rows(path.join(stopped.dir,'dataset.jsonl')).length,0);fs.unlinkSync(path.join(stopped.dir,'stop.flag'));assert.equal((await C.continueFrom(reload(stopped),source.ctx.dir)).complete,true);assert.equal(rows(path.join(stopped.dir,'games.jsonl')).length,131);assert.deepEqual(hashes(source.ctx),before);
 });
 await check('stop flag during source copy preserves an incomplete manifest for explicit resume',async()=>{const source=sourceFixture('source-stop'),destination=context('stopped-destination');fs.writeFileSync(path.join(destination.dir,'stop.flag'),'user stop');const stopped=await C.continueFrom(destination,source.ctx.dir);assert.equal(stopped.complete,false);assert.equal(rows(path.join(destination.dir,'games.jsonl')).length,0);fs.unlinkSync(path.join(destination.dir,'stop.flag'));const result=await C.continueFrom(reload(destination),source.ctx.dir);assert.equal(result.complete,true);assert.equal(rows(path.join(destination.dir,'dataset.jsonl')).length,3);});
 await check('an unaccepted prior candidate can warm-start training but cannot become champion',async()=>{const source=sourceFixture('source-warm'),destination=context('warm-destination'),candidate={schemaVersion:1,kind:'forest-value-mlp',rulesId:S.RULES_ID,featureVersion:S.FEATURE_VERSION,inputSize:32,hiddenSize:1,activation:'relu',outputActivation:'tanh',normalization:{mean:Array(32).fill(0),scale:Array(32).fill(1)},layers:[{weights:[Array(32).fill(0)],bias:[0]},{weights:[[0]],bias:[0]}],modelId:'unaccepted-fixture',scale:600,training:{updates:10},adoption:{accepted:false}};N.validate(candidate);S.atomic(path.join(source.ctx.dir,'candidate.json'),candidate);const before=hashes(source.ctx);await C.continueFrom(destination,source.ctx.dir);assert.equal(S.read(path.join(destination.dir,'warm-start.json')).modelId,candidate.modelId);assert(!fs.existsSync(path.join(destination.dir,'champion.json')));assert(!fs.existsSync(path.join(destination.dir,'candidate.json')));assert.deepEqual(hashes(source.ctx),before);});
 await check('claimed source ply must match the actual played position',async()=>{const source=sourceFixture('source-wrong-position'),destination=context('position-destination'),data=rows(path.join(source.ctx.dir,'dataset.jsonl'));data[0].position.board[R.index('O15')]=1;data[0].positionKey=R.positionKey(data[0].position.board,data[0].position.p,data[0].position.firstPlayer);data[0].features=Array.from(N.extractFeatures(data[0].position.board,data[0].position.p,data[0].position.firstPlayer));S.atomic(path.join(source.ctx.dir,'dataset.jsonl'),data.map(row=>JSON.stringify(row)+'\n').join(''));await assert.rejects(C.continueFrom(destination,source.ctx.dir),/position|played|ply|source/i);});
 await check('stored features must match the versioned feature extractor',async()=>{const source=sourceFixture('source-wrong-features'),destination=context('features-destination'),data=rows(path.join(source.ctx.dir,'dataset.jsonl'));data[0].features[0]+=.5;S.atomic(path.join(source.ctx.dir,'dataset.jsonl'),data.map(row=>JSON.stringify(row)+'\n').join(''));await assert.rejects(C.continueFrom(destination,source.ctx.dir),/feature|position|extract/i);});
 await check('continuation preserves fresh-data baseline, seed cursor, trial budget and update history',async()=>{const source=sourceFixture('source-history'),destination=context('history-destination');source.ctx.state.generationIndex=20;source.ctx.state.trial=4;source.ctx.state.counters.trainingUpdates=10;source.ctx.state.importedSampleGames=['same-record-id'];source.ctx.state.analysisDone=['same-record-id:4'];S.save(source.ctx);const before=hashes(source.ctx);await C.continueFrom(destination,source.ctx.dir);assert.equal(destination.state.generationIndex,20);assert.equal(destination.state.trial,4);assert.equal(destination.state.counters.trainingUpdates,10);assert.equal(destination.state.lastTrainingSampleCount,3);assert.equal(destination.state.counters.samples-destination.state.lastTrainingSampleCount,0);assert.deepEqual(destination.state.importedSampleGames,['same-record-id']);assert.deepEqual(destination.state.analysisDone,['same-record-id:4']);assert.deepEqual(hashes(source.ctx),before);const legacy=sourceFixture('source-cursor-fallback'),fresh=context('cursor-fallback-destination');await C.continueFrom(fresh,legacy.ctx.dir);assert.equal(fresh.state.generationIndex,3,'Fresh seeds must start beyond every imported game index even if the old cursor was stale');});
 console.log(JSON.stringify({passed:true,checks:passed.length,scope:'Independent legal-game persistence, source boundaries, family isolation and crash recovery; no training/adoption',tests:passed}));
})().catch(error=>{console.error(error);process.exitCode=1;}).finally(()=>{for(const ctx of contexts)J.close(ctx.dir);const absolute=path.resolve(temporary);if(path.dirname(absolute)!==path.join(S.ROOT,'work')||!path.basename(absolute).startsWith('learning-corpus-test-'))throw Error('Unsafe project fixture cleanup');fs.rmSync(absolute,{recursive:true,force:true});const external=path.resolve(outside);if(path.dirname(external)!==path.resolve(os.tmpdir())||!path.basename(external).startsWith('omok-corpus-outside-'))throw Error('Unsafe external fixture cleanup');fs.rmSync(external,{recursive:true,force:true});});
