const $=id=>document.getElementById(id),canvas=$('board'),ctx=canvas.getContext('2d');
let N=15,b=Array(225).fill(0),mode=2,history=[],focus=112,last=-1,result=null,selected=0,pvStep=0,worker=null,token=0,pendingAction=null,analysisColor=1,busy=false,inspection=null,reviewMoves=null,reviewPly=0,reviewJump=93,reviewPreset=null;
/*RECORDS*/
const GAME95=/*GAME95*/;
const GAME47=/*GAME47*/;
const GAME33=/*GAME33*/;
const GAME31=/*GAME31*/;
const GAME29=/*GAME29*/;
const GAME48=/*GAME48*/;
const name=p=>p===1?'흑':'백',coord=i=>String.fromCharCode(65+i%N)+(N-Math.floor(i/N));
const mine=()=>Number($('mine').value),next=()=>Number($('next').value),starter=()=>Number($('starter').value),isLive=()=>$('inputMode').value==='live';
function say(t){$('notice').textContent=t;}
function counts(){return [0,b.filter(v=>v===1).length,b.filter(v=>v===2).length];}
function expected(){let c=counts(),p=starter();if(c[p]===c[3-p])return p;if(c[p]===c[3-p]+1)return 3-p;return 0;}
function kill(){token++;if(worker){worker.terminate();worker=null;}busy=false;$('analyze').disabled=false;$('cancel').style.display='none';}
function invalidate(){kill();$('timeStatus').textContent=$('time').value==='auto'?'자동 시간 조절 · 최대 8초':'수동 시간 설정';$('rejectedPanel').hidden=true;$('rejectedLines').replaceChildren();inspection=null;$('forbiddenNote').hidden=true;result=null;selected=0;pvStep=0;$('badge').textContent='분석 준비';$('badge').classList.remove('dangerText');$('move').textContent='—';$('move').classList.remove('dangerText');$('reason').textContent='상대 착수를 입력한 뒤 1순위 추천을 확인하세요.';$('rankHelp').textContent='분석이 완료되면 1순위 한 수를 확인하세요.';$('variation').textContent='예상 응수는 확정된 진행이 아닙니다.';$('alternatives').replaceChildren();$('compare').hidden=true;$('apply').disabled=true;$('apply').textContent='실제 판에 둔 뒤 이 수 기록';$('prevPV').disabled=true;$('nextPV').disabled=true;$('stats').textContent='모든 수를 끝까지 탐색하지 않으므로 항상 이기는 수는 보장할 수 없습니다.';}
function choose(v){mode=v;for(let [id,val]of [['black',1],['white',2],['erase',0]]){$(id).classList.toggle('active',v===val);$(id).setAttribute('aria-pressed',String(v===val));}render();}
/*DRAWING*/
function context(){let c=counts(),p=expected();$('setupSummary').textContent=`나: ${name(mine())}돌 · ${mine()===starter()?'선공':'후공'} / 상대: ${name(3-mine())}돌 · ${mine()===starter()?'후공':'선공'} / ${p?name(p)+' 차례':'돌 개수 확인 필요'}`;$('starter').options[0].textContent='백돌 먼저';$('starter').options[1].textContent='흑돌 먼저';$('next').disabled=isLive();}
function setNextFromCounts(){const p=expected();if(p){$('next').value=String(p);if(isLive())mode=p;}}
function renderExtra(){context();let S=900,pad=48,step=804/(N-1),eng=createEngine(N,b),st=eng.state();for(let line of st.lines){ctx.strokeStyle='#e14d32';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(pad+line[0]%N*step,pad+Math.floor(line[0]/N)*step);let end=line[4];ctx.lineTo(pad+end%N*step,pad+Math.floor(end/N)*step);ctx.stroke();}for(let i of result?.danger||[]){if(b[i])continue;ctx.strokeStyle='#bd3827';ctx.lineWidth=4;ctx.beginPath();ctx.arc(pad+i%N*step,pad+Math.floor(i/N)*step,step*.43,0,Math.PI*2);ctx.stroke();}
 if($('showForbidden').checked&&!pvStep){for(let i=0;i<b.length;i++)if(!b[i]&&!eng.legal(i,next())){const x=pad+i%N*step,y=pad+Math.floor(i/N)*step,r=step*.15;ctx.strokeStyle='#a0213c';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(x-r,y-r);ctx.lineTo(x+r,y+r);ctx.moveTo(x-r,y+r);ctx.lineTo(x+r,y-r);ctx.stroke();}}
 if(inspection&&!pvStep)for(let [k,t]of inspection.threes.entries()){ctx.strokeStyle=k%2?'#7b238d':'#007478';ctx.lineWidth=4;ctx.beginPath();t.stones.forEach((i,n)=>{const x=pad+i%N*step,y=pad+Math.floor(i/N)*step;n?ctx.lineTo(x,y):ctx.moveTo(x,y);});ctx.stroke();}
 $('before94').textContent=`${reviewJump+1}수 직전`;$('reviewNav').hidden=!reviewMoves;if(reviewMoves){$('recordPly').max=String(reviewMoves.length);$('recordPly').value=String(reviewPly);$('recordState').textContent=`${reviewPly} / ${reviewMoves.length}수 · 다음 ${name(next())} · ${reviewPly?'마지막 '+name(reviewMoves[reviewPly-1].p)+' '+coord(reviewMoves[reviewPly-1].i):'시작 전'}`;$('recordPrev').disabled=reviewPly===0;$('recordNext').disabled=reviewPly===reviewMoves.length;}
}
function explainForbidden(info){inspection=info;$('forbiddenNote').hidden=false;$('forbiddenNote').textContent=`${coord(info.i)}: 3·3 금수. `+info.threes.map(t=>`${t.direction} ${t.stones.map(coord).join('–')} (${coord(t.extension)}에 이어 열린 4, 양끝 ${t.ends.map(coord).join('·')})`).join(' / ');render();}
function put(i,p=mode){
 if(!Number.isInteger(i)||i<0||i>=b.length)return false;
 if(isLive()){
   const st=createEngine(N,b).state();if(st.winners.length||st.full){say('대국이 끝났습니다. 수정하려면 판 복원·수정으로 전환하세요.');return false;}
   if(!expected()){say('돌 개수와 선후공이 맞지 않습니다. 판 복원·수정에서 확인하세요.');return false;}
   if(p!==next()){say(`지금은 ${name(next())}돌 차례입니다. 다른 색은 판 복원·수정에서 입력하세요.`);return false;}
 }
 if(p&&b[i]){say('이미 돌이 있습니다. 지우개로 지운 뒤 입력하세요.');return false;}if(!p&&!b[i])return false;
 if(p&&isLive()&&!createEngine(N,b).legal(i,p)){explainForbidden(createEngine(N,b).moveInfo(i,p));say(`${coord(i)}은 3·3 금수입니다. 판 아래에 두 방향을 표시했습니다.`);return false;}
 inspection=null;$('forbiddenNote').hidden=true;reviewMoves=null;
 history.push({i,before:b[i],after:p,next:next(),mode,last});invalidate();b[i]=p;last=p?i:-1;focus=i;setNextFromCounts();choose(mode);say('');
 const st=createEngine(N,b).state();if(st.winners.length||st.full){showTerminal(st);return true;}
 if(isLive()&&p&&next()!==mine()){$('move').textContent='상대 차례';$('reason').textContent='상대가 실제로 둔 수를 입력해 주세요.';}
 if(isLive()&&$('auto').checked&&p&&next()===mine())analyze();return true;
}
canvas.addEventListener('click',e=>{let r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*900,y=(e.clientY-r.top)/r.height*900,s=804/(N-1),xx=Math.round((x-48)/s),yy=Math.round((y-48)/s);if(xx>=0&&xx<N&&yy>=0&&yy<N)put(yy*N+xx);});
canvas.addEventListener('keydown',e=>{let x=focus%N,y=Math.floor(focus/N);if(e.key==='ArrowLeft')x--;else if(e.key==='ArrowRight')x++;else if(e.key==='ArrowUp')y--;else if(e.key==='ArrowDown')y++;else if(e.key==='Enter'||e.key===' '){e.preventDefault();put(focus);return;}else return;e.preventDefault();focus=Math.max(0,Math.min(N-1,y))*N+Math.max(0,Math.min(N-1,x));canvas.setAttribute('aria-label',`${coord(focus)}, ${b[focus]?name(b[focus])+'돌':'빈칸'}. Enter로 입력`);render();});canvas.onfocus=render;canvas.onblur=render;
function showTerminal(st){$('badge').textContent='대국 종료';$('move').textContent=st.winners.length?st.winners.map(name).join('·')+' 5목':'빈자리 없음';$('reason').textContent=st.winners.length?'정확히 5목이 완성되었습니다. 이 판의 승리 수를 추천하지 않습니다.':'빈자리가 없습니다.';$('apply').disabled=true;render();}
function showResult(){
 const m=result?.moves[selected],kind=result?.kind;const bad=['lost','incomplete','none'].includes(kind);$('move').classList.toggle('dangerText',bad);$('badge').classList.toggle('dangerText',bad);if(!m)$('rankHelp').textContent='현재 권장할 승리 수가 없습니다.';
 if(result?.rejectedMoves?.length){$('rejectedPanel').hidden=false;$('rejectedLines').replaceChildren();for(let item of result.rejectedMoves.slice(0,3)){const el=document.createElement('p');el.textContent=item.line.map((i,k)=>name(k%2?3-analysisColor:analysisColor)+' '+coord(i)).join(' → ');$('rejectedLines').append(el);}}
 if(!m){$('compare').hidden=true;$('apply').disabled=true;const forbidden=result.lossReason==='forbidden-defense';$('move').textContent=kind==='lost'?(forbidden?'방어점이 금수':result.lossReason==='immediate'?'방어 불가':result.lossReason==='forcing-line'?'상대 강제 공격':'방어 수 미발견'):'분석 미완료';$('badge').textContent=kind==='lost'?'승리 추천 없음':'다시 분석 필요';$('reason').textContent=forbidden?`${name(3-analysisColor)}의 승리 자리 ${result.danger.map(coord).join(', ')}를 막아야 하지만, ${name(analysisColor)}은 그 자리에 3·3 금수로 둘 수 없습니다. 다른 빈칸에 둘 수 있어도 상대의 5목을 막지 못합니다.`:kind==='lost'?(result.lossReason==='immediate'?`상대 즉시 승리 자리: ${result.danger.map(coord).join(', ')}. 내 즉시 승리 수가 없고 한 수로 막을 수 없습니다.`:result.lossReason==='forcing-line'?`현재 차례의 방어 후보 ${result.screened}개 모두에 대해 상대의 강제 공격 경로가 확인됐습니다. 이 수들을 승리 추천으로 표시하지 않습니다. 아래에서 응수 예시를 확인하세요.`:'검사한 후보에서 상대의 강제 공격을 막을 수 있는 수를 찾지 못했습니다.'):'시간 안에 안전 검사를 마치지 못했습니다. 수읽기 시간을 늘려 다시 분석하세요.';$('variation').textContent='추천 수를 억지로 표시하지 않습니다. 이전 착수부터 복기하세요.';$('stats').textContent=`${result.nodes.toLocaleString()}개 탐색 노드 · ${(result.elapsed||0).toFixed(1)}초`;if(forbidden&&result.forbiddenDefenses?.length)explainForbidden(result.forbiddenDefenses[0]);render();return;}
 const main=selected===0;
 if(result.fallback){
   $('badge').textContent=busy?'계산 중 · 임시 착수 후보':kind==='lost'?'위험 경고 · 계속 둘 수 있는 수':'검사 미완료 · 임시 착수 후보';
   $('move').textContent=coord(m.i);
   $('reason').textContent=kind==='lost'?(result.lossReason==='immediate'?'상대의 즉시 승리 자리가 여러 곳이라 모두 막을 수 없습니다.':result.lossReason==='forbidden-defense'?'상대 승리 자리를 막는 수가 3·3 금수입니다.':'검사한 후보에서 상대의 강제 공격이 확인됐습니다.')+' 대국은 아직 끝나지 않았습니다. 계속 둘 수 있는 합법 수를 표시합니다. 상대가 다른 응수를 하면 판세가 달라질 수 있습니다.':(busy?'검사 중입니다.':'시간 안에 검사를 끝내지 못했습니다.')+' 아래 수는 합법이지만 안전성은 확인되지 않은 임시 후보입니다.';
   const threatText=(result.immediateThreats||[]).map(t=>coord(t.i)+' → '+t.lines.map(l=>l.map(coord).join('–')).join(' / ')).join('; ');
   if(result.mandatoryDefense){$('badge').textContent=busy?'계산 중 · 필수 방어':'필수 방어 · 이후 위험';$('reason').textContent=coord(result.danger[0])+'을 막아야 상대의 즉시 5목을 막습니다. 다른 후보는 표시하지 않습니다. '+threatText+' 이후의 강제 공격 위험은 남아 있습니다.';}
   else if(result.lossReason==='immediate'){$('badge').textContent='동시 승리 위협 · 한 수로 방어 불가';$('reason').textContent='상대 승리 자리 '+result.danger.map(coord).join('·')+' 중 하나를 막아도 다른 곳에서 5목이 됩니다. '+threatText+' 표시한 수는 대국을 계속하기 위한 후보이며, 모두 막는 수가 아닙니다.';}
   $('rankHelp').textContent=busy?'계산 중입니다. 급하면 분석 중지를 눌러 임시 후보를 사용할 수 있습니다.':'필승 또는 최선 수의 증명은 아닙니다. 실제 착수 후 기록하면 다음 상대 수에 맞춰 다시 분석합니다.';
   $('variation').textContent='착수 후보 · '+name(analysisColor)+' '+coord(m.i);
   $('compare').hidden=result.moves.length<2;$('alternatives').replaceChildren();result.moves.forEach((v,k)=>{const bt=document.createElement('button');bt.textContent='후보 '+(k+1)+' '+coord(v.i);bt.onclick=()=>{selected=k;pvStep=0;showResult();};$('alternatives').append(bt);});
   $('apply').disabled=busy;$('apply').textContent='실제 판에 '+name(analysisColor)+' '+coord(m.i)+'을 둔 뒤 기록';$('prevPV').disabled=true;$('nextPV').disabled=true;
   $('stats').textContent=result.nodes.toLocaleString()+'개 노드 · '+(result.elapsed||0).toFixed(1)+'초 · 합법 수 제공';render();return;
 }
 $('badge').textContent=(main?'1순위 · ':'비교 '+(selected+1)+'순위 · ')+(kind==='win'?'즉시 승리':kind==='forced'?'연속 4목 강제 승리 확인':kind==='block'?'필수 방어':'제한 탐색 추천');$('move').textContent=coord(m.i);
 $('reason').textContent=kind==='win'?`${coord(m.i)}에 두면 정확히 5목입니다.`:kind==='forced'?'상대가 필수 방어를 하더라도 이어지는 4목 공격으로 승리하는 경로를 확인했습니다.':kind==='block'?`상대가 ${result.danger.map(coord).join(', ')}에서 바로 이깁니다. 먼저 막아야 합니다. 이후 승리는 보장되지 않습니다.`:'즉시 위협·금수 방어·상대의 연속 4목·3목 준비 공격을 검사하고 남은 후보를 비교했습니다. 필승 판정은 아닙니다.';
 if(m.score<-9000000&&kind!=='win'&&kind!=='forced')$('reason').textContent+=' 탐색한 진행에서 패배 위협이 발견되었습니다.';
 if(analysisColor!==mine())$('reason').textContent+=' 주의: 현재 상대 돌의 수를 분석 중입니다.';
 if(!main)$('reason').textContent+=' 다른 후보를 비교 중입니다. 권장 수는 1순위입니다.';
 $('rankHelp').textContent=busy?'아직 계산 중인 잠정 후보입니다. 분석이 끝날 때까지 기다려 주세요.':main?'이 좌표 한 곳에 두세요. 후보를 반복해서 누를 필요가 없습니다.':'비교 후보입니다. 다시 권장 수를 보려면 1순위로 돌아가세요.';if(busy)$('badge').textContent='계산 중 · 잠정 후보';
 if(!busy&&m.score<-9000000){$('badge').textContent='패배 경로 발견 · 제한 탐색';$('move').classList.add('dangerText');$('rankHelp').textContent='승리 수가 아닙니다. 탐색한 진행에서는 불리하며, 더 앞선 장면을 복기하세요.';}if(!busy&&result.depth===0&&m.status!=='opening'){$('badge').textContent='비교 탐색 미완료 · 임시 후보';$('rankHelp').textContent='후보 비교를 완료하지 못했습니다. 이 수는 임시 후보입니다.';}if(!busy&&m.score>=-9000000&&m.status==='unverified'){$('badge').textContent='연속 공격 검사 미완료';$('rankHelp').textContent='시간 안에 이 후보의 상대 강제 공격 검사를 마치지 못했습니다. 시간을 늘려 재분석하세요.';}
 $('compare').hidden=result.moves.length<2;$('alternatives').replaceChildren();result.moves.forEach((v,k)=>{let bt=document.createElement('button');bt.textContent=`${k+1}순위 ${coord(v.i)}`;bt.classList.toggle('active',k===selected);bt.onclick=()=>{selected=k;pvStep=0;showResult();};$('alternatives').append(bt);});
 $('variation').textContent=(pvStep?'미리보기 '+pvStep+'수 · ':'예상 진행 · ')+m.pv.map((v,k)=>`${name(k%2?3-analysisColor:analysisColor)} ${coord(v)}`).join(' → ')+(kind==='forced'?' (상대 필수 방어 기준)':'');
 $('prevPV').disabled=pvStep===0;$('nextPV').disabled=pvStep>=m.pv.length;$('apply').disabled=busy;$('apply').textContent=`실제 판에 ${name(analysisColor)} ${coord(m.i)}을 둔 뒤 기록`;
 $('stats').textContent=`${busy?'분석 중 · ':''}완료 깊이 ${result.depth}수 · ${result.nodes.toLocaleString()}개 노드 · ${(result.elapsed||0).toFixed(1)}초${result.rejected?' · 위험 후보 '+result.rejected+'개 제외':''}${result.screeningComplete===false?' · 후보 검사 일부 완료':''}`;render();
}
function analyze(){
 invalidate();let p=next(),eng=createEngine(N,b),st=eng.state();if(st.winners.length||st.full){showTerminal(st);return;}
 const expectedColor=expected();if(!expectedColor||expectedColor!==p){$('move').textContent='차례 확인';$('reason').textContent='돌 개수·먼저 두는 색·이번 차례가 서로 맞지 않습니다. 설정이나 누락된 돌을 확인하세요.';say('잘못된 차례의 추천을 막기 위해 분석을 중단했습니다.');render();return;}
 if(isLive()&&p!==mine()){$('move').textContent='상대 차례';$('reason').textContent='백/흑을 바꾸지 말고, 상대의 실제 착수부터 입력하세요. 상대 분석은 판 복원·수정에서 가능합니다.';render();return;}
 analysisColor=p;let mineToken=token,start=performance.now();busy=true;$('badge').textContent='위협 검사와 수읽기 중';$('move').textContent='•••';$('reason').textContent='검사가 완료되면 1순위 한 수를 표시합니다.';$('analyze').disabled=true;$('cancel').style.display='block';
 const src=$('engineSource').textContent+'\nonmessage=e=>{try{const {N,b,p,ms}=e.data;const result=createEngine(N,b).analyze(p,ms,r=>postMessage({result:r,partial:true}));postMessage({result});}catch(err){postMessage({error:err.message});}}';
 try{let url=URL.createObjectURL(new Blob([src],{type:'text/javascript'}));worker=new Worker(url);URL.revokeObjectURL(url);
 worker.onmessage=e=>{if(mineToken!==token)return;const data=e.data;if(!data.partial)kill();if(data.error){say('분석 오류: '+data.error);$('badge').textContent='분석 실패';return;}if(!validateOmokAnalysis(N,b,p,data.result)){invalidate();$('badge').textContent='추천 검증 실패';$('move').textContent='추천 중단';say('추천 또는 예상 진행에 금수·불가능한 착수가 포함되어 표시를 중단했습니다.');return;}result=data.result;result.elapsed=(performance.now()-start)/1000;selected=0;pvStep=0;showResult();$('timeStatus').textContent=result.automatic?'자동 · '+result.elapsed.toFixed(1)+'초 · '+(result.autoReason||'분석 중'):'수동 · '+result.elapsed.toFixed(1)+'초';};
 worker.onerror=()=>{kill();$('badge').textContent='분석 실패';say('분석을 실행하지 못했습니다. Chrome 또는 Edge로 열어 주세요.');};worker.postMessage({N,b,p,ms:$('time').value==='auto'?'auto':Number($('time').value)});
 }catch(e){kill();$('badge').textContent='분석 실패';say('이 브라우저에서 분석을 실행할 수 없습니다.');}
}
for(let [id,p]of [['black',1],['white',2],['erase',0]])$(id).onclick=()=>{if(!p){$('inputMode').value='setup';invalidate();say('판 복원·수정으로 전환했습니다.');}choose(p);};
$('time').onchange=()=>{invalidate();render();};$('analyze').onclick=analyze;$('cancel').onclick=()=>{kill();if(result){showResult();$('timeStatus').textContent='사용자가 분석 중지 · 마지막 완료 결과';}else invalidate();say('분석을 중지했습니다. 표시된 결과는 중지 전까지 완료한 검사입니다.');};
$('apply').onclick=()=>{if(busy)return;let m=result?.moves[selected];if(m)put(m.i,analysisColor);};$('prevPV').onclick=()=>{pvStep--;showResult();};$('nextPV').onclick=()=>{pvStep++;showResult();};$('backBest').onclick=()=>{selected=0;pvStep=0;showResult();};
$('undo').onclick=()=>{if(reviewMoves){showRecordPly(reviewPly-1);return;}let h=history.pop();if(!h)return;invalidate();b[h.i]=h.before;$('next').value=String(h.next);last=h.last;mode=h.mode;setNextFromCounts();choose(mode);say('한 수를 취소했습니다.');};
$('next').onchange=()=>{invalidate();render();};$('mine').onchange=()=>{invalidate();render();};$('starter').onchange=()=>{invalidate();setNextFromCounts();choose(mode);};$('inputMode').onchange=()=>{invalidate();setNextFromCounts();choose(mode);say(isLive()?'현재 돌 개수에 맞춰 차례를 설정했습니다.':'돌 위치를 자유롭게 복원합니다. 모두 입력한 뒤 추천 찾기를 누르세요.');};
function clearBoard(size=N){invalidate();inspection=null;reviewMoves=null;$('forbiddenNote').hidden=true;N=size;b=Array(N*N).fill(0);history=[];last=-1;focus=Math.floor(N/2)*(N+1);$('size').value=String(N);$('next').value=String(starter());mode=starter();$('reviewNote').hidden=true;reviewPreset=null;choose(mode);say('새 판입니다. 먼저 두는 색부터 입력하세요.');}
function confirmAction(action){if(!b.some(Boolean)){action();return;}pendingAction=action;$('confirm').showModal();}
$('reset').onclick=()=>confirmAction(()=>clearBoard());$('size').onchange=()=>{const n=Number($('size').value);$('size').value=String(N);confirmAction(()=>clearBoard(n));};$('keep').onclick=()=>{$('confirm').close();pendingAction=null;};$('clear').onclick=()=>{const action=pendingAction;$('confirm').close();pendingAction=null;action?.();};
$('imageInput').onchange=e=>{const f=e.target.files[0];if(!f)return;if(!f.type.startsWith('image/')){say('이미지 파일을 선택하세요.');return;}if($('reference').src.startsWith('blob:'))URL.revokeObjectURL($('reference').src);$('reference').src=URL.createObjectURL(f);$('reference').hidden=false;};
function review(){clearBoard(15);$('mine').value='1';$('starter').value='2';$('inputMode').value='setup';const black='L12 F10 I10 G9 F8 G8 E7 F7 G7 H7 F6 C5 G5',white='K11 H10 J10 F9 I9 H8 I8 D7 I7 D6 G6 H6 I6 J6';const ix=s=>(15-Number(s.slice(1)))*15+s.charCodeAt(0)-65;for(let s of black.split(' '))b[ix(s)]=1;for(let s of white.split(' '))b[ix(s)]=2;$('next').value='1';mode=1;choose(1);$('reviewNote').hidden=false;$('reviewNote').textContent='실제 진행: 백 I6 → 흑 I5 → 백 K6. 지금은 백 I6 직후입니다. 백은 가로 G6–J6과 세로 I6–I9의 4목을 동시에 갖고 있어, K6과 I5 중 하나만 막을 수 있습니다. 이보다 앞선 착수에서 예방해야 했습니다.';analyze();}
$('review').onclick=()=>confirmAction(review);
$('showForbidden').onchange=render;
function showRecordPly(n){if(!reviewMoves)return;invalidate();inspection=null;$('forbiddenNote').hidden=true;reviewPly=Math.max(0,Math.min(reviewMoves.length,Number(n)));b=Array(N*N).fill(0);history=[];last=-1;for(let {i,p}of reviewMoves.slice(0,reviewPly)){history.push({i,before:0,after:p,next:p,mode:p,last});b[i]=p;last=i;}setNextFromCounts();mode=next();$('inputMode').value='live';choose(mode);say(`기보 ${reviewPly}수까지 복원했습니다. 추천 찾기로 해당 차례를 분석할 수 있습니다.`);if(reviewPreset==='47'){$('reviewNote').hidden=false;$('reviewNote').textContent=reviewPly>=45?'45수 백 J4로 F4·K4 두 승리 자리가 생겼습니다. 흑 K4 이후 백 F4에서 5목이 완성됩니다.':reviewPly>=37?'이 구간에서는 백의 연속 공격이 핵심입니다. 흑 J3 → 백 G4 → 흑 F3 → 백 H4 → 흑 H3 → 백 J4로 두 승리 자리가 생깁니다. 다른 후보의 방어 가능성도 추천 찾기에서 검사합니다.':'이번 47수 대국입니다. 더 앞선 장면에서 공격·방어의 선택을 비교할 수 있습니다.';}if(reviewPreset==='48'){$('reviewNote').hidden=false;$('reviewNote').textContent=reviewPly>=46?'46수 백 G5로 G5–G8의 열린 4목이 됐습니다. G4·G9 중 한 곳을 막아도 다른 곳에서 백이 이깁니다.':reviewPly>=38?'이 구간은 백의 강제 공격이 이어집니다. G6 → G7 → G5로 두 승리 자리가 생깁니다. 당장의 방어만으로 해결되지 않으므로 더 앞선 장면에서 비교해야 합니다.':'이전 버전은 28수·34수 직후 10초 분석에서 위험 검사에 시간을 소진해 비교 깊이가 0이었습니다. 이제 검사 시간을 제한하고 남은 시간에 후보를 비교합니다. 안전 검사가 끝나지 않은 수는 미완료로 표시합니다.';}if(reviewPreset==='29'){$('reviewNote').hidden=false;$('reviewNote').textContent=reviewPly>=27?'27수 백 J5로 승리 자리 M8과 H3이 동시에 생겼습니다. 흑 H3은 한쪽을 막았지만 백 M8이 I4–J5–K6–L7–M8의 5목을 완성했습니다.':reviewPly>=25?'25수 백 L7 뒤 K7은 H7–I7–J7–빈 K7–L7의 5목을 막는 필수 방어입니다. 하지만 백 J5가 이어지는 양끝이 열린 4목 위협이 있어 더 앞서 예방해야 합니다.':'이번 흑 후공 29수 대국입니다. 이전 장면으로 이동해 공격과 방어를 비교하세요.';}if(reviewPreset==='31'){$('reviewNote').hidden=false;$('reviewNote').textContent='흑 선공 대국입니다. 24수 백 L14 뒤 추천이 중단됐던 장면을 복원했습니다. 이제 위험 경고와 합법 착수 후보를 함께 표시합니다. 실제 진행은 흑 G6 이후 계속되어 31수 F11에서 흑 F11–J11의 5목으로 승리했습니다.';}if(reviewPreset==='33'){$('reviewNote').hidden=false;$('reviewNote').textContent=reviewPly>=33?'33수 백 J6: J6–K7–L8–M9가 열린 4목입니다. I5와 N10 중 한 곳만 막을 수 있어 방어 불가입니다.':reviewPly>=29?'백 M9 이후에는 이미 강제 공격이 있습니다. 실제 진행: 흑 L9 → 백 K7 → 흑 K6 → 백 J6. 흑 K6은 K열의 즉시 5목을 막는 필수 방어였습니다.':reviewPly>=25?'이 구간의 흑 F11은 백 E12를 강제하지만 위기를 해결하지 못합니다. 3초·10초에서 놓칠 수 있는 더 긴 패배 경로를 30초로 확인하세요.':'24수 흑 K11 직전입니다. 30초 분석에서 K7도 방어 후보로 비교됩니다. 이 수의 승리를 증명한 것은 아닙니다.';}const st=createEngine(N,b).state();if(st.winners.length||st.full)showTerminal(st);}
function loadRecord(text,n,size=N,jump=null,preset=null){let parsed;try{parsed=parseOmokRecord(text,size);}catch(e){say(e.message);return;}confirmAction(()=>{clearBoard(size);$('starter').value=String(parsed.first);$('mine').value='1';reviewMoves=parsed.moves;reviewJump=jump??Math.max(0,parsed.moves.length-2);reviewPreset=preset;showRecordPly(n??parsed.moves.length);});}
$('loadRecord').onclick=()=>loadRecord($('recordText').value);
$('load95').onclick=()=>{let text=GAME95.map((s,k)=>`${k+1}. ${k%2?'흑':'백'} ${s}`).join(' · ');$('recordText').value=text;loadRecord(text,95,15,93,'95');};
$('load47').onclick=()=>{const text=GAME47.map((s,k)=>`${k+1}. ${k%2?'흑':'백'} ${s}`).join(' · ');$('recordText').value=text;loadRecord(text,47,15,37,'47');};
$('load48').onclick=()=>{const text=GAME48.map((s,k)=>`${k+1}. ${k%2?'백':'흑'} ${s}`).join(' · ');$('recordText').value=text;loadRecord(text,34,15,28,'48');};
$('load29').onclick=()=>{const text=GAME29.map((s,k)=>`${k+1}. ${k%2?'흑':'백'} ${s}`).join(' · ');$('recordText').value=text;loadRecord(text,27,15,25,'29');};
$('load31').onclick=()=>{const text=GAME31.map((s,k)=>`${k+1}. ${k%2?'백':'흑'} ${s}`).join(' · ');$('recordText').value=text;loadRecord(text,24,15,24,'31');};
$('load33').onclick=()=>{const text=GAME33.map((s,k)=>`${k+1}. ${k%2?'흑':'백'} ${s}`).join(' · ');$('recordText').value=text;loadRecord(text,33,15,23,'33');};
$('recordPly').oninput=e=>showRecordPly(e.target.value);$('recordPrev').onclick=()=>showRecordPly(reviewPly-1);$('recordNext').onclick=()=>showRecordPly(reviewPly+1);
$('before94').onclick=()=>{if(reviewMoves)showRecordPly(Math.min(reviewJump,reviewMoves.length));};
$('demo').onclick=()=>confirmAction(()=>{clearBoard(15);$('inputMode').value='setup';$('starter').value='1';$('mine').value='1';b[7*15+4]=2;for(let x=5;x<=8;x++)b[7*15+x]=1;for(let [x,y]of [[6,6],[7,6],[9,9]])b[y*15+x]=2;setNextFromCounts();choose(1);say('승리 예제: 흑이 J8에 두면 5목입니다.');analyze();});
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_omok_board',description:'Read current board, turn, move history and analysis.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:input=>{if(input===null||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw Error('No input fields are accepted');return {version:10,size:N,next:next(),mine:mine(),first:starter(),stones:b.flatMap((p,i)=>p?[{coordinate:coord(i),color:name(p)}]:[]),history:history.map(h=>({coordinate:coord(h.i),color:h.after?name(h.after):'erase'})),analysis:result?{kind:result.kind,danger:result.danger.map(coord),recommendation:result.moves.map(m=>coord(m.i))}:null};}})).catch(()=>{});}catch{}}
choose(2);
