'use strict';
// Resume known historical runs with the exact preserved code. Never rewrite
// an old run's identity to pretend a new algorithm produced its old results.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),cp=require('node:child_process'),threads=require('node:worker_threads');
const {builtinModules}=require('node:module'),crypto=require('node:crypto');
const ROOT=path.resolve(__dirname,'../..'),SNAPSHOT=path.join(ROOT,'work/continuous-runtime-baseline.json');
function assertDeliverySource(snapshot){const now=require('./state.cjs').sourceIdentity();if(now.sourceHash!==snapshot.identity.sourceHash||snapshot.identity.version>=2&&(now.harnessHash!==snapshot.identity.harnessHash||now.runtimeHash!==snapshot.identity.runtimeHash))throw Error('The production engine changed: archived evaluation cannot publish a model into a different engine or runtime. Continue experience in a new run and evaluate again.');}
function archiveId(identity){return crypto.createHash('sha256').update(JSON.stringify([identity.sourceHash,identity.harnessHash,identity.runtimeHash||null])).digest('hex');}
function captureRuntime(identity=require('./state.cjs').sourceIdentity()){
 if(identity.version!==2||!Array.isArray(identity.sourceManifest)||!Array.isArray(identity.harnessManifest))throw Error('Full runtime capture requires canonical dependency manifests');
 const S=require('./state.cjs'),id=archiveId(identity),file=path.join(ROOT,'work/runtime-archives',id+'.json'),files={};for(const row of [...identity.sourceManifest,...identity.harnessManifest]){const source=fs.readFileSync(path.join(ROOT,row.path),'utf8');if(S.hash(source)!==row.sha256)throw Error('Runtime dependency changed during capture: '+row.path);files[row.path]=source;}
 const prior=S.read(file);if(prior){if(prior.identity?.sourceHash!==identity.sourceHash||prior.identity?.harnessHash!==identity.harnessHash||prior.identity?.runtimeHash!==identity.runtimeHash||S.hash(prior.files)!==S.hash(files))throw Error('Existing preserved runtime conflicts with its immutable identity');return {archiveId:id,file};}
 S.atomic(file,{schemaVersion:2,archiveId:id,createdAt:new Date().toISOString(),identity,externalDependencies:[],files});return {archiveId:id,file};
}
function selectResumeRunner(run,{repo=ROOT}={}){
 repo=path.resolve(repo);const S=require(path.join(repo,'tools/learning/state.cjs')),state=S.read(path.join(run,'state.json')),normal={runner:path.join(repo,'tools/learning/run.cjs'),argsPrefix:[],cwd:repo};if(!state)return normal;
 const now=S.sourceIdentity();if(state.identity?.version>=2&&state.identity.runtimeHash!==now.runtimeHash)throw Error('The preserved native Node/V8/SQLite runtime differs from this host. Continue experience in a new run and evaluate again.');if(state.identity?.sourceHash===now.sourceHash&&state.identity?.harnessHash===now.harnessHash&&(!(state.identity?.version>=2)||state.identity.runtimeHash===now.runtimeHash))return normal;
 if(state.identity?.version>=2){const id=archiveId(state.identity),saved=S.read(path.join(repo,'work/runtime-archives',id+'.json'));if(saved&&saved.identity.sourceHash===state.identity.sourceHash&&saved.identity.harnessHash===state.identity.harnessHash&&saved.identity.runtimeHash===state.identity.runtimeHash)return {runner:path.join(repo,'tools/learning/archive.cjs'),argsPrefix:['--archived-run','--runtime='+id],cwd:repo};}
 const file=path.join(repo,'work/continuous-runtime-baseline.json'),snapshot=S.read(file);if(snapshot&&state.identity?.sourceHash===snapshot.identity.sourceHash&&state.identity?.harnessHash===snapshot.identity.harnessHash)return {runner:path.join(repo,'tools/learning/archive.cjs'),argsPrefix:['--archived-run'],cwd:repo};
 const archived=state.identity?.harnessHash;if(/^[a-f0-9]{64}$/.test(archived||'')){const saved=S.read(path.join(repo,'work/runtime-archives',archived+'.json'));if(saved&&saved.identity.sourceHash===state.identity.sourceHash&&saved.identity.harnessHash===archived)return {runner:path.join(repo,'tools/learning/archive.cjs'),argsPrefix:['--archived-run','--runtime='+archived],cwd:repo};}
 throw Error('이 실험의 실행 버전을 찾을 수 없습니다. 저장된 경험을 새 누적 실험으로 이어 주세요.');
}
function frozenRuntime(snapshotFile=SNAPSHOT){
 const snapshot=JSON.parse(fs.readFileSync(snapshotFile,'utf8')),sources=snapshot.files,cache=new Map(),relative=file=>path.relative(ROOT,path.resolve(file)).split(path.sep).join('/');
 if(snapshot.identity?.version>=2&&snapshot.identity.runtimeHash!==require('./state.cjs').sourceIdentity().runtimeHash)throw Error('Preserved native runtime mismatch; continue experience in a new run');
 const inside=key=>key!== '..'&&!key.startsWith('../')&&!path.isAbsolute(key),code=key=>inside(key)&&(key==='build.cjs'||/^(?:src|tools\/learning)\/.*\.(?:js|cjs|py|html)$/.test(key)||/^test\/reader\/game(?:29|31|33|47|48|95)\.cjs$/.test(key));
 if(!sources||typeof sources!=='object'||Array.isArray(sources))throw Error('Archived runtime files are missing');
 const mandatory=['src/node-engine.cjs','build.cjs','src/neural-app.js'];for(const name of mandatory)if(typeof sources[name]!=='string')throw Error('Archived repository dependency missing: '+name);
 for(const row of [...(snapshot.identity?.sourceManifest||[]),...(snapshot.identity?.harnessManifest||[])])if(typeof sources[row.path]!=='string'||crypto.createHash('sha256').update(sources[row.path]).digest('hex')!==row.sha256)throw Error('Archived dependency manifest mismatch: '+row.path);
 const manifested=new Set([...(snapshot.identity?.sourceManifest||[]),...(snapshot.identity?.harnessManifest||[])].map(row=>row.path));
 const requireSource=key=>{if(!inside(key)||typeof sources[key]!=='string'||snapshot.identity?.version>=2&&!manifested.has(key))throw Error('Archived repository dependency missing from files or canonical manifest: '+key);return sources[key];},virtualFds=new Map();let nextFd=-100000;
 const sourceKey=file=>typeof file==='string'?relative(file):file instanceof URL&&file.protocol==='file:'?relative(require('node:url').fileURLToPath(file)):null;
 const frozenFs={...fs,existsSync(file){const key=sourceKey(file);if(key&&Object.hasOwn(sources,key))return true;if(key&&code(key))requireSource(key);return fs.existsSync(file);},readFileSync(file,options){const key=sourceKey(file);if(key&&(Object.hasOwn(sources,key)||code(key))){const bytes=Buffer.from(requireSource(key));return typeof options==='string'||options?.encoding?bytes.toString(typeof options==='string'?options:options.encoding):bytes;}return fs.readFileSync(file,options);},openSync(file,flags,...args){const key=sourceKey(file);if(key&&(Object.hasOwn(sources,key)||code(key))){if(flags!=='r')throw Error('Archived repository dependencies are immutable: '+key);const fd=nextFd--;virtualFds.set(fd,{bytes:Buffer.from(requireSource(key)),cursor:0});return fd;}return fs.openSync(file,flags,...args);},readSync(fd,buffer,offset,length,position){const row=virtualFds.get(fd);if(!row)return fs.readSync(fd,buffer,offset,length,position);const start=position==null?row.cursor:position,n=row.bytes.copy(buffer,offset,start,Math.min(row.bytes.length,start+length));if(position==null)row.cursor+=n;return n;},closeSync(fd){if(virtualFds.has(fd)){virtualFds.delete(fd);return;}return fs.closeSync(fd);}};
 const frozenCp={...cp,execFileSync(command,args,options){if(args?.[0]===path.join(ROOT,'build.cjs'))assertDeliverySource(snapshot);return cp.execFileSync(command,args,options);},spawn(command,args,options){if(args?.[0]===path.join(ROOT,'tools/learning/train.py')){const target=path.join(ROOT,'work/archived-trainer-'+snapshot.identity.harnessHash+'.py'),source=sources['tools/learning/train.py'];if(fs.existsSync(target)){if(fs.readFileSync(target,'utf8')!==source)throw Error('Archived trainer content changed');}else fs.writeFileSync(target,source);args=[target,...args.slice(1)];}return cp.spawn(command,args,options);}};
 class ArchivedWorker extends threads.Worker{constructor(file,options={}){const key=sourceKey(file);if(key&&inside(key)){requireSource(key);super(__filename,{...options,workerData:{archivedWorkerModule:key,snapshotFile,original:options.workerData}});}else throw Error('Archived worker dependency is outside its preserved repository');}}
 const frozenThreads={...threads,Worker:ArchivedWorker,workerData:threads.workerData?.archivedWorkerModule?threads.workerData.original:threads.workerData};
 function load(key){key=relative(path.join(ROOT,key));if(cache.has(key))return cache.get(key).exports;requireSource(key);const module={exports:{}};cache.set(key,module);const filename=path.join(ROOT,key),directory=path.dirname(filename);
  const localRequire=id=>{if(id==='node:fs'||id==='fs')return frozenFs;if(id==='node:child_process'||id==='child_process')return frozenCp;if(id==='node:worker_threads'||id==='worker_threads')return frozenThreads;if(id.startsWith('.')||path.isAbsolute(id)){let name=relative(path.resolve(directory,id));if(!Object.hasOwn(sources,name))for(const suffix of ['.js','.cjs','.json','/index.js','/index.cjs'])if(Object.hasOwn(sources,name+suffix)){name+=suffix;break;}return load(name);}if(!builtinModules.includes(id)&&!builtinModules.includes(id.replace(/^node:/,'')))throw Error('Archived external dependency is not allowlisted (only native Node built-ins are allowed): '+id);return require(id);};
  if(key.endsWith('.json'))module.exports=JSON.parse(sources[key]);else vm.compileFunction(sources[key],['module','exports','require','__filename','__dirname'],{filename})(module,module.exports,localRequire,filename,directory);return module.exports;
 }
 const identity=load('tools/learning/state.cjs').sourceIdentity();if(identity.sourceHash!==snapshot.identity.sourceHash||identity.harnessHash!==snapshot.identity.harnessHash||snapshot.identity.version>=2&&identity.runtimeHash!==snapshot.identity.runtimeHash)throw Error('Preserved runtime identity mismatch');return {snapshot,load};
}
if(!threads.isMainThread&&threads.workerData?.archivedWorkerModule)frozenRuntime(threads.workerData.snapshotFile).load(threads.workerData.archivedWorkerModule);
else if(require.main===module){if(process.argv[2]!=='--archived-run')throw Error('Archive runner requires a trusted archived-run selection');const args=process.argv.slice(3);let snapshotFile=SNAPSHOT;if(args[0]?.startsWith('--runtime=')){const id=args.shift().slice(10);if(!/^[a-f0-9]{64}$/.test(id))throw Error('Invalid archived runtime identity');snapshotFile=path.join(ROOT,'work/runtime-archives',id+'.json');}frozenRuntime(snapshotFile).load('tools/learning/run.cjs').main(args).catch(error=>{console.error(error.stack||error);process.exitCode=1;});}
module.exports={selectResumeRunner,frozenRuntime,assertDeliverySource,archiveId,captureRuntime};
