'use strict';
const fs=require('node:fs'),path=require('node:path');
const readline=require('node:readline');
const {ROOT,hash,read,atomic,baselineFactory,save,stopped,sourceIdentity}=require('./state.cjs');
const {blank,index,coord,replay,opening,outcome,legalMoves,positionKey,familyFor}=require('./replay.cjs');
const neural=()=>require('../../src/neural-evaluator.js');
const current=options=>require('../../src/node-engine.cjs')(options);
function parity(model,report){
 neural().validate(model);if(!report?.passed||report.modelId!==model.modelId||report.featureVersion!==model.featureVersion||!Array.isArray(report.cases)||!report.cases.length)return {passed:false,reason:'Missing or mismatched Python parity fixtures/model identity'};
 const E=neural().createEvaluator(model),rows=report.cases.map(c=>({expected:c.expectedValue,actual:E.raw(c.features),error:Math.abs(E.raw(c.features)-c.expectedValue)})),maximum=Math.max(...rows.map(x=>x.error));
 let effectiveError=0;for(const c of report.cases)if(Number.isFinite(c.expectedEffectiveValue)){const f=c.features,swapped=[...f.slice(12,24),...f.slice(0,12),f[25],f[24],f[27],f[26],-f[28],f[29],f[31],f[30]],actual=(E.raw(f)-E.raw(swapped))/2;effectiveError=Math.max(effectiveError,Math.abs(actual-c.expectedEffectiveValue));}
 return {passed:rows.every(x=>Number.isFinite(x.error))&&maximum<=Math.min(1e-5,report.tolerance||1e-5)&&effectiveError<=1e-5,maxAbsoluteError:maximum,effectiveMaxAbsoluteError:effectiveError,cases:rows.length,modelId:model.modelId};
}
function trainingEvidence(model,report,datasetHash){const errors=[];if(report?.modelExported!==true)errors.push('No model exported by the current training invocation');if(report?.modelId!==model?.modelId)errors.push('Candidate/training model identity mismatch');if(!datasetHash||report?.datasetHash!==datasetHash||model?.training?.datasetHash!==datasetHash)errors.push('Candidate/training/current dataset identity mismatch');if(!(model?.training?.updates>0)||report?.training?.updates!==model.training.updates)errors.push('Missing or mismatched completed training updates');if(report?.device?.finite!==true)errors.push('Training finiteness evidence missing');return {passed:!errors.length,errors,modelId:model?.modelId,datasetHash,updates:model?.training?.updates||0,trainedOnCuda:!!model?.training?.trainedOnCuda,actualUpdatesThisRun:report?.device?.updatesThisRun||0,scope:'Current snapshot and exported model consistency; optimizer loss is not playing strength'};}
function rulesAudit(candidate,base){
 const fixtures=[['five','D8 E8 F8 G8',true,true],['five+33','E8 F8 G8 I8 H7 H9 G7 I9',true,true],['33','G8 I8 H7 H9',false,false],['44','F8 G8 I8 H6 H7 H9',true,false],['overline','C8 D8 E8 F8 G8',true,false],['overline+33','C8 D8 E8 F8 G8 H7 H9 G7 I9',false,false]],errors=[];let checks=0;
 for(const p of [1,2])for(const [name,stones,legal,win]of fixtures){const b=blank();stones.split(' ').forEach(c=>b[index(c)]=p);for(const make of [base,current]){const E=make({firstPlayer:3-p,optimized:true,model:make===current?candidate:null}),copy=b.slice(),r=E.inspect(b,index('H8'),p);if(r.legal!==legal||!!r.win.length!==win||JSON.stringify(copy)!==JSON.stringify(b))errors.push(name+' color '+p);checks++;}}
 for(const p of [1,2]){const b=blank();'D8 E8 F8 G8'.split(' ').forEach(c=>b[index(c)]=p);b[index('C8')]=3-p;for(const make of [base,current]){const E=make({firstPlayer:p,optimized:true,model:make===current?candidate:null}),win=E.analyze(b,p,30,[]);if(win.i!==index('H8')||!E.inspect(b,win.i,p).win.length)errors.push('missed own immediate five');const block=E.analyze(b,3-p,30,[]);if(block.i!==index('H8'))errors.push('missed compulsory defense');checks+=2;}}
 return {passed:!errors.length,checks,errors,scope:'Both-color house-rule fixtures, winning priority, board restoration and compulsory immediate defense. Broader repository regressions remain separate.'};
}
function pairedStats(games,{minPairs=32,confidence=.95,trial=1}={}){
 const families=new Map(),groups=new Map();let wins=0,draws=0,losses=0,unfinished=0;
 for(const g of games){if(!g.completed){unfinished++;continue;}const value=g.winner===0?.5:g.winner===g.candidateColor?1:0;if(value===1)wins++;else if(value===0)losses++;else draws++;const key=g.pairId;const rows=groups.get(key)||[];rows.push({game:g,value});groups.set(key,rows);}
 for(const rows of groups.values()){if(rows.length!==2||new Set(rows.map(x=>x.game.candidateFirst)).size!==2)continue;const family=rows[0].game.familyId,a=families.get(family)||[];a.push((rows[0].value+rows[1].value)/2);families.set(family,a);}
 const values=[...families.values()].map(a=>a.reduce((x,y)=>x+y,0)/a.length),n=values.length,mean=n?values.reduce((x,y)=>x+y,0)/n:null;
 // Independent source/opening families, not games or symmetry variants, are
 // the bounded observations. Alpha spending protects repeated promotions.
 const alpha=(1-confidence)/(Math.max(1,trial)*(Math.max(1,trial)+1)),radius=n?Math.sqrt(Math.log(1/alpha)/(2*n)):1,lower=n?Math.max(0,mean-radius):0;
 return {wins,draws,losses,unfinished,completedGames:wins+draws+losses,completedPairs:[...groups.values()].filter(a=>a.length===2&&new Set(a.map(x=>x.game.candidateFirst)).size===2).length,independentFamilies:n,meanScore:mean,lowerConfidenceBound:lower,alpha,minPairs,passed:n>=minPairs&&lower>.5,method:'one-sided Hoeffding bound on family-averaged paired scores with alpha spending',scope:'Improvement only against the recorded opponent, openings and move budget; not a universal strength claim'};
}
const openingFamily=start=>'family-'+hash(familyFor(start.events.slice(0,4),start.firstPlayer)).slice(0,24);
function plan(context,model,trained=new Set(),trainedFamilies=new Set()){
 const prior=read(path.join(context.dir,'champion.json')),seen=new Set(),positions=[];let serial=0;
 while(positions.length<context.settings.pairs){let start;
  start=opening(context.settings.seed+100000003+context.state.cycle*100003+serial*1237,4+serial%3);start.source='reserved-evaluation-opening';
  serial++;if(serial>1000000)throw Error('Unable to find independent evaluation openings');const stem=openingFamily(start);if(seen.has(stem)||trainedFamilies.has(stem)||trainedFamilies.has(start.familyId)||trained.has(positionKey(start.board,start.p,start.firstPlayer)))continue;start.familyId=stem;seen.add(stem);positions.push(start);
 }
 const opponents=prior?['baseline','incumbent']:['baseline'],games=[];for(const opponent of opponents)positions.forEach((pos,k)=>{for(const candidateFirst of [true,false])games.push({id:opponent+'-'+k+'-'+(candidateFirst?'first':'second'),pairId:opponent+'-'+k,familyId:pos.familyId,source:pos.source,opponent,candidateFirst,candidateColor:candidateFirst?pos.firstPlayer:3-pos.firstPlayer,firstPlayer:pos.firstPlayer,board:pos.board.slice(),p:pos.p,opening:pos.events,events:[],completed:false,winner:null,elapsedMs:0});});
 return {schemaVersion:1,candidateHash:hash(model),candidateModelId:model.modelId,baselineCommit:context.state.baselineCommit,incumbentHash:prior?hash(prior):null,incumbent:prior,identity:sourceIdentity(),rulesId:context.state.rulesId,lessons:require('./generate.cjs').lessonsFor(context),lessonHash:hash(require('./generate.cjs').lessonsFor(context)),datasetSha256:context.state.dataset?.sha256,settingsHash:hash({validationMs:context.settings.validationMs,pairs:context.settings.pairs,minPairs:context.settings.minPairs,confidence:context.settings.confidence}),moveMs:context.settings.validationMs,pairs:context.settings.pairs,trial:++context.state.trial,games,startedAt:new Date().toISOString()};
}
async function validate(context,{deadline=Infinity,modelPath=path.join(context.dir,'candidate.json')}={}){
 const model=read(modelPath);if(!model)throw Error('No candidate model; run training first');neural().validate(model);const file=path.join(context.dir,'arena-cycle-'+context.state.cycle+'.json');let state=read(file);
 if(state){if(state.candidateHash!==hash(model)||state.moveMs!==context.settings.validationMs||state.pairs!==context.settings.pairs)throw Error('Candidate or evaluation settings changed; use a new cycle/run');}
 else{const trained=new Set(),trainedFamilies=new Set(),data=path.join(context.dir,'datasets/cycle-'+(context.state.cycle||1)+'.jsonl');if(fs.existsSync(data)){const input=readline.createInterface({input:fs.createReadStream(data),crlfDelay:Infinity});for await(const line of input)if(line.trim()){const row=JSON.parse(line);if(row.split==='train'){trainedFamilies.add(row.familyId);if(row.positionKey)trained.add(row.positionKey);}}}const gameFile=path.join(context.dir,'games.jsonl');if(fs.existsSync(gameFile)){const input=readline.createInterface({input:fs.createReadStream(gameFile),crlfDelay:Infinity});for await(const line of input)if(line.trim()){const game=JSON.parse(line);if(game.split==='train'&&game.opening?.length>=4)trainedFamilies.add(openingFamily({events:game.opening,firstPlayer:game.firstPlayer}));}}state=plan(context,model,trained,trainedFamilies);state.trainingPositionCount=trained.size;state.trainingFamilyCount=trainedFamilies.size;state.startPositionsDisjointFromTraining=true;atomic(file,state);save(context);}
 const baseline=baselineFactory(context.state.baselineCommit);state.rules=rulesAudit(model,baseline.createEngine);state.parity=parity(model,read(modelPath+'.parity.json'));
 for(const game of state.games){if(game.completed||game.exhausted)continue;if(stopped(context.dir)||Date.now()>=deadline)break;
  const challenger=current({firstPlayer:game.firstPlayer,optimized:true,model}),opponent=game.opponent==='baseline'?baseline.createEngine({firstPlayer:game.firstPlayer,optimized:true}):current({firstPlayer:game.firstPlayer,optimized:true,model:state.incumbent});
  while(!game.completed){const ending=outcome(challenger,game.board);if(ending){Object.assign(game,ending);break;}if(stopped(context.dir)||Date.now()+state.moveMs>=deadline){game.reason=stopped(context.dir)?'user-stop':'time-limit';break;}if(game.events.length>=225){game.reason='ply-limit';break;}
   const E=game.p===game.candidateColor?challenger:opponent,legal=legalMoves(E,game.board,game.p);if(!legal.length){game.reason='no-legal-move';break;}
   const started=performance.now(),r=E.analyze(game.board,game.p,state.moveMs,state.lessons||[]),elapsed=performance.now()-started;if(r.i==null||!E.inspect(game.board,r.i,game.p).legal){game.invalid='illegal-or-missing-recommendation';game.reason=game.invalid;break;}
   const shape=E.inspect(game.board,r.i,game.p);game.events.push({type:'move',p:game.p,i:r.i,coord:coord(r.i),engine:game.p===game.candidateColor?'candidate':game.opponent,elapsedMs:elapsed,depth:r.depth,nodes:r.nodes,proofStatus:r.proofStatus});game.elapsedMs+=elapsed;game.board[r.i]=game.p;game.p=3-game.p;if(shape.win.length){game.completed=true;game.winner=3-game.p;game.reason='played-exact-five';}
   context.state.progress={gameId:game.id,ply:game.events.length,completed:state.games.filter(x=>x.completed).length,total:state.games.length};atomic(file,state);save(context);await new Promise(resolve=>setImmediate(resolve));
  }
  // Independently replay all actually played turns; proof flags never adjudicate.
  try{const checked=replay({id:game.id,first:game.firstPlayer,events:[...game.opening,...game.events]});if(game.completed&&(!checked.completed||(checked.draw?0:checked.winner)!==game.winner))game.invalid='terminal-replay-mismatch';}catch(e){game.invalid=e.message;}
  if(['no-legal-move','ply-limit','illegal-or-missing-recommendation'].includes(game.reason)||game.invalid)game.exhausted=true;
  atomic(file,state);
 }
 const stats={};for(const opponent of [...new Set(state.games.map(g=>g.opponent))])stats[opponent]=pairedStats(state.games.filter(g=>g.opponent===opponent),{minPairs:context.settings.minPairs,confidence:context.settings.confidence,trial:state.trial});
 const training=read(modelPath+'.training.json'),trainingCheck=trainingEvidence(model,training,state.datasetSha256),invalid=state.games.filter(g=>g.invalid),complete=state.games.every(g=>g.completed||g.exhausted),passed=complete&&state.games.every(g=>g.completed)&&!invalid.length&&state.rules.passed&&state.parity.passed&&trainingCheck.passed&&Object.values(stats).every(x=>x.passed);
 Object.assign(state,{stats,summary:stats.baseline,complete,passed,invalidGames:invalid.map(g=>({id:g.id,error:g.invalid})),trainingEvidence:training,trainingCheck,finishedAt:complete?new Date().toISOString():null,rejectionReasons:[...(!state.games.every(g=>g.completed)?['evaluation games unfinished']:[]),...(!state.rules.passed?['rule/tactical audit failed']:[]),...(!state.parity.passed?['JS/Python model parity missing or failed']:[]),...trainingCheck.errors,...(invalid.length?['invalid played game']:[]),...Object.entries(stats).filter(([,s])=>!s.passed).map(([name])=>'conservative strength threshold not met against '+name)]});atomic(file,state);atomic(path.join(context.dir,'arena.json'),state);context.state.validation={cycle:context.state.cycle,candidateHash:state.candidateHash,passed,complete,stats,rejectionReasons:state.rejectionReasons};save(context);return state;
}
module.exports={parity,trainingEvidence,rulesAudit,pairedStats,openingFamily,plan,validate};
