'use strict';
const $=id=>document.getElementById(id);
let session=null,selectedId='',selectedRun=null,record=null,recordName='',busy=false,sourceTouched=false;
const accumulationKeys=['gamesPerCycle','minNewSamples','maxTrainingSamples','recordBranchFraction'];
const phases={ready:'실험 준비',import:'CPU 기보 복원',analyze:'CPU 기보와 대안 분석',analysis:'CPU 기보와 대안 분석',generate:'CPU 자료 생성 · 자가대국',snapshot:'학습 자료 고정 · 표본 선택',train:'GPU 모델 학습',validate:'CPU 대국 검증 · 흑백 교환',adopt:'채택 기준 확인',created:'실험 준비',complete:'실험 완료'};
const statuses={created:'준비',running:'진행 중',stopped:'중단됨',complete:'완료',completed:'완료',failed:'오류',pending:'대기'};
function statusOf(run){return run?.active?'running':run?.state?.status==='running'?'stopped':run?.state?.status||'created';}
function notice(text){$('notice').textContent=text||'';}
async function api(route,body){const response=await fetch(route,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json','X-Omok-Session':session.token}:{},body:body?JSON.stringify(body):undefined});const value=await response.json();if(!response.ok)throw Error(value.error||'요청에 실패했습니다.');return value;}
function setSource(){const id=$('fromRun').value;$('sourceInfo').textContent=id?'선택한 '+id+'의 완료 대국과 학습 자료를 새 실험으로 이어받습니다. 원본은 보존하고 미완료 대국은 승패 정답으로 쓰지 않습니다.':'기존 내장 기보와 새 자가대국으로 시작합니다. 이전 경험을 이어받으려면 저장된 실험을 선택하세요.';$('startButton').textContent=id?'저장된 경험을 이어받아 실행':'새 경험 누적 시작';}
function setPreset(){const preset=session?.presets[$('preset').value];if(!preset)return;for(const key of ['minutes','games','pairs','epochs','workers'])$(key).value=preset[key];for(const key of accumulationKeys)$(key).value=preset[key]??session.presets.continuous[key];const continuous=!!preset.continuous; $('concurrentTraining').checked=!!preset.concurrentTraining; $('concurrentTraining').disabled=!continuous;$('gamesField').hidden=continuous;$('games').disabled=continuous;for(const key of accumulationKeys)$(key).disabled=!continuous;$('modeInfo').textContent=continuous?'총 대국 수 상한 없이 경험을 누적합니다. 이번 실행 시간이 되면 자동 저장 후 멈추며, 다음에는 같은 실험을 재개합니다.':'정한 누적 대국 수를 채우면 완료됩니다. 실행 시간에 먼저 도달하면 저장한 지점에서 재개할 수 있습니다.';}
function download(id,kind,available){const element=$(kind+'Download');element.hidden=!available;element.href='/api/download?id='+encodeURIComponent(id)+'&kind='+kind;}
function number(value){return Number.isFinite(Number(value))?Number(value).toLocaleString('ko-KR'):'—';}
function lastAdoption(state){const history=[...(state?.adoptions||[]),...(state?.adoptionHistory||[]),...(state?.decisions||[])];return history.sort((a,b)=>String(a.at||'').localeCompare(String(b.at||''))).at(-1)||state?.adoption||null;}
function bytes(value){if(!Number.isFinite(value)||value<0)return '기록 없음';const units=['B','KiB','MiB','GiB','TiB'];let unit=0;while(value>=1024&&unit<units.length-1){value/=1024;unit++;}return value.toLocaleString('ko-KR',{maximumFractionDigits:unit?2:0})+' '+units[unit];}
function monitorElements(){
  if(!$('diskUsage')){const block=document.createElement('div');block.className='storage-monitor';for(const [tag,id,text] of [['h3',null,'저장 공간과 파생 자료 보존'],['p','diskUsage','저장 공간 점검 기록이 아직 없습니다.'],['p','retentionInfo','']]){const element=document.createElement(tag);if(id)element.id=id;element.textContent=text;block.append(element);}$('resourceInfo').after(block);}
  if(!$('candidateHistory')){const block=document.createElement('div');block.className='result-block candidate-monitor';const title=document.createElement('h3');title.textContent='최근 후보 변화';const hint=document.createElement('p');hint.className='hint';hint.textContent='최근 8개 기록 · 미완료 검증 점수는 대기합니다. 서로 다른 학습 자료의 MSE와 실제 대국 실력은 별도로 확인합니다.';const list=document.createElement('ol');list.id='candidateHistory';list.className='candidate-history';block.append(title,hint,list);$('validation').parentElement.after(block);}
}
function renderMonitors(run){
  monitorElements();const storage=run?.storage,retention=storage?.retention;
  $('diskUsage').textContent=storage?['사용 '+bytes(storage.usedBytes),'다음 쓰기 예약 '+bytes(storage.reservedBytes),'진행 작업 예약 '+bytes(storage.heldBytes),'상한 '+bytes(storage.limitBytes),storage.checkedAt?'점검 '+storage.checkedAt:'점검 시각 기록 없음',storage.stoppedForBudget?'저장 공간 예산으로 중단':''].filter(Boolean).join(' · '):'저장 공간 점검 기록이 아직 없습니다.';
  $('diskUsage').className=storage?.stoppedForBudget?'storage-warning':'';
  $('retentionInfo').textContent=retention?'파생 snapshot 기본 최근 '+number(retention.maxDerivedCycles)+'회 보관 · '+(retention.records.length?'최근 정리 완료 '+number(retention.completed)+'회 · 복구 대기 '+number(retention.pending)+'회'+(retention.records[0]?' · 마지막 cycle '+retention.records[0].cycle+' '+({completed:'정리 완료',prepared:'중단 후 정리 대기',legacy:'이전 정리 기록'}[retention.records[0].status]||'기록 확인'):'')+(retention.truncated?' · 최근 기록만 표시':''):'아직 파생 자료 정리 기록 없음')+' · 현재 자료와 채택 모델의 자료는 추가 보존':'';
  const list=$('candidateHistory'),rows=(run?.candidateHistory?.rows||[]).slice(0,8);list.replaceChildren();if(!rows.length){const item=document.createElement('li');item.textContent='후보 기록이 아직 없습니다.';list.append(item);return;}
  rows.forEach((row,index)=>{const item=document.createElement('li'),title=document.createElement('strong');title.textContent='cycle '+(row.cycle??'기록 없음')+' / trial '+(row.trial??'대기');const metric=document.createElement('p');metric.textContent='분리 검증 MSE '+(Number.isFinite(row.validationMse)?row.validationMse.toFixed(5):'기록 없음');const score=document.createElement('p');
    if(row.status==='complete'&&row.complete){const values=Object.entries(row.stats||{}).map(([control,stats])=>{const prior=rows.slice(index+1).find(previous=>previous.complete&&previous.status==='complete'&&row.controlIdentity?.[control]&&previous.controlIdentity?.[control]===row.controlIdentity[control]&&['sourceHash','harnessHash','runtimeHash'].every(key=>row.identity?.[key]&&row.identity[key]===previous.identity?.[key])&&Number.isFinite(previous.stats?.[control]?.meanScore)),change=prior?100*(stats.meanScore-prior.stats[control].meanScore):null;return control+' '+(100*stats.meanScore).toFixed(2)+'%'+(change!==null?' (전 기록 대비 '+(change>0?'+':'')+change.toFixed(2)+'%p)':'');});score.textContent=values.length?'완료 검증 · '+values.join(' · '):'완료 검증 · 대조군 점수 기록 없음';}
    else score.textContent=row.status==='invalid'?'검증 기록에 무효 대국이 있어 점수를 표시하지 않습니다.':row.status==='summary-unavailable'?'검증 요약 기록을 읽지 못했습니다.':row.status==='identity-unavailable'?'완료 기록의 모델·실행 식별자가 부족해 점수를 표시하지 않습니다.':'검증 대기 · 미완료 점수는 표시하지 않습니다.';
    const identity=document.createElement('details'),label=document.createElement('summary'),text=document.createElement('p');label.textContent='모델·실행 식별자';text.textContent=['모델 '+(row.candidateModelId||'기록 없음'),'후보 hash '+(row.candidateHash||'기록 없음'),'source '+(row.identity?.sourceHash||'기록 없음'),'harness '+(row.identity?.harnessHash||'기록 없음'),'runtime '+(row.identity?.runtimeHash||'기록 없음'),'자료 '+(row.datasetSha256||'기록 없음'),'수읽기 예산 '+(Number.isFinite(row.moveMs)?row.moveMs+' ms':'기록 없음'),'완료 시각 '+(row.finishedAt||'기록 없음')].join(' · ');identity.append(label,text);item.append(title,metric,score,identity);list.append(item);
  });
}
function renderSelected(run){
  selectedRun=run;
  renderMonitors(run);
  const state=run?.state||{},count=state.counters||{},training=run?.training||state.training||{},metadata=run?.candidate?.training||{},gpu=training.gpuMetrics||training.gpu||training.metrics||(typeof training.device==='object'?training.device:training),arena=run?.arena||{},selected=!!run;
  const running=!!run?.active,status=statusOf(run);$('stateBadge').textContent=selected?statuses[status]||status:'대기';$('stateBadge').className='badge '+status;
  $('phase').textContent=selected?(phases[state.phase]||state.phase||'실험 준비'):'기보를 넣으면 분석부터 검증까지 이어서 실행합니다.';
  $('message').textContent=state.message||state.error||state.errors?.at?.(-1)?.message||'';
  $('completedGames').textContent=number(count.completedGames??0);$('samples').textContent=number(count.samples??metadata.trainSamples??0);$('updates').textContent=number(count.trainingUpdates??metadata.updates??gpu.updates??0);$('families').textContent=number(count.families??state.dataset?.families??0);
  $('uniquePositions').textContent=Number.isFinite(count.uniquePositions)?'고유 국면 '+number(count.uniquePositions)+'개':'고유 국면 집계 전';
  const overlap=state.concurrency?.training&&state.concurrency?.generation;$('resourceInfo').textContent=selected?'CPU 대국 작업 '+number(run.settings?.workers??state.resources?.workers??1)+'개 · '+(state.resources?.applied&&state.resources?.priority==='below-normal'?'낮은 우선순위 적용':'우선순위 기록 확인 전')+(state.phase==='validate'?' · 검증 병렬 작업 '+number(state.progress?.workers??run.settings?.workers??1)+'개 · 동시 진행 '+number(state.progress?.activeGames??0)+'대국 · 검증 완료 '+number(state.progress?.completed??0)+' / '+number(state.progress?.total??0):overlap?' · GPU 학습과 CPU 자료 생성 동시 진행':run.settings?.concurrentTraining?' · 학습 중 다음 대국 생성 사용':''):''; const savedGate=state.trainingGate,cutoff=overlap?state.concurrency?.trainedThroughSamples:state.lastTrainingSampleCount??state.concurrency?.trainedThroughSamples;const gate=savedGate&&Number.isFinite(cutoff)&&Number.isFinite(count.samples)?{...savedGate,newSamples:Math.max(0,count.samples-cutoff),ready:count.samples-cutoff>=savedGate.minNewSamples}:savedGate;$('gate').textContent=gate?'다음 학습을 위한 새 표본 '+number(gate.newSamples)+' / '+number(gate.minNewSamples)+(gate.ready?' · 학습 조건 충족':' · CPU가 새 경험을 모으는 중'):'새 자료가 충분히 쌓이면 학습합니다.';
  if(state.phase==='snapshot')$('gate').textContent='누적 경험에서 이번 학습의 표본을 선택하고 고정하는 중입니다.';
  $('experienceInfo').textContent=selected?(run.settings?.continuous?'연속 누적 · 총 대국 수 상한 없음':'정해진 대국 수로 실행')+' · 이 실험의 경험은 중단 후에도 보존됩니다.':'';
  const elapsedMs=state.lastRun?.elapsedMs??state.timing?.elapsedMs??state.timing?.totalElapsedMs??state.elapsedMs??(Array.isArray(state.timing)?state.timing.reduce((sum,row)=>sum+(row.includedInPhase?0:row.elapsedMs||0),0):Array.isArray(state.timings)?state.timings.reduce((sum,row)=>sum+(row.includedInPhase?0:row.elapsedMs||0),0):undefined);$('elapsed').textContent=Number.isFinite(elapsedMs)?Math.round(elapsedMs/1000)+'초':'—';
  const completed=['complete','completed'].includes(status);$('stopButton').disabled=busy||!running||run.stopRequested;$('resumeButton').disabled=busy||!selected||!!session.activeId||running||completed;$('continueButton').disabled=busy||!selected||!!session.activeId||running;$('startButton').disabled=busy||!!session.activeId;$('stopping').hidden=!run?.stopRequested||!running;
  $('resumeInfo').textContent=selected?(completed?'이 실험은 목표를 채워 완료되었습니다. 더 쌓으려면 ‘이 경험을 이어서 누적’을 누르세요.':'재개는 같은 실험과 설정을 이어갑니다. 다른 버전의 실험은 보관된 실행기로 재개합니다.'):'';
  const trainedOnCuda=gpu.trainedOnCuda??training.trainedOnCuda??metadata.device?.startsWith?.('cuda');
  $('gpu').textContent=run?.candidate?(trainedOnCuda?'GPU 학습 완료':'학습 모델 생성 · GPU 실행 여부는 기록에서 확인')+(gpu.name?' · '+gpu.name:''):'학습 결과가 아직 없습니다.';
  $('training').textContent=run?.candidate?['학습 국면 '+number(metadata.trainSamples??training.trainSamples),metadata.validationMse!=null?'분리 검증 오차 '+Number(metadata.validationMse).toFixed(5):'',gpu.elapsedSeconds!=null?'학습 '+Number(gpu.elapsedSeconds).toFixed(1)+'초':'',gpu.samplesPerSecond!=null?'초당 '+number(Math.round(gpu.samplesPerSecond))+'국면':''].filter(Boolean).join(' · '):'';
  const adoption=lastAdoption(state)||run?.adoption,accepted=!!run?.champion;
  $('adoption').textContent=adoption?.decision==='insufficient-evidence'?'검증이 충분하지 않아 이번 후보를 채택하지 않았습니다. 기존 엔진을 유지합니다.':adoption&&(adoption.adopted===false||adoption.accepted===false)?'새 후보가 채택 기준에 미달하여 기존 엔진을 유지합니다.':accepted?'검증을 통과한 모델이 저장됐습니다. 오목 HTML에 반영된 후 파일을 다시 열면 사용됩니다.':adoption?'채택 기준에 미달하여 기존 엔진을 유지합니다.':'검증 전입니다. 기존 엔진을 유지합니다.';
  const scoresVisible=arena.complete===true&&arena.identityVerified===true,result=scoresVisible?(arena.summary||arena.stats?.baseline||{}):{},details=[];
  if(arena.unavailable)details.push('검증 요약을 읽지 못했습니다. 원본 결과를 내려받아 확인하세요.');
  else if(run?.arena){const earlier=(arena.candidateHash&&run.candidate?.hash&&arena.candidateHash!==run.candidate.hash)||(arena.candidateModelId&&run.candidate?.modelId&&arena.candidateModelId!==run.candidate.modelId);details.push((earlier?'이전 후보의 검증':'검증 결과')+' · cycle '+(arena.cycle??state.validation?.cycle??'기록 없음')+' / trial '+(arena.trial??'기록 없음')+' · 모델 '+(arena.candidateModelId??'기록 없음')+' · hash '+(arena.candidateHash?.slice(0,12)??'기록 없음'));if(arena.finishedAt)details.push('완료 '+arena.finishedAt);}
  if(run?.arena&&!arena.unavailable&&!scoresVisible)details.push(arena.evaluationInvalid?'무효 대국이 포함된 검증 · 점수 표시 대기':arena.complete?'모델·실행 식별자 기록이 부족해 점수 표시 대기':'미완료 검증 · 점수 표시 대기');
  if(result.meanScore!=null)details.push('점수 '+(100*result.meanScore).toFixed(2)+'%');if(result.independentFamilies!=null)details.push('독립 가족 '+number(result.independentFamilies));
  if(arena.planning?.requiredMeanStrictlyGreaterThan!=null)details.push('통과에 필요한 점수 >'+(100*arena.planning.requiredMeanStrictlyGreaterThan).toFixed(2)+'%');
  if(arena.planning?.independentFamilies!=null)details.push('예정 독립 가족 '+number(arena.planning.independentFamilies));
  for(const [opponent,stats] of Object.entries(scoresVisible?arena.stats||{}:{}))if(opponent!=='baseline')details.push(opponent+' 점수 '+(100*(stats.meanScore??0)).toFixed(2)+'%, 가족 '+number(stats.independentFamilies)+', 하한 '+(100*(stats.lowerConfidenceBound??0)).toFixed(2)+'%');
  if(result.wins!=null)details.push('승 '+number(result.wins));if(result.losses!=null)details.push('패 '+number(result.losses));if(result.draws!=null)details.push('무 '+number(result.draws));if(result.unfinished!=null)details.push('미완료 '+number(result.unfinished));if(result.completedGames!=null)details.push('완료 '+number(result.completedGames)+'대국');if(result.completedPairs!=null)details.push('흑백 '+number(result.completedPairs)+'쌍');if(result.lowerConfidenceBound!=null)details.push('점수 신뢰하한 '+(100*result.lowerConfidenceBound).toFixed(1)+'%');if(arena.reason||adoption?.reason)details.push(arena.reason||adoption.reason);
  $('validation').textContent=details.join(' · ');for(const kind of ['champion','candidate','arena'])download(run?.id||'',kind,kind==='champion'?accepted:kind==='candidate'?!!run?.candidate:!!run?.arena);
  $('log').textContent=run?.log||'기록이 아직 없습니다.';
}
async function refresh(){if(!session)return;try{const result=await api('/api/status'+(selectedId?'?id='+encodeURIComponent(selectedId):''));session.activeId=result.activeId;
  if(!selectedId)selectedId=result.activeId||result.runs[0]?.id||'';
  const old=$('runs').value;$('runs').replaceChildren();if(!result.runs.length){const option=document.createElement('option');option.value='';option.textContent='아직 실험이 없습니다';$('runs').append(option);}for(const run of result.runs){const option=document.createElement('option');option.value=run.id;option.textContent=run.id+' · '+(statuses[statusOf(run)]||statusOf(run));$('runs').append(option);}$('runs').value=selectedId||old;
  const source=$('fromRun').value;$('fromRun').replaceChildren();const fresh=document.createElement('option');fresh.value='';fresh.textContent='새 경험 저장소 · 기존 내장 기보부터';$('fromRun').append(fresh);const saved=result.runs.filter(run=>!run.active&&['complete','completed','stopped','failed'].includes(run.state?.status));for(const run of saved){const option=document.createElement('option');option.value=run.id;option.textContent=run.id+' · 완료 '+number(run.state?.counters?.completedGames??0)+'대국';$('fromRun').append(option);}if(!sourceTouched){$('fromRun').value=saved.some(run=>run.id===selectedId)?selectedId:saved[0]?.id||'';}else $('fromRun').value=saved.some(run=>run.id===source)?source:'';setSource();
  if(result.selected?.id===selectedId)renderSelected(result.selected);else if(selectedId){const detail=await api('/api/status?id='+encodeURIComponent(selectedId));renderSelected(detail.selected);}else renderSelected(null);
  }catch(error){notice(error.message);}}
$('preset').addEventListener('change',setPreset);
$('fromRun').addEventListener('change',()=>{sourceTouched=true;setSource();});
$('runs').addEventListener('change',()=>{selectedId=$('runs').value;refresh();});
$('recordFile').addEventListener('change',async()=>{const file=$('recordFile').files[0];if(!file){record=null;recordName='';return;}try{if(file.size>2*1024*1024)throw Error('2 MiB 이하의 기보를 선택해 주세요.');const text=await file.text();const parsed=JSON.parse(text);if(!parsed||typeof parsed!=='object')throw Error('기보는 JSON 객체 또는 배열이어야 합니다.');record=parsed;recordName=file.name;$('recordInfo').textContent=file.name+' · '+number(file.size)+'바이트';notice('');}catch(error){record=null;$('recordInfo').textContent='기보를 읽지 못했습니다.';notice(error.message);}});
$('startForm').addEventListener('submit',async event=>{event.preventDefault();if(busy||!session)return;busy=true;$('startButton').disabled=true;notice('');try{let input=record;if($('recordText').value.trim())input=JSON.parse($('recordText').value);const continuous=!!session.presets[$('preset').value].continuous,config={};for(const key of ['minutes','pairs','epochs','workers',...(continuous?accumulationKeys:['games'])])config[key]=Number($(key).value);config.continuous=continuous;config.concurrentTraining=continuous&&$('concurrentTraining').checked;const fromRun=$('fromRun').value,result=await api('/api/start',{record:input,recordName:recordName||'붙여넣은 기보.json',preset:$('preset').value,config,fromRun});selectedId=result.id;session.activeId=result.id;sourceTouched=false;notice(fromRun?'저장된 경험을 보존하여 이어받는 실행을 시작했습니다.':'새 경험 저장소에서 실행을 시작했습니다.');await refresh();}catch(error){notice(error.message);}finally{busy=false;await refresh();}});
$('stopButton').addEventListener('click',async()=>{if(!selectedId)return;try{await api('/api/stop',{id:selectedId});notice('중단을 요청했습니다. 현재 작업을 마치고 저장한 뒤 멈춥니다.');await refresh();}catch(error){notice(error.message);}});
$('resumeButton').addEventListener('click',async()=>{if(!selectedId)return;try{await api('/api/resume',{id:selectedId});session.activeId=selectedId;notice('저장한 진행 상태에서 재개했습니다.');await refresh();}catch(error){notice(error.message);}});
$('continueButton').addEventListener('click',()=>{if(!selectedRun||session.activeId)return;$('fromRun').value=selectedRun.id;sourceTouched=true;$('preset').value='continuous';setPreset();setSource();notice('선택한 경험을 이어받도록 준비했습니다. 왼쪽의 실행 버튼을 누르면 새 버전의 연속 누적을 시작합니다.');$('startForm').scrollIntoView({behavior:'smooth',block:'start'});});
api('/api/session').then(value=>{session=value;setPreset();return refresh();}).catch(error=>notice(error.message));
setInterval(refresh,2000);
