'use strict';
// Staged bytes and execution identity form one durable transaction. A changed
// runtime or interrupted rollback restores every prior destination before use.
const fs=require('node:fs'),path=require('node:path'),S=require('./state.cjs');
const identityKeys=['sourceHash','harnessHash','runtimeHash'];
function paths(root){return {dir:path.join(root,'work/local-learning-20261007/deployment'),delivery:path.resolve(root,'../../outputs')};}
function permitted(root,file){if(typeof file!=='string'||path.resolve(file)!==file)return false;const rel=path.relative(root,file),delivery=paths(root).delivery;return (!rel.startsWith('..'+path.sep)&&rel!=='..'&&!path.isAbsolute(rel))||[path.join(delivery,'omok.html'),path.join(delivery,'omok-gpu.html')].includes(file);}
function stagedPath(root,file){if(typeof file!=='string'||path.resolve(file)!==file)return false;const rel=path.relative(path.join(root,'work'),file);return rel!==''&&rel!=='..'&&!rel.startsWith('..'+path.sep)&&!path.isAbsolute(rel);}
function executionIdentity(provider){const value=provider(),identity=Object.fromEntries(identityKeys.map(key=>[key,value?.[key]]));if(identityKeys.some(key=>!/^[a-f0-9]{64}$/.test(identity[key]||'')))throw Error('Invalid deployment execution identity');return identity;}
function sameIdentity(a,b){return identityKeys.every(key=>a?.[key]===b?.[key]);}
function copyChecked(source,file,sha256){fs.mkdirSync(path.dirname(file),{recursive:true});const temporary=file+'.tmp-'+process.pid;fs.copyFileSync(source,temporary);if(S.fileHash(temporary)!==sha256)throw Error('Deployment source bytes changed during durable copy');const fd=fs.openSync(temporary,'r+');try{fs.fsyncSync(fd);}finally{fs.closeSync(fd);}for(let attempt=0;;attempt++){try{fs.renameSync(temporary,file);S.syncDirectory(path.dirname(file));return;}catch(error){if(!['EPERM','EACCES','EBUSY'].includes(error.code)||attempt>=11)throw error;Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0,Math.min(100,10*(attempt+1)));}}}
function verify(root,intent){
 if(intent.schemaVersion!==2||intent.root!==root||!Array.isArray(intent.targets)||!intent.targets.length||identityKeys.some(key=>!/^[a-f0-9]{64}$/.test(intent.identity?.[key]||'')))throw Error('Invalid deployment intent or missing execution identity; preserve it for investigation');
 const seen=new Set();for(const row of intent.targets){if(!permitted(root,row.file)||seen.has(row.file)||!stagedPath(root,row.staged)||!stagedPath(root,row.backup)||typeof row.existed!=='boolean'||!/^[a-f0-9]{64}$/.test(row.sha256||'')||row.existed&&!/^[a-f0-9]{64}$/.test(row.backupSha256||''))throw Error('Deployment staging/backup identity or path mismatch');seen.add(row.file);}
}
function verifyStaged(intent){for(const row of intent.targets)if(!fs.existsSync(row.staged)||S.fileHash(row.staged)!==row.sha256)throw Error('Deployment staged bytes are missing or changed; preserve them for investigation');}
function verifyBackups(intent){for(const row of intent.targets)if(row.existed&&(!fs.existsSync(row.backup)||S.fileHash(row.backup)!==row.backupSha256))throw Error('Deployment rollback backup is missing or changed; preserve it for investigation');}
function rollback(root,intent,{reason=intent.rollbackReason||'delivery-error',onRollback=()=>{}}={}){
 verify(root,intent);verifyBackups(intent);const file=path.join(paths(root).dir,'transaction.json');
 intent.status='rolling-back';intent.rollbackReason=reason;S.atomic(file,intent);
 for(const [n,row] of intent.targets.entries()){if(row.existed){if(S.fileHash(row.backup)!==row.backupSha256)throw Error('Deployment rollback backup changed during restoration');copyChecked(row.backup,row.file,row.backupSha256);}else if(fs.existsSync(row.file)){fs.unlinkSync(row.file);S.syncDirectory(path.dirname(row.file));}onRollback(row.file,n);}
 intent.status='rolled-back';intent.completedAt=new Date().toISOString();S.atomic(file,intent);return {rolledBack:true,reason,transactionId:intent.transactionId};
}
function publish(root,intent,{identityProvider=S.sourceIdentity,onPublish=()=>{}}={}){
 verify(root,intent);verifyStaged(intent);
 const assertExecution=()=>{if(!sameIdentity(intent.identity,executionIdentity(identityProvider)))throw Error('Deployment engine/harness/runtime changed after evaluation or staging');};assertExecution();
 for(const [n,row] of intent.targets.entries()){copyChecked(row.staged,row.file,row.sha256);onPublish(row.file,n);assertExecution();}
 intent.status='committed';intent.completedAt=new Date().toISOString();S.atomic(path.join(paths(root).dir,'transaction.json'),intent);return intent.delivery;
}
function recoverDeployment({root=S.ROOT,identityProvider=S.sourceIdentity,onRollback=()=>{}}={}){
 root=path.resolve(root);const {dir}=paths(root),file=path.join(dir,'transaction.json'),intent=S.read(file);if(!intent||!['prepared','rolling-back'].includes(intent.status))return null;
 const lock=S.read(path.join(dir,'runner.lock'));if(lock?.pid&&lock.pid!==process.pid){let alive=false;try{process.kill(lock.pid,0);alive=true;}catch{}if(alive)throw Error('Model deployment is in progress; retry after it completes');}
 const release=S.lock(dir);try{verify(root,intent);if(intent.status==='rolling-back')return rollback(root,intent,{onRollback});
  let current;try{current=executionIdentity(identityProvider);}catch(error){rollback(root,intent,{reason:'execution-identity-unavailable: '+error.message,onRollback});throw Error('Pending deployment execution identity is unavailable; prior model/artifacts/run adoption state restored: '+error.message);}
  if(!sameIdentity(intent.identity,current)){rollback(root,intent,{reason:'execution-identity-changed',onRollback});throw Error('Pending deployment engine/harness/runtime changed; prior model/artifacts/run adoption state restored. Fresh evaluation is required.');}
  try{return publish(root,intent,{identityProvider});}catch(error){rollback(root,intent,{reason:error.message,onRollback});throw Error('Pending deployment failed and prior model/artifacts/run adoption state restored: '+error.message);}
 }finally{release();}
}
function deploy(accepted,{root=S.ROOT,stageId,incumbentHash=null,build,onPublish=()=>{},onRollback=()=>{},identityProvider=S.sourceIdentity,context,entry}={}){
 require('../../src/neural-evaluator.js').validate(accepted);if(accepted.adoption?.accepted!==true)throw Error('Only accepted models may enter the deployment transaction');root=path.resolve(root);if(root!==S.ROOT&&!root.startsWith(path.join(S.ROOT,'work')+path.sep))throw Error('Test deployment root must stay inside the repository work directory');if(!/^[A-Za-z0-9._-]{1,120}$/.test(stageId)||stageId==='.'||stageId==='..')throw Error('Invalid deployment stage identifier');recoverDeployment({root,identityProvider,onRollback});
 const {dir,delivery}=paths(root),release=S.lock(dir),stage=path.join(root,'work/local-learning-20261007/adoption-stage',stageId),active=path.join(root,'src/active-model.json'),htmlFiles=[path.join(root,'outputs/omok.html'),path.join(root,'outputs/omok-gpu.html'),path.join(root,'dist/index.html'),path.join(delivery,'omok.html'),path.join(delivery,'omok-gpu.html')];let intent;
 try{const identity=executionIdentity(identityProvider);for(const key of identityKeys)if(accepted.adoption[key]!=null&&accepted.adoption[key]!==identity[key])throw Error('Accepted model evaluation '+key+' differs from deployment execution');
  fs.mkdirSync(stage,{recursive:true});const modelFile=path.join(stage,'accepted-model.json');S.atomic(modelFile,accepted);if(build)build({root,stage,accepted,modelFile});else require('node:child_process').execFileSync(process.execPath,[path.join(root,'build.cjs'),'--model='+modelFile,'--out-dir='+stage],{cwd:root,encoding:'utf8',windowsHide:true});
  if(!sameIdentity(identity,executionIdentity(identityProvider)))throw Error('Deployment engine/harness/runtime changed while building staged HTML');
  const html=fs.readFileSync(path.join(stage,'omok.html'),'utf8');if(!html.includes(accepted.modelId)||html.includes('/*ENGINE*/')||html.includes('/*APP*/'))throw Error('Staged HTML does not embed the accepted model');S.atomic(path.join(stage,'omok.html'),html);if((S.read(active)?S.hash(S.read(active)):null)!==incumbentHash)throw Error('Incumbent changed during staged deployment');
  const transactionId=S.hash([stageId,S.hash(accepted)]),deliveryResult={activeModel:active,html:delivery,artifacts:htmlFiles.map(file=>({file,sha256:S.hash(html)})),transactionId,identity};const rows=[{file:active,staged:modelFile},...htmlFiles.map(file=>({file,staged:path.join(stage,'omok.html')}))];
  if(context){if(!permitted(root,context.dir))throw Error('Run adoption directory must remain in the repository');const adoptedEntry={...entry,delivery:deliveryResult,transactionId},state={...context.state,adoptions:[...(context.state.adoptions||[]),adoptedEntry].slice(-100),updatedAt:new Date().toISOString()};for(const [name,value] of [['champion.json',accepted],['models/'+accepted.modelId+'.json',accepted],['adoption.json',adoptedEntry],['state.json',state]]){if(name.startsWith('models/')&&!/^[A-Za-z0-9._-]+$/.test(accepted.modelId))throw Error('Invalid model identifier');const staged=path.join(stage,'run-'+rows.length+'.json');S.atomic(staged,value);rows.push({file:path.join(context.dir,name),staged});}const journalFile=path.join(context.dir,'adoptions.jsonl'),journalStaged=path.join(stage,'adoptions.jsonl'),previous=fs.existsSync(journalFile)?fs.readFileSync(journalFile,'utf8'):'';S.atomic(journalStaged,previous+(previous&&!previous.endsWith('\n')?'\n':'')+JSON.stringify(adoptedEntry)+'\n');rows.push({file:journalFile,staged:journalStaged});}
  if(accepted.adoption.exposure){const exposure=accepted.adoption.exposure,source=path.join(context?.dir||'','temporal-exposures.jsonl');if(!context||exposure.runDir!==context.dir||exposure.file!=='models/'+accepted.modelId+'.exposures.jsonl'||!/^[a-f0-9]{64}$/.test(exposure.sha256||'')||!fs.existsSync(source)||S.fileHash(source)!==exposure.sha256)throw Error('Accepted model temporal exposure provenance changed or is missing');const staged=path.join(stage,'model-exposures.jsonl');copyChecked(source,staged,exposure.sha256);if(S.fileHash(source)!==exposure.sha256)throw Error('Accepted model temporal exposure provenance changed while staging');rows.push({file:path.join(context.dir,exposure.file),staged});}
  const targets=rows.map((row,n)=>{const existed=fs.existsSync(row.file),backup=path.join(stage,'backup-'+n);if(existed)copyChecked(row.file,backup,S.fileHash(row.file));return {...row,sha256:S.fileHash(row.staged),existed,backup,backupSha256:existed?S.fileHash(backup):null};});intent={schemaVersion:2,root,transactionId,identity,status:'prepared',createdAt:new Date().toISOString(),targets,delivery:deliveryResult};verify(root,intent);S.atomic(path.join(dir,'transaction.json'),intent);const result=publish(root,intent,{identityProvider,onPublish:(file,n)=>onPublish(file,n-1)});if(context)Object.assign(context.state,S.read(path.join(context.dir,'state.json')));return result;
 }catch(error){let rollbackResult;if(intent){try{rollbackResult=rollback(root,intent,{reason:error.message,onRollback});}catch(restoreError){throw Error('Model delivery failed; rollback remains incomplete: '+error.message+'; '+restoreError.message);}}throw Error('Model delivery failed; '+(rollbackResult?'prior active model/artifacts/run adoption state restored: ':'prior destinations unchanged: ')+error.message);}finally{release();}
}
module.exports={deploy,recoverDeployment};
