'use strict';
const fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),readline=require('node:readline');
const S=require('./state.cjs'),R=require('./replay.cjs'),G=require('./generate.cjs'),A=require('./arena.cjs');
function parse(args){const out={command:args[0]||'status'};for(let n=1;n<args.length;n++){const a=args[n];if(!a.startsWith('--'))throw Error('Unknown argument '+a);const k=a.slice(2).split('=')[0],v=a.includes('=')?a.slice(a.indexOf('=')+1):args[n+1]&&!args[n+1].startsWith('--')?args[++n]:true;out[k]=v;}return out;}
function options(args){const map={'move-ms':'moveMs','analysis-ms':'analysisMs','validation-ms':'validationMs','min-pairs':'minPairs','batch-size':'batchSize','train-seconds':'trainSeconds','max-plies':'maxPlies','sample-every':'sampleEvery','max-samples':'maxSamples','stage-minutes':'stageMinutes','games-per-cycle':'gamesPerCycle'},out={};for(const key of ['seed','games','pairs','workers','epochs','minutes','exploration','confidence',...Object.keys(map)])if(args[key]!==undefined){const n=Number(args[key]);if(!Number.isFinite(n))throw Error('Invalid number for --'+key);out[map[key]||key]=n;}for(const key of ['python','device'])if(args[key])out[key]=String(args[key]);if(args['no-adopt'])out.autoAdopt=false;if(args['max-disk-gb'])out.maxDiskBytes=Number(args['max-disk-gb'])*1024**3;return out;}
function validateSettings(x){for(const k of ['games','pairs','minPairs','workers','epochs','batchSize','sampleEvery','maxSamples','maxPlies'])if(!Number.isInteger(x[k])||x[k]<1)throw Error(k+' must be a positive integer');if(x.workers>8)throw Error('At most 8 game workers are supported');if(x.moveMs<30||x.analysisMs<30||x.validationMs<30)throw Error('Search budgets must be at least 30ms');if(x.confidence<.9||x.confidence>=1||x.minPairs<32)throw Error('Promotion requires confidence >=90% and at least 32 independent paired families');if(x.exploration<0||x.exploration>1||x.minutes<=0||x.trainSeconds<=0)throw Error('Invalid exploration/time settings');}
function normalizeLesson(l,source){if(!l||typeof l.key!=='string'||!/^[012]{225}$/.test(l.key)||!Number.isInteger(l.bad)||l.bad<0||l.bad>=225||!Number.isInteger(l.good)||l.good<0||l.good>=225||l.bad===l.good||l.key[l.bad]!=='0'||l.key[l.good]!=='0')throw Error('Invalid existing lesson in '+source);return {...l,active:l.rules?.fivePriority!==false&&(!l.rulesId||l.rulesId===S.RULES_ID),labelRole:'existing heuristic only; never ground-truth training label',provenance:[...(l.provenance||[]),source]};}
function importLessons(context,payload,records,source){
 const doc=S.read(path.join(context.dir,'lessons.json'),{lessons:[]}),lessons=doc.lessons||[],incoming=Array.isArray(payload?.lessons)?payload.lessons:[];
 const study=records.find(r=>r.first===2&&r.events.length===42&&r.events[34]?.i===R.index('L7')&&r.events[0]?.i===R.index('H8')&&r.events[1]?.i===R.index('I8'));
 if(study){const E=require('../../src/node-engine.cjs')({model:null}),pre=R.replay({...study,events:study.events.slice(0,34)}).board,can=E.canonical(pre,2);incoming.push({key:can.key,bad:E.transformed(R.index('L7'),can.t),good:E.transformed(R.index('K9'),can.t),game:study.id,turn:35,type:'Preserved app 35th-move lesson',verified:true,scope:'Historical bounded VCF defense check; universal safety unproved',provenance:['src/app.js makeStudy k=34']});}
 const seen=new Set(lessons.map(l=>S.hash([l.key,l.bad,l.good,l.rules])));for(const raw of incoming){const l=normalizeLesson(raw,source),id=S.hash([l.key,l.bad,l.good,l.rules]);if(!seen.has(id)){lessons.push(l);seen.add(id);}}
 if(lessons.length>2000)throw Error('Existing lesson limit exceeded (2000)');S.atomic(path.join(context.dir,'lessons.json'),{schemaVersion:1,rulesId:S.RULES_ID,baselineCommit:context.state.baselineCommit,modelVersion:G.modelFor(context)?.modelId||'baseline',lessons,lessonHash:S.hash(lessons.filter(l=>l.active!==false)),scope:'Existing symmetric whole-position heuristics applied identically to both comparison engines; claims are not learning labels'});context.state.counters.existingLessons=lessons.filter(l=>l.active!==false).length;
}
function importRecords(context,input,args={}){
 const existing=S.read(path.join(context.dir,'records.json'),[]),text=input?fs.readFileSync(path.resolve(S.ROOT,input),'utf8'):null,payload=text&&/^[\s]*[{[]/.test(text)?JSON.parse(text):null,incoming=input?R.normalizeRecords(text,{firstPlayer:args.first?Number(args.first):undefined,seed:context.settings.seed,source:path.basename(input)}):[],built=R.bootstrap({seed:context.settings.seed}),all=[...existing],seen=new Set(existing.map(r=>r.contentId||R.familyFor(r.events,r.first)));
 for(const record of [...built.records,...incoming])if(!seen.has(record.contentId)){all.push(record);seen.add(record.contentId);}
 const grouped=R.groupFamilies(all,existing),priorGroups=S.read(path.join(context.dir,'family-groups.json'),{aliases:{}});S.atomic(path.join(context.dir,'family-groups.json'),{schemaVersion:1,aliases:{...priorGroups.aliases,...grouped.aliases},groups:grouped.groups,scope:'Canonical opening-stem/prefix families; links to existing training data cannot become final test data.'});
 // Existing split assignments remain immutable on repeated imports. Report
 // prefixes are seeds/teacher evidence, never silently accepted proof labels.
 importLessons(context,payload,all,input?path.basename(input):'existing app source bootstrap');S.atomic(path.join(context.dir,'records.json'),all);S.atomic(path.join(context.dir,'bootstrap.json'),{...built,records:undefined,importedCount:incoming.length,totalRecords:all.length,splitCounts:Object.fromEntries(['train','validation','test'].map(s=>[s,all.filter(r=>r.split===s).length]))});context.state.counters.importedRecords=all.length;context.state.progress={records:all.length,added:all.length-existing.length,bootstrapErrors:built.errors.length};S.save(context);return all;
}
function positionKey(row){return row.positionKey||(row.position?R.positionKey(row.position.board,row.position.p,row.position.firstPlayer):null);}
async function snapshotData(context,file){
 const source=path.join(context.dir,'dataset.jsonl');if(!fs.existsSync(source))throw Error('No training samples yet');const heldout=new Set(),finalTest=new Set(),families=new Map(),grouping=S.read(path.join(context.dir,'family-groups.json'),{aliases:{},groups:[]}),splitMap=new Map(grouping.groups.map(g=>[g.familyId,g.split]));
 const lines=async handler=>{const stream=readline.createInterface({input:fs.createReadStream(source),crlfDelay:Infinity});let lineNo=0;for await(const line of stream){lineNo++;if(!line.trim())continue;let row;try{row=JSON.parse(line);}catch{throw Error('Invalid dataset JSON at line '+lineNo);}row.familyId=grouping.aliases[row.familyId]||row.familyId;row.split=splitMap.get(row.familyId)||row.split;await handler(row);}};
 await lines(row=>{const prior=families.get(row.familyId);if(prior&&prior!==row.split)throw Error('Source family crosses data splits: '+row.familyId);families.set(row.familyId,row.split);if(row.split!=='train'){const k=positionKey(row);if(k)heldout.add(k);if(k&&row.split==='test')finalTest.add(k);}});
 const tmp=file+'.tmp-'+process.pid;fs.mkdirSync(path.dirname(file),{recursive:true});const fd=fs.openSync(tmp,'w'),seen=new Set(),positions=new Set(),counts={train:0,validation:0,test:0,deduplicated:0,overlapExcluded:0};
 try{await lines(row=>{if(seen.has(row.sampleId)){counts.deduplicated++;return;}seen.add(row.sampleId);const key=positionKey(row);if(row.split==='train'&&heldout.has(key)||row.split==='validation'&&finalTest.has(key)){counts.overlapExcluded++;return;}fs.writeSync(fd,JSON.stringify(row)+'\n');if(key)positions.add(key);counts[row.split]++;});}finally{fs.closeSync(fd);}fs.renameSync(tmp,file);const manifest={schemaVersion:1,file:path.basename(file),sha256:S.fileHash(file),rulesId:S.RULES_ID,featureVersion:S.FEATURE_VERSION,counts,uniquePositions:positions.size,families:families.size,createdAt:new Date().toISOString(),scope:'Family splits are immutable; exact D4/color-equivalent overlap is excluded with test > validation > train priority.'};S.atomic(file+'.manifest.json',manifest);context.state.dataset=manifest;context.state.counters.uniquePositions=positions.size;S.save(context);return manifest;
}
async function train(context,{deadline=Infinity,execute}={}){
 const cycle=context.state.cycle||1,data=path.join(context.dir,'datasets/cycle-'+cycle+'.jsonl'),output=path.join(context.dir,'candidate.json'),checkpoint=path.join(context.dir,'checkpoints/cycle-'+cycle+'.pt');
 if(!fs.existsSync(data))await snapshotData(context,data);const manifest=S.read(data+'.manifest.json');if(!manifest?.counts.train||!manifest?.counts.validation)throw Error('Training requires independent train and validation families. Generate more seeded games or import additional records.');if(S.fileHash(data)!==manifest.sha256)throw Error('Fixed training snapshot changed');
 if(!fs.existsSync(context.settings.python))throw Error('Local Python runtime is missing: '+context.settings.python);
 const maximum=Math.max(1,Math.min(context.settings.trainSeconds,(deadline-Date.now())/1000));const args=[path.join(__dirname,'train.py'),'train','--data',data,'--output',output,'--checkpoint',checkpoint,'--device',context.settings.device,'--epochs',String(context.settings.epochs),'--batch-size',String(context.settings.batchSize),'--max-seconds',String(maximum),'--stop-file',path.join(context.dir,'stop.flag')];if(fs.existsSync(checkpoint))args.push('--resume');const champion=path.join(context.dir,'champion.json');if(!fs.existsSync(checkpoint)){let priorCandidate=null;try{const prior=S.read(output);if(prior?.training?.updates>0)priorCandidate=require('../../src/neural-evaluator.js').validate(prior);}catch{}if(priorCandidate)args.push('--init-model',output);else if(fs.existsSync(champion))args.push('--init-model',champion);}
 const start=Date.now();const result=execute?await execute({python:context.settings.python,args,output,data,checkpoint}):await new Promise((resolve,reject)=>{const child=cp.spawn(context.settings.python,args,{cwd:S.ROOT,windowsHide:true,stdio:['ignore','pipe','pipe']});let last='',stdout='',stderr='';child.stdout.on('data',d=>{const s=d.toString();stdout+=s;last=(last+s).split('\n').slice(-1)[0];fs.appendFileSync(path.join(context.dir,'train.stdout.log'),s);process.stdout.write(s);});child.stderr.on('data',d=>{stderr=(stderr+d.toString()).slice(-12000);fs.appendFileSync(path.join(context.dir,'train.stderr.log'),d);});child.once('error',reject);child.once('exit',code=>resolve({code,stdout:stdout.slice(-20000),stderr,elapsedMs:Date.now()-start}));});
 context.state.training=S.read(output+'.training.json',{status:'unverified',process:result});context.state.training.process={exitCode:result.code,elapsedMs:result.elapsedMs};S.save(context);if(result.code!==0)throw Error('Training failed: '+result.stderr.slice(-1000));const model=S.read(output),evidence=A.trainingEvidence(model,context.state.training,manifest.sha256);context.state.training.verification=evidence;S.save(context);if(!evidence.passed){context.state.message='현재 데이터의 새 학습 모델이 검증되지 않아 이전 후보를 새 결과로 사용하지 않습니다.';S.save(context);return false;}require('../../src/neural-evaluator.js').validate(model);return true;
}
function deployModel(accepted,{root=S.ROOT,stageId,incumbentHash=null,build,onPublish=()=>{}}={}){
 require('../../src/neural-evaluator.js').validate(accepted);if(accepted.adoption?.accepted!==true)throw Error('Only accepted models may enter the deployment transaction');
 root=path.resolve(root);const allowedRoot=path.join(S.ROOT,'work').toLowerCase()+path.sep;if(root!==S.ROOT&&!root.toLowerCase().startsWith(allowedRoot))throw Error('Test deployment root must stay inside the repository work directory');if(!/^[A-Za-z0-9._-]{1,120}$/.test(stageId)||stageId==='.'||stageId==='..')throw Error('Invalid deployment stage identifier');
 const active=path.join(root,'src/active-model.json'),release=S.lock(path.join(root,'work/local-learning-20261007/deployment')),stage=path.join(root,'work/local-learning-20261007/adoption-stage/'+stageId),delivery=path.resolve(root,'../../outputs'),targets=[path.join(root,'outputs/omok.html'),path.join(root,'outputs/omok-gpu.html'),path.join(root,'dist/index.html'),path.join(delivery,'omok.html'),path.join(delivery,'omok-gpu.html')],backups=targets.map((file,n)=>({file,backup:path.join(stage,'previous-'+n+'.html'),existed:fs.existsSync(file)})),prior=fs.existsSync(active)?fs.readFileSync(active,'utf8'):null;
 try{fs.mkdirSync(stage,{recursive:true});for(const row of backups)if(row.existed)fs.copyFileSync(row.file,row.backup);if(prior)S.atomic(path.join(stage,'previous-active.json'),prior);S.atomic(path.join(stage,'accepted-model.json'),accepted);
  if(build)build({root,stage,accepted,modelFile:path.join(stage,'accepted-model.json')});else cp.execFileSync(process.execPath,[path.join(root,'build.cjs'),'--model='+path.join(stage,'accepted-model.json'),'--out-dir='+stage],{cwd:root,encoding:'utf8',windowsHide:true});
  const html=fs.readFileSync(path.join(stage,'omok.html'),'utf8');if(!html.includes(accepted.modelId)||html.includes('/*ENGINE*/')||html.includes('/*APP*/'))throw Error('Staged HTML does not embed the accepted model');if((S.read(active)?S.hash(S.read(active)):null)!==incumbentHash)throw Error('Incumbent changed during staged deployment');
  S.atomic(active,accepted);for(let n=0;n<targets.length;n++){S.atomic(targets[n],html);onPublish(targets[n],n);}return {activeModel:active,html:delivery,artifacts:targets.map(file=>({file,sha256:S.fileHash(file)}))};
 }catch(e){if(prior)S.atomic(active,prior);else if(fs.existsSync(active))fs.unlinkSync(active);for(const row of backups){try{if(row.existed)fs.copyFileSync(row.backup,row.file);else if(fs.existsSync(row.file))fs.unlinkSync(row.file);}catch{}}throw Error('Model delivery failed; prior active model/artifacts restored where available: '+e.message);}finally{release();}
}
function adopt(context){
 const candidate=path.join(context.dir,'candidate.json'),arena=S.read(path.join(context.dir,'arena.json')),model=S.read(candidate);if(!model)throw Error('No candidate model');const reasons=[...(arena?.rejectionReasons||['No completed independent evaluation'])],now=S.sourceIdentity(),settingsHash=S.hash({validationMs:context.settings.validationMs,pairs:context.settings.pairs,minPairs:context.settings.minPairs,confidence:context.settings.confidence}),data=path.join(context.dir,'datasets/cycle-'+context.state.cycle+'.jsonl'),active=path.join(S.ROOT,'src/active-model.json'),current=S.read(active),incumbentHash=current?S.hash(current):null;
 if(arena?.identity?.sourceHash!==now.sourceHash||arena?.identity?.harnessHash!==now.harnessHash)reasons.push('Engine/harness changed after evaluation');if(arena?.rulesId!==S.RULES_ID||arena?.settingsHash!==settingsHash)reasons.push('Rules/evaluation configuration changed');if(!fs.existsSync(data)||arena?.datasetSha256!==S.fileHash(data))reasons.push('Dataset changed after evaluation');if(arena?.incumbentHash!==incumbentHash)reasons.push('Active incumbent changed; fresh evaluation required');if(arena?.lessonHash!==S.hash(G.lessonsFor(context)))reasons.push('Existing lesson context changed after evaluation');const trainingCheck=A.trainingEvidence(model,S.read(candidate+'.training.json'),arena?.datasetSha256);if(!trainingCheck.passed)reasons.push(...trainingCheck.errors);const parityCheck=A.parity(model,S.read(candidate+'.parity.json'));if(!parityCheck.passed)reasons.push('Candidate parity identity/result changed');
 const allowed=!!arena?.passed&&arena.complete&&arena.candidateHash===S.hash(model)&&!reasons.length,entry={at:new Date().toISOString(),cycle:context.state.cycle,modelId:model.modelId,candidateHash:S.hash(model),adopted:allowed,decision:allowed?'accepted':arena?.complete?'kept-current':'insufficient-evidence',reason:allowed?'Passed rule/parity checks and conservative independent paired strength thresholds':reasons.join('; '),arena:'arena-cycle-'+context.state.cycle+'.json'};
 if(allowed){
  const accepted={...model,adoption:{accepted:true,at:entry.at,baselineCommit:context.state.baselineCommit,validationHash:S.hash(arena),sourceHash:now.sourceHash,harnessHash:now.harnessHash,datasetSha256:arena.datasetSha256,criteria:{minPairs:context.settings.minPairs,confidence:context.settings.confidence,method:arena.stats.baseline.method},stats:arena.stats}};
  entry.delivery=deployModel(accepted,{stageId:context.state.runId+'-'+context.state.cycle,incumbentHash:arena.incumbentHash});S.atomic(path.join(context.dir,'champion.json'),accepted);S.atomic(path.join(context.dir,'models/'+model.modelId+'.json'),accepted);
 }
 context.state.adoptions.push(entry);S.save(context);S.atomic(path.join(context.dir,'adoption.json'),entry);return entry;
}
async function timed(context,phase,fn){const start=Date.now();S.setPhase(context,phase,phase+' in local CPU/GPU pipeline');try{return await fn();}finally{context.state.timing=context.state.timing||[];context.state.timing.push({phase,cycle:context.state.cycle,elapsedMs:Date.now()-start,at:new Date().toISOString()});S.save(context);}}
async function cycle(context,args,deadline){
 importRecords(context,args.input,args);const total=context.settings.games;context.state.pipeline=context.state.pipeline||{stage:'analyze',target:Math.min(total,context.state.counters.generatedGames+(context.settings.gamesPerCycle||Math.min(100,total)))};if(context.state.cycle===0)context.state.cycle=1;S.save(context);
 while(Date.now()<deadline&&!S.stopped(context.dir)){
  if(S.diskBytes(context.dir)>=context.settings.maxDiskBytes){context.state.message='Disk budget reached';return false;}const pipeline=context.state.pipeline,remaining=deadline-Date.now();
  if(pipeline.stage==='analyze'){await timed(context,'analyze',()=>G.analyzeRecords(context,{deadline:Math.min(deadline,Date.now()+Math.min(context.settings.stageMinutes*60000,remaining*.15))}));if(S.stopped(context.dir))return false;pipeline.stage='generate';S.save(context);}
  else if(pipeline.stage==='generate'){await timed(context,'generate',()=>G.generate(context,{target:pipeline.target,deadline:Math.min(deadline,Date.now()+Math.min(context.settings.stageMinutes*60000,remaining*.4))}));if(S.stopped(context.dir))return false;pipeline.stage='train';S.save(context);}
  else if(pipeline.stage==='train'){if(deadline-Date.now()<2000)return false;const ok=await timed(context,'train',()=>train(context,{deadline:Math.min(deadline,Date.now()+context.settings.trainSeconds*1000)}));if(S.stopped(context.dir)||!ok)return false;pipeline.stage='validate';S.save(context);}
  else if(pipeline.stage==='validate'){const result=await timed(context,'validate',()=>A.validate(context,{deadline}));if(S.stopped(context.dir)||!result.complete){const decision={at:new Date().toISOString(),cycle:context.state.cycle,modelId:result.candidateModelId,candidateHash:result.candidateHash,adopted:false,decision:'insufficient-evidence',reason:'평가 예산·표본이 부족하여 이번 후보를 채택하지 않고 기존 엔진을 유지합니다. 저장된 같은 대국을 재개합니다.',rejectionReasons:result.rejectionReasons};context.state.decisions=context.state.decisions||[];context.state.decisions.push(decision);context.state.message=decision.reason;S.atomic(path.join(context.dir,'adoption.json'),decision);S.save(context);return false;}pipeline.stage='adopt';S.save(context);}
  else if(pipeline.stage==='adopt'){if(context.settings.autoAdopt)await timed(context,'adopt',()=>adopt(context));else{context.state.message='Automatic adoption disabled; validated candidate kept';S.save(context);}pipeline.stage='cycle-end';S.save(context);}
  else if(pipeline.stage==='cycle-end'){if(context.state.counters.generatedGames>=total)return true;const prior=context.state.validation;if(prior&&!prior.passed){context.state.message='Candidate did not meet strength threshold. Data and diagnostics retained; continuing only with new game experience.';}
   context.state.cycle++;context.state.pipeline={stage:'analyze',target:Math.min(total,context.state.counters.generatedGames+(context.settings.gamesPerCycle||100))};S.save(context);
  }else throw Error('Unknown pipeline stage '+pipeline.stage);
 }
 return false;
}
async function main(argv=process.argv.slice(2)){
 const args=parse(argv),dir=S.resolveRun(args.run),command=args.command;
 if(command==='help'||command==='--help'){console.log('Local no-API learning: init|import|analyze|generate|train|validate|adopt|cycle|stop|status --run=outputs/learning/default [--input=records.json] [--resume] [--games=100000 --workers=2 --minutes=60]. Search/data/games use CPU; neural training uses --device=cuda. Resume by re-running cycle --resume.');return;}
 if(command==='stop'){fs.mkdirSync(dir,{recursive:true});S.atomic(path.join(dir,'stop.flag'),'requested '+new Date().toISOString());console.log(JSON.stringify({status:'stop-requested',run:dir}));return;}
 if(command==='status'){console.log(JSON.stringify({run:dir,state:S.read(path.join(dir,'state.json')),settings:S.read(path.join(dir,'settings.json'))}));return;}
 const context=S.init(dir,options(args));validateSettings(context.settings);S.checkIdentity(context);const release=S.lock(dir);if(args.resume&&fs.existsSync(path.join(dir,'stop.flag')))fs.unlinkSync(path.join(dir,'stop.flag'));S.atomic(path.join(dir,'settings.json'),context.settings);
 const started=Date.now(),deadline=started+context.settings.minutes*60000;let complete=false;
 try{if(S.stopped(dir)){context.state.status='stopped';context.state.message='Stop requested; use --resume to continue';S.save(context);return;}
  if(command==='init'){importRecords(context,args.input,args);complete=true;}
  else if(command==='import'){importRecords(context,args.input,args);complete=true;}
  else if(command==='analyze'){importRecords(context,args.input,args);complete=await timed(context,'analyze',()=>G.analyzeRecords(context,{deadline}));}
  else if(command==='generate'){importRecords(context,args.input,args);complete=await timed(context,'generate',()=>G.generate(context,{deadline,target:context.settings.games}));}
  else if(command==='train'){if(!context.state.cycle)context.state.cycle=1;complete=await timed(context,'train',()=>train(context,{deadline}));}
  else if(command==='validate'){const r=await timed(context,'validate',()=>A.validate(context,{deadline}));complete=r.complete;}
  else if(command==='adopt'){await timed(context,'adopt',()=>adopt(context));complete=true;}
  else if(command==='cycle')complete=await cycle(context,args,deadline);
  else throw Error('Unknown command '+command);
  context.state.status=complete?'complete':'stopped';context.state.message=complete?'Requested local stage complete':S.stopped(dir)?'Stopped by user; checkpoints retained':context.state.validation&&!context.state.validation.complete?'평가가 미완료라 기존 엔진을 유지합니다. 같은 run으로 저장된 평가를 재개하세요.':'Time/resource budget reached; resume with the same run';context.state.lastRun={command,startedAt:new Date(started).toISOString(),elapsedMs:Date.now()-started,complete};S.save(context);console.log(JSON.stringify({run:dir,status:context.state.status,phase:context.state.phase,counters:context.state.counters,validation:context.state.validation,adoption:context.state.adoptions.at(-1),elapsedMs:Date.now()-started}));
 }catch(e){context.state.status='failed';context.state.message=e.message;context.state.errors.push({at:new Date().toISOString(),phase:context.state.phase,error:e.message});S.save(context);throw e;}finally{release();}
}
if(require.main===module)main().catch(e=>{console.error(e.stack||e);process.exitCode=1;});
module.exports={parse,options,validateSettings,normalizeLesson,importLessons,importRecords,snapshotData,train,deployModel,adopt,cycle,main};
