const fs=require('fs'),path=require('path'),{chromium}=require('playwright');
const positions=require('./positions.cjs'),root=path.resolve(__dirname,'../..'),out=path.join(root,'reports/performance');
(async()=>{const browser=await chromium.launch({executablePath:process.env.OMOK_BROWSER||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});const page=await browser.newPage();
 for(const f of ['reader-engine.js','forest-engine.js','unified-engine.js']){let s=fs.readFileSync(path.join(root,'src',f),'utf8');if(f.startsWith('reader'))s=s.replace('function createEngine(','function createReaderEngine(');await page.addScriptTag({content:s+'\n//# sourceURL='+f});}
 const session=await page.context().newCDPSession(page);await session.send('Profiler.enable');await session.send('Profiler.setSamplingInterval',{interval:1000});const summary=[];
 for(const [id,ms] of [['sixth-move',15000],['quiet-middle',25000]]){
  await session.send('Profiler.start');const result=await page.evaluate(({position,ms})=>{const e=createEngine({fivePriority:true}),t=performance.now(),r=e.analyze(position.board,position.p,ms,[]);const j=performance.now(),serialized=JSON.stringify(r);return {elapsed:performance.now()-t,engineMs:r.ms,serializationMs:performance.now()-j,serializedBytes:serialized.length,depth:r.depth,nodes:r.nodes,move:r.i==null?null:e.coord(r.i)};},{position:positions.find(p=>p.id===id),ms});
  const {profile}=await session.send('Profiler.stop');fs.writeFileSync(path.join(out,'profile-'+id+'.cpuprofile'),JSON.stringify(profile));
  const nodes=new Map(profile.nodes.map(n=>[n.id,n])),self=new Map(),groups=new Map();const parent=new Map();for(const n of profile.nodes)for(const child of n.children||[])parent.set(child,n.id);
  const categories={pattern:['line','run','win','winning','wins','shapes','mayStartForcing','exact'],legality:['inspect','legal','openThrees','threes','moveInfo'],candidates:['candidates','rank','ranked','searchMoves','positional'],evaluation:['evaluate','value','staticEval'],transposition:['__ttGet'],tactical:['forcing','vcf','forcedReplyTrap','quietTrap','threatWin','solve'],allocationGC:['(garbage collector)']};
  for(let k=0;k<(profile.samples||[]).length;k++){const id=profile.samples[k],ms=(profile.timeDeltas[k]||0)/1000;self.set(id,(self.get(id)||0)+ms);let n=id,group='other';while(n){const name=nodes.get(n)?.callFrame.functionName;const found=Object.entries(categories).find(([,names])=>names.includes(name));if(found){group=found[0];break;}n=parent.get(n);}groups.set(group,(groups.get(group)||0)+ms);}
  const top=[...self].sort((a,b)=>b[1]-a[1]).slice(0,20).map(([id,ms])=>({function:nodes.get(id).callFrame.functionName,file:nodes.get(id).callFrame.url,line:nodes.get(id).callFrame.lineNumber+1,self_ms:ms}));summary.push({position:id,budget:ms,result,groups:[...groups].sort((a,b)=>b[1]-a[1]),top});fs.writeFileSync(path.join(out,'profile-summary.json'),JSON.stringify(summary,null,2));console.log(JSON.stringify(summary.at(-1)));}
 await browser.close();})().catch(e=>{console.error(e);process.exit(1)});

