'use strict';
// Rebuild the user report from recorded final experiments; never rerun searches.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'),directory=path.join(root,'reports/strategy');
const args=process.argv.slice(2),option=(name,fallback)=>{const i=args.indexOf('--'+name);return i<0?fallback:args[i+1];};
if(args.includes('--help')){console.log('node tools/strategy-report.cjs --label v5140\nReads final known/holdout fixed and arena JSON, baseline-checks.json and release-validation.json. Writes reports/strategy/results.html.');process.exit(0);}
const label=option('label','v5140');if(!/^[A-Za-z0-9_-]+$/.test(label))throw Error('Invalid report label');
const read=file=>fs.existsSync(file)?JSON.parse(fs.readFileSync(file,'utf8')):null;
const manifest=read(path.join(root,'tools/strategy/manifest.json'))||{cases:[],knownReplays:[],games:[],openings:[],modes:[]};
const baseline=read(path.join(directory,'baseline-checks.json')),release=read(path.join(directory,'release-validation.json'));
const inputs=[label+'-known-fixed.json',label+'-holdout-fixed.json'];
const fixed=inputs.map(file=>({file,data:read(path.join(directory,file))})).filter(x=>x.data&&x.data.kind==='fixed');
const arenaFile=[label+'-arena.json',label+'-arena-arena.json'].find(file=>fs.existsSync(path.join(directory,file)));
const arena=arenaFile?read(path.join(directory,arenaFile)):null;
const rows=fixed.flatMap(x=>(x.data.rows||[]).map(r=>({...r,sourceFile:x.file}))),byId=new Map();
for(const row of rows)byId.set(row.id||[row.case,row.mode,row.repeat,row.version].join('/'),row);
const actualRows=[...byId.values()],pairMap=new Map();
for(const row of actualRows){const key=[row.case,row.mode,row.repeat??0].join('/');if(!pairMap.has(key))pairMap.set(key,{key,case:row.case,mode:row.mode,repeat:row.repeat??0});pairMap.get(key)[row.version]=row;}
const pairs=[...pairMap.values()],paired=pairs.filter(p=>p.baseline&&p.improved),pkg=read(path.join(root,'package.json'))||{};
const h=value=>String(value??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const coord=i=>Number.isInteger(i)&&i>=0&&i<225?String.fromCharCode(65+i%15)+(Math.floor(i/15)+1):'—';
const color=p=>p===1?'흑·노란 버섯':p===2?'백·초록 슬라임':'색 미확인';
const modeName={fast:'아주 빠르게',auto:'최적화 자동',deep25:'심층 분석'};
const statusName={PROVEN_WIN:'엔진 강제승 주장',PROVEN_LOSS:'엔진 강제패배 주장',BOUNDED_FAVORABLE:'제한 비교 추천',BLOCKING_UNCHECKED:'차단 후보·이후 안전 미확인',INCOMPLETE:'판단 미완료',UNRESOLVED:'승패 미증명',TERMINAL:'종료'};
const categoryName={A:'선공 공격 유지',B:'필수 방어',C:'후공 선제 차단',D:'방어와 공격 겸용',E:'반격 함정',F:'금수·장목·무효 확장',known:'기존 기보'};
const median=values=>{const xs=values.filter(Number.isFinite).sort((a,b)=>a-b);return xs.length?xs[Math.floor(xs.length/2)]:null;};
const n=value=>Number.isFinite(value)?Math.round(value).toLocaleString('ko-KR'):'—';
const time=value=>Number.isFinite(value)?(value/1000).toFixed(2)+'초':'—';
const date=value=>value&&!Number.isNaN(Date.parse(value))?new Date(value).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'}):'미기록';
const table=(heads,data)=>`<div class="scroll"><table><thead><tr>${heads.map(x=>`<th>${h(x)}</th>`).join('')}</tr></thead><tbody>${data.length?data.map(row=>`<tr>${row.map(x=>`<td>${x}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${heads.length}">실행 결과가 아직 없습니다.</td></tr>`}</tbody></table></div>`;
const codeReference=(file,needle,base=root)=>{const full=path.join(base,file);if(!fs.existsSync(full))return `<code>${h(file)}</code> (파일 미확인)`;const lines=fs.readFileSync(full,'utf8').split(/\r?\n/),line=lines.findIndex(x=>x.includes(needle));return `<code>${h(file)}${line>=0?':'+(line+1):''}</code>${line<0?' (해당 구문 미확인)':''}`;};
const baselineRoot=path.resolve(root,'../baseline');
const findings=[
 ['후보 탈락 가능성',`기존 Reader는 내부 일반 후보와 루트 후보 수를 제한합니다. 연결·차단 수가 제한 밖에 남는지는 국면별 실험 대상입니다. ${codeReference('src/reader-engine.js','k<16||forcing.has',baselineRoot)} · ${codeReference('src/reader-engine.js','k<24||forceSet.has',baselineRoot)}`],
 ['현재 차례와 가상 반격의 혼동',`기존 코드에는 상대가 강제 방어한 판에서 상대에게 다시 차례를 주어 VCF를 검사하는 경로가 있었습니다. 실제 차례는 내 후속 수입니다. 새 경로는 모든 합법 후속 수를 확인하는 기존 증명 검사를 사용합니다. ${codeReference('src/unified-engine.js','after[ends[0]]=3-p',baselineRoot)} → ${codeReference('src/unified-engine.js','const counter=forest.forcedReplyTrap')}`],
 ['선후공 상태 누락',`기보의 최초 착수자와 현재 착수자는 별개였지만 기존 Worker는 최초 착수자를 전달하지 않았습니다. 이제 PASS와 복기를 포함해 최초 착수자를 그대로 전달합니다. ${codeReference('src/unified-app.js','w.postMessage({',baselineRoot)} → ${codeReference('src/unified-app.js','w.postMessage({firstPlayer:')}`],
 ['빠른 결과와 심층 결과 결합',`기존 심층 교체는 후보 목록을 한 수로 줄였습니다. 완료된 동일 탐색의 상위 후보와 반증을 보존하도록 바꿨습니다. ${codeReference('src/unified-engine.js','candidates:[{i:extended.i',baselineRoot)} → ${codeReference('src/unified-engine.js','extended.candidates?.length')}`],
 ['초기 회귀 실패와 변경한 검사 계약',`첫 개선 후 전체 검사에는 Unified 32개 통과·3개 실패가 있었습니다 (<code>reports/strategy/full-regression.log</code>). 다음 검사에는 33개 통과·2개 실패가 있었습니다. 반격 진단 메타데이터를 복원하되 <code>riskOnly</code>로 명시해 추천 제외·감점에 사용하지 않습니다. F7을 무조건 금지하던 두 단정은 실제 차례에서 합법적인 후속 수가 살아 있다는 완료된 검사와 충돌했습니다. 기보를 유지하고 F7 선택 시 합법성·미증명 상태·실제 차례 검사·합법 생존 후속 수를 요구합니다. 짧은 진단이 중단되면 독립 1초 검사로 실제 생존 수를 확인해야 통과합니다. 전체 강제패배 표시가 기존 반증 후보 J6을 다시 추천하던 실제 fallback 오류는, 전체 승패 상태와 개별 반증 제외를 분리해 고쳤습니다. 검증된 J6 제외 단정은 변경하지 않았습니다. 최종 전체 검사 결과는 7번 실행 기록에서 확인합니다. ${codeReference('src/unified-engine.js','riskOnly:true,actualTurn:')} · ${codeReference('src/unified-engine.js','!bad.has(m.i)).map')} · ${codeReference('test/unified.cjs','A future opponent-first VCF')} · ${codeReference('test/strategy-policy.cjs','completed actual-turn all-continuation proof')}`]
];
const badRow=r=>!!r.invalid||!!r.error||!!r.acceptanceProblems?.length;
const negative=paired.filter(p=>badRow(p.improved)||(p.improved.result?.depth??0)<(p.baseline.result?.depth??0));
const holdout=actualRows.filter(r=>r.split==='holdout'),holdoutPlanned=144;
const independentFamilies=new Set(holdout.map(r=>r.family||r.case)).size;
const games=arena?.games||manifest.games.map(g=>({...g,status:'pending',moves:[]})),verifiedGames=[],gameIssues=[];
let frozenEngine=null,replayTools=null;
try{frozenEngine=require(path.join(baselineRoot,'src/node-engine.cjs'))();replayTools=require('./strategy/replay.cjs');}catch{}
for(const game of games){if(game.status!=='completed')continue;
 try{const opening=manifest.openings.find(o=>o.id===game.opening);if(!opening||!frozenEngine||!replayTools)throw Error('독립 재생기 또는 오프닝 없음');
  const played=replayTools.replay(frozenEngine,{firstPlayer:opening.firstPlayer,moves:[...opening.moves,...(game.moves||[])]});
  const end=replayTools.outcome(frozenEngine,played.board,played.p);
  if(!end||end.status!=='completed'||!['played-exact-five','full-board'].includes(end.reason)||end.winner!==game.winner)throw Error('실제 종료 재생 결과 불일치');
  verifiedGames.push({...game,verifiedReason:end.reason});
 }catch(error){gameIssues.push({game:game.id,reason:String(error.message||error)});}
}
const wdl=(mode,first)=>{const selected=games.filter(g=>g.mode===mode&&g.improvedFirst===first),done=verifiedGames.filter(g=>g.mode===mode&&g.improvedFirst===first);let win=0,draw=0,loss=0;
 for(const game of done){const side=first?game.firstPlayer:3-game.firstPlayer;if(game.winner==null)draw++;else if(game.winner===side)win++;else loss++;}
 return [h(modeName[mode]||mode),first?'개선 엔진 선공':'개선 엔진 후공',n(selected.length),`${win} / ${draw} / ${loss}`,n(done.length),n(selected.filter(g=>g.status==='pending').length),n(selected.filter(g=>g.status!=='pending'&&!done.some(d=>d.id===g.id)).length)];};
const commands=Array.isArray(release?.tests)?release.tests:Array.isArray(release?.checks)?release.checks:Array.isArray(release?.commands)?release.commands:[];
const failures=commands.filter(c=>c.exitCode!=null&&c.exitCode!==0||c.passed===false||c.ok===false);
// Strategy score changes and one PV are deliberately insufficient. Confirmation
// requires separately reviewed evidence and complete, adequately balanced data.
const outsideEvidence=['A','C','D'].every(k=>release?.independentStrategyEvidence?.[k]?.verified===true&&typeof release.independentStrategyEvidence[k].basis==='string'&&release.independentStrategyEvidence[k].basis.trim()&&release.independentStrategyEvidence[k].basis!=='strategy-score');
const tacticalComplete=['B','E','F'].every(k=>holdout.filter(r=>r.version==='improved'&&r.category===k).length===12)&&!holdout.some(badRow);
const confirmed=release?.performanceConfirmed===true&&outsideEvidence&&tacticalComplete&&holdout.length>=holdoutPlanned&&holdout.every(r=>r.auditComplete===true)&&paired.filter(p=>p.improved.split==='holdout'&&p.baseline.externalBudgetMs===p.improved.externalBudgetMs).length>=72&&verifiedGames.length>=36&&!failures.length&&!gameIssues.length;
const conclusion=confirmed?'구현 완료 · 독립 검증한 범위에서 개선 확인':failures.length?'구현 변경 완료 · 회귀 오류 확인, 성능 개선 미확인':'구현 완료 · 성능 개선 미확인';
const lineHTML=line=>(line||[]).map(m=>`${h(color(m.p))} ${h(m.coord||coord(m.i))}`).join(' → ')||'미기록';
const factsHTML=f=>!f?'미기록':`다음 착수자 ${h(color(f.currentSide))}: 즉시 5목 승리점 ${h((f.ownWinningPoints||[]).join(', ')||'없음')} / 상대 승리점 ${h((f.opponentWinningPoints||[]).join(', ')||'없음')}${f.requiredBlock?` / 유일 합법 방어 ${h(f.requiredBlock)}`:''}${f.independentLoss?' / 즉시 위협 방어 불가':''}`;
function branchesHTML(row){return (row?.replyBranches||[]).length?row.replyBranches.map(b=>`<div class="branch"><b>상대 ${h(b.engine==='improved'?'개선':'baseline')} 엔진 응수</b> · 예산 ${time(b.externalBudgetMs)} · 실측 ${time(b.elapsedMs)} · 깊이 ${n(b.response?.depth)} · 노드 ${n(b.response?.nodes)}<p>${lineHTML(b.line)}</p><p>${factsHTML(b.factsAfterReply)}</p><p>후속: ${factsHTML(b.factsAfterFollowup)}</p><p>상태 ${h(b.status||'미완료')}${b.followup?` · 내 후속 계산 ${h(b.followup.engine)} 예산 ${time(b.followup.externalBudgetMs)} / 실측 ${time(b.followup.elapsedMs)} / 깊이 ${n(b.followup.result?.depth)} / 노드 ${n(b.followup.result?.nodes)}`:''}${b.error||b.invalid?` · 오류 ${h(b.error||b.invalid)}`:''}</p></div>`).join(''):'응수 분기가 아직 기록되지 않았습니다.';}
function pairDetail(pair){const a=pair.baseline,b=pair.improved,meta=manifest.cases.find(c=>c.id===pair.case)||manifest.knownReplays.find(c=>c.id===pair.case),row=b||a;
 const stat=r=>[h(r?.version==='improved'?'개선':'baseline'),h(coord(r?.result?.i)),time(r?.externalBudgetMs)+' / '+time(r?.workerInternalBudgetMs),time(r?.elapsedMs),n(r?.result?.depth),n(r?.result?.nodes),h(statusName[r?.result?.assessmentStatus||r?.result?.proofStatus]||'미기록'),h(r?.independentProofStatus==='played-exact-five-verified'?'즉시 정확한 5목 재검사 완료':r?.independentProofStatus==='full-certificate-not-audited'||r?.result?.lossProven?'전체 방어 분기 독립 증명 검증 미완료':'승패 증명 주장 없음')];
 return `<article><h3>${h(pair.case)} · ${h(categoryName[row?.category]||row?.category)} · ${h(modeName[pair.mode]||pair.mode)} · 반복 ${n(pair.repeat+1)}</h3><p>${h(color(row?.currentSide))} ${row?.currentSide===row?.firstPlayer?'선공':'후공'} 차례. ${meta?.moves?`입력 기보: ${h(meta.moves.map(m=>typeof m==='string'?m:m.coord||coord(m.i)).join(' '))}`:''}</p>${table(['엔진','추천','외부 / 내부 시간 예산','실측 시간','완료 깊이','노드','판정','독립 검증'],[stat(a),stat(b)])}<div class="twocol"><div><h4>baseline 실제 제한 응수 분기</h4>${branchesHTML(a)}</div><div><h4>개선 실제 제한 응수 분기</h4>${branchesHTML(b)}</div></div><p>두 상대 엔진의 제한 시간 응수를 비교했습니다. 모든 합법 응수 중 최선이라는 증명은 없습니다. 기하학적 3·4 모양과 추정 점수만으로 공격 유지·선제 차단·주도권 탈환 또는 필승을 선언하지 않습니다.</p>${a?.externalBudgetMs!==b?.externalBudgetMs?'<p class="bad">두 엔진 예산이 달라 유효한 동등 조건 비교로 채택할 수 없습니다.</p>':''}</article>`;
}
function representative(first){const choices=paired.filter(p=>{const r=p.improved;return (r.currentSide===r.firstPlayer)===first;}).sort((a,b)=>{const x=a.improved,y=b.improved;return (x.split==='holdout'?0:1)-(y.split==='holdout'?0:1)||({'auto':0,deep25:1,fast:2}[a.mode]??3)-({'auto':0,deep25:1,fast:2}[b.mode]??3)||a.case.localeCompare(b.case)||a.repeat-b.repeat;});return choices[0]?pairDetail(choices[0]):'<p>해당 역할의 같은 국면·같은 모드 비교가 아직 완성되지 않았습니다. 추천 좌표나 승리 수순을 만들어 채우지 않습니다.</p>';}
const modeTable=(manifest.modes||[]).map(mode=>{const data=holdout.filter(r=>r.mode===mode.id),p=paired.filter(x=>x.mode===mode.id&&x.improved.split==='holdout');return [h(modeName[mode.id]||mode.id),`${data.length} / 48`,n(p.length),time(median(data.filter(r=>r.version==='baseline').map(r=>r.elapsedMs))),time(median(data.filter(r=>r.version==='improved').map(r=>r.elapsedMs))),n(median(data.filter(r=>r.version==='baseline').map(r=>r.result?.depth))),n(median(data.filter(r=>r.version==='improved').map(r=>r.result?.depth))),n(data.filter(badRow).length),n(data.filter(r=>r.result?.timedOut||r.result?.analysisIncomplete).length)];});
const allPairsTable=paired.sort((a,b)=>a.case.localeCompare(b.case)||a.mode.localeCompare(b.mode)||a.repeat-b.repeat).map(p=>{const a=p.baseline,b=p.improved;return [h(p.case),h(modeName[p.mode]||p.mode),n(p.repeat+1),h(coord(a.result?.i)),h(coord(b.result?.i)),`${n(a.result?.depth)} → ${n(b.result?.depth)}`,`${time(a.elapsedMs)} → ${time(b.elapsedMs)}`,h([...b.acceptanceProblems||[],b.invalid,b.error].filter(Boolean).join('; ')||'없음'),`<details><summary>실제 분기</summary><b>baseline</b>${branchesHTML(a)}<b>개선</b>${branchesHTML(b)}</details>`];});
const changedFiles=['src/strategy-engine.js','src/reader-engine.js','src/forest-engine.js','src/unified-engine.js','src/unified-app.js','src/app.js','src/gpu-app.js','src/node-engine.cjs','build.cjs','package.json','test/unified.cjs','test/strategy-context.cjs','test/strategy-policy.cjs','test/strategy-engine.cjs','test/strategy-manifest.cjs','test/strategy-manifest-replay.cjs','test/strategy-proof.cjs','tools/strategy-report.cjs','tools/strategy/run.cjs','tools/strategy/browser.cjs','tools/strategy/replay.cjs','tools/performance/ui-smoke.cjs'].filter(file=>fs.existsSync(path.join(root,file)));
const sourceHashes=Object.fromEntries(changedFiles.map(file=>[file,crypto.createHash('sha256').update(fs.readFileSync(path.join(root,file))).digest('hex')]));
const testRows=[...(baseline?[{command:baseline.command,exitCode:baseline.exitCode,note:'개선 직전 baseline · Reader '+baseline.readerScenarios+' / Unified '+baseline.unifiedScenarios}]:[]),...commands].map(c=>[h(c.command||c.name||c.test||'검사'),c.exitCode==null?h(c.status||'종료 코드 미기록'):h('종료 코드 '+c.exitCode),h(c.note||c.scope||'')]);
const metadata=fixed[0]?.data.metadata||arena?.metadata;
const unpairedTable=pairs.filter(p=>!p.baseline||!p.improved).map(p=>[h(p.case),h(modeName[p.mode]||p.mode),n(p.repeat+1),p.baseline?`${h(coord(p.baseline.result?.i))} · ${time(p.baseline.elapsedMs)} · 깊이 ${n(p.baseline.result?.depth)}`:'미실행',p.improved?`${h(coord(p.improved.result?.i))} · ${time(p.improved.elapsedMs)} · 깊이 ${n(p.improved.result?.depth)}`:'미실행']);
const sections=[
 `<section id="s1"><h2>1) 현재 엔진의 문제: 재현 사례와 코드 근거</h2><p>개선 전 기준은 GPU 업데이트를 포함한 실제 작업 직전 소스입니다. UI의 ‘기존 CPU’는 연산 방식이며 baseline 엔진을 뜻하지 않습니다. 기준 커밋 <code>${h(manifest.baselineCommit)}</code>, 기준 아카이브 SHA-256 <code>${h(manifest.baselineArchiveSha256)}</code>.</p>${table(['확인 사항','코드와 해석'],findings.map(([name,body])=>[h(name),body]))}<p>상대 평가의 1.1 배율과 주변 돌 수만으로 원인을 확정하지 않았습니다. 후보 제한이 실제 좋은 수를 버렸는지, 구조 평가가 어떤 국면에서 유효했는지는 아래 실전 분기와 독립 검증 범위에서만 판단합니다. 이전 필승·강제패배 주장은 미완성 증명과 구분합니다.</p><p>기존 기보 측정 ${n(actualRows.filter(r=>r.split==='known').length)}회. 2수·4수 초기 접두부는 같은 기보의 일부이며 별도 독립 사례로 집계하지 않습니다.</p></section>`,
 `<section id="s2"><h2>2) 변경 내용: 어떤 판단과 탐색이 달라졌는지</h2><ul><li>합법 공격축, 열린 확장점, 공통 연결점과 여러 방향의 협력을 찾아 연결·차단·겸용 후보를 탐색에 보존합니다. ${codeReference('src/strategy-engine.js','function structure')} · ${codeReference('src/strategy-engine.js','function select')}</li><li>내 수 → 상대 응수 → 내 후속 수를 제한 범위에서 비교합니다. 미완료 탐색과 점수는 증명이 아니며 반격 검사는 실제 차례를 따릅니다. ${codeReference('src/strategy-engine.js','function probe')} · ${codeReference('src/forest-engine.js','function forcedReplyTrap')}</li><li>색·최초 착수자·현재 착수자·주도권 근거를 분리하고 PASS·복기·Worker·사전 응수에 전달합니다. ${codeReference('src/app.js','function rebuild')} · ${codeReference('src/unified-app.js','const positionKey=')}</li><li>임시·최종·시간 초과 추천에 동일한 합법성·반증 기준을 적용하고 완료된 상위 후보를 보존합니다. 판정은 강제승, 제한 비교 추천, 차단 후 안전 미확인, 판단 미완료, 강제패배를 구분합니다. ${codeReference('src/unified-engine.js','function finalizeResult')}</li></ul><p>즉시 정확한 5목·필수 방어가 전략보다 우선합니다. 양측 3·3 금지, 4·4 허용, 6목 이상 승리 불인정과 기존 실행 경로를 유지합니다. 시간 예산을 늘려 개선으로 계산하지 않습니다.</p></section>`,
 `<section id="s3"><h2>3) 선공 사례: 개선 전후 좌표·수순·차이</h2><p>결과의 좋고 나쁨을 기준으로 고르지 않고, 처음 보는 평가용 사례를 우선한 뒤 자동 모드·사례 ID 순으로 대표 국면을 선택했습니다.</p>${representative(true)}</section>`,
 `<section id="s4"><h2>4) 후공 사례: 개선 전후 좌표·수순·차이</h2><p>후공을 영구 수비 역할로 고정하지 않습니다. 차단 뒤의 공격과 반격은 기록된 실제 제한 응수와 다음 합법 5목 지점으로 검토합니다.</p>${representative(false)}</section>`,
 `<section id="s5"><h2>5) 모드별 테스트 및 선후공 교대 대국 결과</h2><p>고정 평가 계획은 홀드아웃 12국면 × 3모드 × 2반복 × 2엔진 = <b>144회 엔진 분석</b>이며 72개 전후 쌍입니다. 현재 ${holdout.length} / 144회, 완성된 전후 쌍 ${paired.filter(p=>p.improved.split==='holdout').length} / 72개, 독립 국면 가족 ${independentFamilies} / 12개입니다. 회전·반전·색 교환은 독립 표본 수를 늘리지 않습니다.</p>${table(['모드','실행 / 예정','완성 쌍','baseline 중앙 시간','개선 중앙 시간','baseline 중앙 깊이','개선 중앙 깊이','수용 기준/실행 오류','시간/판단 미완료'],modeTable)}<p>자동 예산은 frozen baseline의 실제 국면별 예산을 두 엔진에 동일하게 전달합니다. fast 900ms, deep25 25,000ms, Worker 예약 시간도 동일합니다. 같은 검증된 패턴 표를 공유하고 매 요청 새 Worker·새 탐색 캐시를 사용합니다. GPU 최초 준비는 분석 시간과 별도입니다.</p><p>실측 장치: ${h(fixed[0]?.data.cpu?.model||arena?.cpu?.model||'미기록')} / 브라우저 ${h(metadata?.browser||'미기록')} / 연산 ${h(metadata?.gpu?.mode||'미기록')} / GPU 패턴 ${n(metadata?.gpu?.verifiedPatterns)}개 / 준비 ${time(metadata?.gpu?.totalMs)}.</p>${table(['모드','개선 역할','계획 대국','승 / 무 / 패','실제 종료 재생 확인','미시작','중단·미완료'],(manifest.modes||[]).flatMap(m=>[wdl(m.id,true),wdl(m.id,false)]))}<p>6개 같은 오프닝에서 선후공을 교대한 36대국을 계획했습니다. 현재 실제 정확한 5목 또는 만판 종료를 재생 확인한 대국 ${verifiedGames.length}개입니다. 강제패배 표시나 높은 평가점수로 대국을 종료·승패 처리하지 않았습니다. 미시작·시간 한도 중단·합법 수 없음은 무승부에 넣지 않습니다.</p><details><summary>모든 실제 대국과 중단 사유</summary>${table(['대국','오프닝','모드','개선 역할','기록 상태','추가 착수 수','사유','실제 결과'],games.map(g=>[h(g.id),h(g.opening),h(modeName[g.mode]||g.mode),g.improvedFirst?'선공':'후공',h(g.status),n(g.moves?.length||0),h(g.reason||'미시작'),h(verifiedGames.some(x=>x.id===g.id)?g.winner==null?'만판 무승부':color(g.winner)+' 승리':'종료 미확인')]))}</details><details><summary>모든 고정 국면 전후 쌍과 실제 응수 분기</summary>${table(['국면','모드','반복','baseline 좌표','개선 좌표','완료 깊이','실측 시간','개선 오류/기준 이탈','응수'],allPairsTable)}</details></section>`,
 `<section id="s6"><h2>6) 그대로 남은 약점과 검증하지 못한 부분</h2><p class="verdict">${h(conclusion)}</p><ul><li>A·C·D의 공격 유지·선제 차단·주도권 탈환은 점수 변화만으로 확인할 수 없습니다. 실제 분기는 제한된 두 상대 엔진 응수이며 모든 최선 방어의 독립 증명은 아닙니다.</li><li>완성된 증명 검증이 별도로 없는 엔진의 강제승·강제패배 표시는 엔진 주장으로 기록했습니다. 한 줄 PV나 사삼·4·4 모양 자체로 필승을 선언하지 않습니다.</li><li>현재 결과는 제한된 국면과 오프닝 표본입니다. 미완료 대국과 불리한 결과를 제외하지 않았고, 더 깊게 읽었다는 사실만으로 실력이 개선됐다고 결론 내리지 않습니다.</li></ul><p>개선 쪽 수용 기준 이탈·오류 또는 완료 깊이 감소가 나타난 전후 쌍 ${negative.length}개. 깊이 감소 자체가 열등한 수의 증명은 아니지만 탐색량·시간 비용의 약점으로 공개합니다.</p>${table(['국면 / 모드 / 반복','baseline → 개선 깊이','추천 변화','오류 / 미확인'],negative.map(p=>[h(p.key),`${n(p.baseline.result?.depth)} → ${n(p.improved.result?.depth)}`,`${h(coord(p.baseline.result?.i))} → ${h(coord(p.improved.result?.i))}`,h([...p.improved.acceptanceProblems||[],p.improved.invalid,p.improved.error].filter(Boolean).join('; ')||'같은 예산의 완료 깊이 감소')]))}${gameIssues.length?table(['대국 재생 검증 문제','사유'],gameIssues.map(x=>[h(x.game),h(x.reason)])):''}</section>`,
 `<section id="s7"><h2>7) 변경 파일, 재현 명령, 실제 실행한 테스트, 버전 정보</h2><p>버전 ${h(pkg.version)} / 사용자 진입점 <code>outputs/omok.html</code> / 기존 배포 <code>outputs/omok-gpu.html</code>, <code>dist/index.html</code>. 기존 빌드가 산출물을 함께 갱신합니다.</p>${table(['실행 기록','결과','범위'],testRows)}${release?'':'<p>최종 release-validation.json이 아직 없어 개선 후 전체 검사 통과를 주장하지 않습니다.</p>'}<pre>npm.cmd test\nnpm.cmd run test:strategy\nnode tools/strategy/run.cjs fixed --label ${h(label)}-known --split known --minutes 60 --compute gpu\nnode tools/strategy/run.cjs fixed --label ${h(label)}-holdout --split holdout --minutes 60 --compute gpu\nnode tools/strategy/run.cjs arena --label ${h(label)} --minutes 60 --stage 1 --compute gpu\nnode tools/strategy-report.cjs --label ${h(label)}</pre><p>위 비교 명령은 새 실행 또는 같은 고정 소스·조건의 재개 명령입니다. ‘실행 기록’에 없는 명령을 이미 통과한 검사로 보지 않습니다. 단계별 계산 한도는 최대 1시간이며 다음 단계 확대에는 결과 검토가 필요합니다.</p><details><summary>현재 코드 파일·SHA-256 및 입력 보고서</summary><pre>${h(JSON.stringify({reportInputs:fixed.map(x=>x.file).concat(arenaFile||[]),baselineCheck:'baseline-checks.json',releaseCheck:release?'release-validation.json':'미작성',manifestHash:fs.existsSync(path.join(root,'tools/strategy/manifest.json.sha256'))?fs.readFileSync(path.join(root,'tools/strategy/manifest.json.sha256'),'utf8').trim():null,sourceHashes},null,2))}</pre></details>${release?`<details><summary>최종 검증 원본 기록</summary><pre>${h(JSON.stringify(release,null,2))}</pre></details>`:''}</section>`
];
const html=`<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>숲속 오목 v${h(pkg.version)} 전략 개선 검증</title><style>body{margin:0;background:#f1f5ef;color:#17352b;font:15px/1.7 system-ui,"Malgun Gothic",sans-serif}main{max-width:1180px;margin:auto;padding:34px 20px}header,section{background:white;border:1px solid #d6e2d4;border-radius:16px;padding:24px;margin:0 0 20px}h1{font-size:30px;line-height:1.3}h2{font-size:23px}h3{font-size:18px}.verdict{background:#fff2d1;border-left:5px solid #b78a23;padding:14px;font-weight:700}.scroll{overflow:auto}table{border-collapse:collapse;width:100%;font-size:13px}th,td{padding:10px;border:1px solid #dce6da;vertical-align:top}th{background:#e9f1e5;text-align:left}code,pre{font:12px/1.6 ui-monospace,Consolas,monospace;overflow-wrap:anywhere}pre{white-space:pre-wrap;background:#f4f6f1;padding:14px}details{margin:12px 0}summary{cursor:pointer;font-weight:600}.twocol{display:grid;grid-template-columns:1fr 1fr;gap:16px}.branch,article{border:1px solid #dce6da;padding:14px;margin:12px 0;border-radius:10px}.branch p{margin:8px 0}.bad{color:#a52d23}nav a{display:inline-block;margin:0 12px 8px 0;color:#236642}@media(max-width:760px){.twocol{grid-template-columns:1fr}main{padding:16px 10px}header,section{padding:16px}}</style><main><header><p>숲속 오목 연구실 · v${h(pkg.version)}</p><h1>공격 연결·선제 차단·주도권 탈환 검증 보고서</h1><p class="verdict">${h(conclusion)}</p><p>생성 ${date(new Date().toISOString())} (한국 시간) · 비교 라벨 ${h(label)} · 임시 harness-smoke 결과는 성능 집계에서 제외했습니다.</p><nav>${sections.map((_,i)=>`<a href="#s${i+1}">${i+1}번 항목</a>`).join('')}</nav></header>${sections.join('')}</main></html>`;
const finalHTML=unpairedTable.length?html.replace('<section id="s6">',`<details><summary>분석은 기록됐으나 전후 쌍이 완성되지 않은 국면</summary>${table(['국면','모드','반복','baseline 기록','개선 기록'],unpairedTable)}</details><section id="s6">`):html;
fs.mkdirSync(directory,{recursive:true});const output=path.join(directory,'results.html');fs.writeFileSync(output,finalHTML);
console.log(JSON.stringify({report:output,label,conclusion,holdoutAnalyses:holdout.length,holdoutPlanned,pairedComparisons:paired.length,verifiedCompletedGames:verifiedGames.length,plannedGames:games.length,negativePairs:negative.length,finalInputFiles:fixed.map(x=>x.file).concat(arenaFile||[])},null,2));
